const { workspacePage } = require('../../app/pages/index')
const url=options=>'/pages/organizations/index?'+Object.entries(options).filter(([,v])=>v).map(([k,v])=>k+'='+encodeURIComponent(v)).join('&')
Page(workspacePage({
 setup(options){this.context={view:options.view||'organizations',organizationId:options.organizationId,runId:options.runId};this.values={};this.form=null;this.page=1;this.active=true},
 keepOnShow(){return Boolean(this.form)},reset(){this.values={};this.form=null;this.active=false},
 async fetch(runtime){this.page=1;this.form=null;return Object.assign({fields:null,preview:null,confirmationOpen:false,result:null,formError:''},await runtime.organizations.view(this.context))},
 methods:{
 select(e){const row=this.data.list.find(r=>r.id===e.detail.id);if(!row)return;if(this.context.view==='organizations')wx.navigateTo({url:url({view:'context',organizationId:row.id})});else if(this.context.view==='runs')wx.navigateTo({url:url({view:'run',organizationId:this.context.organizationId,runId:row.id})})},
 async action(e){const action=e.currentTarget.dataset.key;if(!this.data.actions.some(a=>a.key===action)||this.data.status==='submitting')return;const views={GOVERN:'members',ASSESSMENT_DELIVERY:'runs',RUNS:'runs',REPORTING:'reporting',SAFETY:'safety',PROGRESS:'progress'};if(views[action]){wx.navigateTo({url:url(Object.assign({},this.context,{view:views[action]}))});return}
  const sequence=this.sequence;this.setData({status:'submitting',formError:''});try{const service=getApp().runtime.organizations;this.actionKey=action;
   if(action==='PREVIEW_PUBLISH'){const preview=await service.preview(this.context.organizationId,this.context.runId,this.data.version);if(sequence!==this.sequence)return;this.previewVersion=this.data.version;this.setData({status:'ready',preview,previewFacts:preview.tracks.flatMap((track,index)=>[{label:'测评项目 '+(index+1)+' · 评价对象',value:String(track.subjectCount)+' 人'},{label:'作答者',value:String(track.respondentCount)+' 人'},{label:'拟生成任务',value:String(track.executionCount)+' 份'}]),confirmationOpen:false,fields:null});return}
   if(action==='CLOSE'||action==='CANCEL'){this.form={fields:[],confirmation:'确认'+(action==='CLOSE'?'关闭':'取消')+'当前测评批次？服务器将处理尚未完成的执行记录。'}}else this.form=await service.form(Object.assign({},this.context,{action}));if(sequence!==this.sequence)return;this.values={};this.setData({status:'ready',fields:this.form.fields,formTitle:this.form.title,notice:this.form.notice||'',confirmation:this.form.confirmation||'请核对信息后提交',preview:null})
  }catch(error){if(sequence===this.sequence)this.setData({status:'ready',formError:error.message})}
 },
 change(e){if(!this.form||this.data.status==='submitting')return;const key=e.currentTarget.dataset.key;this.values[key]=e.detail.value;if(key==='resourceIndex'){this.values={resourceIndex:e.detail.value};this.form.fields=getApp().runtime.organizations.trackFields(this.form.resources,e.detail.value)}this.setData({fields:this.form.fields.map(f=>Object.assign({},f,{value:this.values[f.key]===undefined?f.value:this.values[f.key]}))})},
 choose(e){const key=e.currentTarget.dataset.key,f=this.form.fields.find(f=>f.key===key);if(!f||!f.selector||this.data.status==='submitting')return;wx.navigateTo({url:'/pages/select/index?domain='+f.selector,events:{selected:value=>{if(!this.active)return;this.values[key]=value.value;this.setData({fields:this.data.fields.map(f=>f.key===key?Object.assign({},f,{selectionLabel:value.label}):f)})}}})},
 confirm(){if(this.data.status==='submitting')return;this.setData({confirmationOpen:true})},cancel(){if(this.data.status!=='submitting')this.setData({confirmationOpen:false})},
 async submit(){if(!this.data.confirmationOpen||this.data.status==='submitting')return;const sequence=this.sequence;this.setData({status:'submitting',formError:''});try{const service=getApp().runtime.organizations;if(this.data.preview)await service.publish(this.context.organizationId,this.context.runId,this.previewVersion);else if(['CLOSE','CANCEL'].includes(this.actionKey))await service.lifecycle(this.context.organizationId,this.context.runId,this.actionKey);else await service.execute(Object.assign({},this.context,{action:this.actionKey}),this.form,this.values);if(sequence!==this.sequence)return;this.form=null;this.values={};await this.load();this.setData({result:'服务器已确认操作完成'})}catch(error){if(sequence!==this.sequence)return;this.setData({status:'ready',confirmationOpen:false,formError:error.message+(error.status===409?'。请刷新批次后重新预览。':!error.status?'。服务器确认结果未知，请刷新列表核对。':'')});if(!error.status)this.setData({fields:null,preview:null})}},
 async more(){if(!this.data.hasMore||this.data.status==='submitting')return;const sequence=this.sequence;this.setData({status:'submitting'});try{const next=await getApp().runtime.organizations.view(Object.assign({},this.context,{page:this.page+1}));if(sequence!==this.sequence)return;this.page+=1;this.setData({list:this.data.list.concat(next.list),hasMore:next.hasMore,status:'ready'})}catch(error){if(sequence===this.sequence)this.setData({status:'ready',formError:error.message})}},
 }}))
