// Compatibility exports. Task-owned definitions are authoritative.
export { fakeRegistryMeta } from './tasks/fake/definitions'
export { reactionRegistryMeta, reactionRegistryMetaV11 } from './tasks/reaction/definitions'
export { memoryRegistryMeta, memoryRegistryMetaV11 } from './tasks/memory/definitions'
export { stroopRegistryMeta, stroopRegistryMetaV11 } from './tasks/stroop/definitions'
export { gonogoRegistryMeta } from './tasks/gonogo/definitions'
export { cptRegistryMeta } from './tasks/cpt/definitions'
export { nbackRegistryMeta } from './tasks/nback/definitions'
export { corsiRegistryMeta } from './tasks/corsi/definitions'
export { sstRegistryMeta } from './tasks/sst/definitions'
export { taskswitchRegistryMeta } from './tasks/taskswitch/definitions'
export { patterncompareRegistryMeta } from './tasks/patterncompare/definitions'
export { flankerRegistryMeta } from './tasks/flanker/definitions'
export { cardsortRegistryMeta } from './tasks/cardsort/definitions'
export { digitbackwardRegistryMeta } from './tasks/digitbackward/definitions'
export { picturesequenceRegistryMeta } from './tasks/picturesequence/definitions'
export { pairedassociateRegistryMeta } from './tasks/pairedassociate/definitions'
export { matrixRegistryMeta } from './tasks/matrix/definitions'
export { mentalrotationRegistryMeta } from './tasks/mentalrotation/definitions'
export { towerRegistryMeta } from './tasks/tower/definitions'
export { trailmakingRegistryMeta } from './tasks/trailmaking/definitions'
export { reversallearningRegistryMeta } from './tasks/reversallearning/definitions'
export { bartRegistryMeta } from './tasks/bart/definitions'
export { wordlistRegistryMeta } from './tasks/wordlist/definitions'
export { lexicaldecisionRegistryMeta } from './tasks/lexicaldecision/definitions'
export { emotionrecognitionRegistryMeta } from './tasks/emotionrecognition/definitions'
