import type { ScaleInstrumentSourceV1 } from '../../../onboarding/types'

export const SCALE_INSTRUMENT_SOURCE = {
  schemaVersion: 1,
  identity: {
    instrumentKey: 'tipi_zh_cn',
    instrumentVersion: '1.0.0',
  },
  catalog: {
    schemaVersion: 1,
    catalogManifestVersion: 1,
    catalogStatus: 'REVIEWED',
    scientificMaturity: 'PILOT',
    identity: {
      canonicalName: 'Ten-Item Personality Inventory — Chinese Standard 7-point',
      abbreviation: 'TIPI',
      instrumentFamily: 'Ten-Item Personality Inventory',
    },
    construct: {
      primaryDomain: 'PERSONALITY',
      secondaryDomains: [],
      constructDefinition: '以十个项目极简测量大五人格的五个广义维度：外向性、宜人性、尽责性、情绪稳定性和经验开放性。',
      constructLevel: 'BROAD_DOMAIN',
      constructOverlapTags: [
        'big_five',
        'extraversion',
        'agreeableness',
        'conscientiousness',
        'emotional_stability',
        'openness',
        'self_report',
      ],
    },
    population: {
      populationNotes: '标准 TIPI 为一般自陈人格工具。本中文 package 使用 Gosling Lab 官方页面列出的 Jackson Lu 等中文译本，并恢复原版 1–7 作答格式；PILOT 阶段不声明中国常模、青少年常模或诊断阈值。',
      respondentTypes: ['SELF'],
      developmentalEvidence: 'PARTIAL',
    },
    administration: {
      itemCount: 10,
      estimatedMinutes: 2,
      administrationModes: ['DIGITAL_SELF_ADMINISTERED', 'DIGITAL_SUPERVISED', 'PAPER'],
      timeFrame: '一般人格自我描述；无特定回忆时段',
      requiredTraining: false,
      itemOrderLocked: true,
      responseFormatLocked: true,
      layoutConstraints: [
        '保持标准 TIPI 的 10 题顺序与 1–7 七点作答格式；不得替换为本项目历史使用的 5 点版本。',
        '每题为一对人格描述词；作答者应评价整对描述在多大程度上符合自己。',
      ],
    },
    intendedUse: {
      intendedUses: [
        {
          use: 'RESEARCH',
          evidenceStatus: 'SUPPORTED',
        },
        {
          use: 'INDIVIDUAL_REFLECTION',
          evidenceStatus: 'EVIDENCE_UNKNOWN',
          notes: '仅提供描述性维度分数和非诊断性解释，不启用常模或 cut-off。',
        },
      ],
      forbiddenUses: [
        'DIAGNOSIS',
        'HIGH_STAKES_SELECTION',
        'SCHOOL_RANKING',
        'TEACHER_ACCOUNTABILITY',
        'UNSUPPORTED_GROUP_COMPARISON',
      ],
    },
    evidence: [
      {
        evidenceId: 'tipi-gosling-2003',
        evidenceType: 'CONVERGENT_DISCRIMINANT',
        population: 'Original TIPI development and validation samples',
        locale: 'en',
        territory: 'US',
        studyDesign: 'Development and validation of an ultra-brief Big Five measure, including convergence with longer Big Five measures, test-retest evidence, external correlates, and self-observer convergence.',
        rating: 'SUFFICIENT',
        citation: 'Gosling SD, Rentfrow PJ, Swann WB Jr. (2003). A very brief measure of the Big-Five personality domains. Journal of Research in Personality, 37(6), 504–528.',
        doi: '10.1016/S0092-6566(03)00046-1',
        url: 'https://doi.org/10.1016/S0092-6566(03)00046-1',
        notes: 'TIPI was designed for situations where brevity is important; psychometric precision is lower than longer Big Five instruments.',
      },
      {
        evidenceId: 'tipi-lu-2020-zh',
        evidenceType: 'CONTENT_VALIDITY',
        population: 'Mainland Chinese research participants using the published Chinese translation',
        locale: 'zh-CN',
        territory: 'CN',
        studyDesign: 'Published Chinese translation of the TIPI reprinted in the article appendix and linked from the Gosling Lab TIPI translation resource.',
        rating: 'UNKNOWN',
        citation: 'Lu JG, Liu XL, Liao H, Wang L. (2020). Disentangling stereotypes from social reality: Astrological stereotypes and discrimination in China. Journal of Personality and Social Psychology.',
        doi: '10.1037/pspi0000237',
        url: 'https://doi.org/10.1037/pspi0000237',
        notes: 'This record establishes translation provenance, not a dedicated psychometric validation of the Chinese TIPI.',
      },
    ],
    referenceApplicability: [],
  },
  localization: {
    schemaVersion: 1,
    sourceLocale: 'en',
    targetLocale: 'zh-CN',
    localizationVersion: '1.0.0',
    translationSource: 'Chinese TIPI translation by Jackson G. Lu, Xin Lucy Liu, Hui Liao, and Lei Wang, linked from the Gosling Lab TIPI page and reprinted in Lu et al. (2020).',
    adaptationMethod: 'DIRECT_TRANSLATION',
    expertReviewStatus: 'PENDING',
    cognitiveDebriefStatus: 'NOT_ESTABLISHED',
    localEvidenceRefs: ['tipi-lu-2020-zh'],
    reviewStatus: 'PENDING',
    notes: '本 package 使用标准 7 点作答及原版题序；不沿用学习动机项目历史问卷中的 5 点 TIPI 改编。',
  },
  applicability: {
    schemaVersion: 1,
    policyVersion: 'tipi-zh-cn-standard-v1',
    respondentTypes: ['SELF'],
    requiredContextKeys: [],
  },
  disclosure: {
    schemaVersion: 1,
    policyVersion: 'tipi-zh-cn-standard-v1',
    audiences: {
      respondent: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: false,
        methods: true,
        educationalContent: false,
      },
      subject: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: false,
        methods: true,
        educationalContent: false,
      },
      teacher: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: false,
        methods: true,
        educationalContent: false,
      },
      researcher: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: true,
        methods: true,
        educationalContent: false,
      },
    },
    unknownAudience: 'DENY',
  },
  usageRequirements: {
    schemaVersion: 1,
    policyVersion: 'tipi-zh-cn-standard-v1',
    requiredRightsActions: ['electronicAdministration', 'scoring', 'display'],
    allowedCommercialNatures: ['NON_COMMERCIAL', 'COMMERCIAL'],
    notes: [
      '项目方确认该量表及中文版本已按作者公开授权/既有研究授权条件获得使用许可。',
      'Gosling Lab 对 TIPI 公开说明可自由使用；本 package 保留标准 7 点反应格式和 canonical scoring。',
    ],
  },
  executable: {
    releaseStatus: 'PUBLISHED',
    contentLocale: 'zh-CN',
    references: [],
    definition: {
      schemaVersion: 2,
      respondentType: 'participant_self_report',
      source: {
        title: 'Ten-Item Personality Inventory (TIPI) — Chinese translation',
        citation: 'Gosling SD, Rentfrow PJ, Swann WB Jr. (2003); Chinese translation by Lu JG, Liu XL, Liao H, Wang L (2020).',
        url: 'https://gosling.psy.utexas.edu/scales-weve-developed/ten-item-personality-measure-tipi/',
        publicationYear: 2003,
      },
      license: {
        status: 'authorized',
        redistribution: 'allowed',
        note: '项目方确认已授权使用；TIPI 作者网站亦明确允许使用。中文部署采用官方 TIPI 页面列出的中文译本。',
      },
      display: {
        randomizeItems: false,
      },
      responseSets: [
        {
          key: 'tipi_agreement_1_7_zh_cn',
          options: [
            { value: '1', label: '非常不同意', score: 1 },
            { value: '2', label: '比较不同意', score: 2 },
            { value: '3', label: '有点不同意', score: 3 },
            { value: '4', label: '既不同意也不反对', score: 4 },
            { value: '5', label: '有点同意', score: 5 },
            { value: '6', label: '比较同意', score: 6 },
            { value: '7', label: '非常同意', score: 7 },
          ],
        },
      ],
      items: [
        {
          itemCode: 'TIPI-01',
          content: '我是外向的、热情的。',
          type: 'single',
          required: true,
          sortOrder: 0,
          responseSetKey: 'tipi_agreement_1_7_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'TIPI-02',
          content: '我是挑剔的、爱争论的。',
          type: 'single',
          required: true,
          sortOrder: 1,
          responseSetKey: 'tipi_agreement_1_7_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'TIPI-03',
          content: '我是可靠的、自律的。',
          type: 'single',
          required: true,
          sortOrder: 2,
          responseSetKey: 'tipi_agreement_1_7_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'TIPI-04',
          content: '我是焦虑的、易心烦的。',
          type: 'single',
          required: true,
          sortOrder: 3,
          responseSetKey: 'tipi_agreement_1_7_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'TIPI-05',
          content: '我是愿意接触新事物的、思维复杂的。',
          type: 'single',
          required: true,
          sortOrder: 4,
          responseSetKey: 'tipi_agreement_1_7_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'TIPI-06',
          content: '我是内敛的、安静的。',
          type: 'single',
          required: true,
          sortOrder: 5,
          responseSetKey: 'tipi_agreement_1_7_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'TIPI-07',
          content: '我是有同情心的、温暖的。',
          type: 'single',
          required: true,
          sortOrder: 6,
          responseSetKey: 'tipi_agreement_1_7_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'TIPI-08',
          content: '我是缺乏条理的、粗心的。',
          type: 'single',
          required: true,
          sortOrder: 7,
          responseSetKey: 'tipi_agreement_1_7_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'TIPI-09',
          content: '我是冷静的、情绪稳定的。',
          type: 'single',
          required: true,
          sortOrder: 8,
          responseSetKey: 'tipi_agreement_1_7_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'TIPI-10',
          content: '我是循规蹈矩的、缺乏创造性的。',
          type: 'single',
          required: true,
          sortOrder: 9,
          responseSetKey: 'tipi_agreement_1_7_zh_cn',
          randomizeOptions: false,
        },
      ],
      scoring: {
        scoringVersion: '1.0.0',
        itemRules: [
          { itemCode: 'TIPI-01', transform: { type: 'identity' } },
          { itemCode: 'TIPI-02', transform: { type: 'reverse' } },
          { itemCode: 'TIPI-03', transform: { type: 'identity' } },
          { itemCode: 'TIPI-04', transform: { type: 'reverse' } },
          { itemCode: 'TIPI-05', transform: { type: 'identity' } },
          { itemCode: 'TIPI-06', transform: { type: 'reverse' } },
          { itemCode: 'TIPI-07', transform: { type: 'identity' } },
          { itemCode: 'TIPI-08', transform: { type: 'reverse' } },
          { itemCode: 'TIPI-09', transform: { type: 'identity' } },
          { itemCode: 'TIPI-10', transform: { type: 'reverse' } },
        ],
        defaultMissingPolicy: {
          type: 'complete_required',
        },
        scores: [
          {
            key: 'extraversion',
            type: 'dimension',
            label: '外向性',
            description: 'TIPI 外向性：项目 1 与反向项目 6 的均值。',
            direction: 'higher_is_more',
            canonical: true,
            displayPrecision: 1,
            missingPolicy: { type: 'complete_required' },
            source: {
              type: 'items',
              items: [
                { itemCode: 'TIPI-01', weight: 1 },
                { itemCode: 'TIPI-06', weight: 1 },
              ],
              aggregation: 'mean',
            },
          },
          {
            key: 'agreeableness',
            type: 'dimension',
            label: '宜人性',
            description: 'TIPI 宜人性：反向项目 2 与项目 7 的均值。',
            direction: 'higher_is_more',
            canonical: true,
            displayPrecision: 1,
            missingPolicy: { type: 'complete_required' },
            source: {
              type: 'items',
              items: [
                { itemCode: 'TIPI-02', weight: 1 },
                { itemCode: 'TIPI-07', weight: 1 },
              ],
              aggregation: 'mean',
            },
          },
          {
            key: 'conscientiousness',
            type: 'dimension',
            label: '尽责性',
            description: 'TIPI 尽责性：项目 3 与反向项目 8 的均值。',
            direction: 'higher_is_more',
            canonical: true,
            displayPrecision: 1,
            missingPolicy: { type: 'complete_required' },
            source: {
              type: 'items',
              items: [
                { itemCode: 'TIPI-03', weight: 1 },
                { itemCode: 'TIPI-08', weight: 1 },
              ],
              aggregation: 'mean',
            },
          },
          {
            key: 'emotional_stability',
            type: 'dimension',
            label: '情绪稳定性',
            description: 'TIPI 情绪稳定性：反向项目 4 与项目 9 的均值。',
            direction: 'higher_is_more',
            canonical: true,
            displayPrecision: 1,
            missingPolicy: { type: 'complete_required' },
            source: {
              type: 'items',
              items: [
                { itemCode: 'TIPI-04', weight: 1 },
                { itemCode: 'TIPI-09', weight: 1 },
              ],
              aggregation: 'mean',
            },
          },
          {
            key: 'openness_to_experience',
            type: 'dimension',
            label: '经验开放性',
            description: 'TIPI 经验开放性：项目 5 与反向项目 10 的均值。',
            direction: 'higher_is_more',
            canonical: true,
            displayPrecision: 1,
            missingPolicy: { type: 'complete_required' },
            source: {
              type: 'items',
              items: [
                { itemCode: 'TIPI-05', weight: 1 },
                { itemCode: 'TIPI-10', weight: 1 },
              ],
              aggregation: 'mean',
            },
          },
        ],
      },
      report: {
        reportVersion: '1.0.0',
        primaryScoreKeys: [
          'extraversion',
          'agreeableness',
          'conscientiousness',
          'emotional_stability',
          'openness_to_experience',
        ],
        scoreOrder: [
          'extraversion',
          'agreeableness',
          'conscientiousness',
          'emotional_stability',
          'openness_to_experience',
        ],
        interpretations: [
          {
            scoreKey: 'extraversion',
            headline: '外向性',
            source: { type: 'score_only' },
            summary: '外向性描述你在社交互动、表达和外显活力方面的一般倾向。分数较高通常表示更倾向于主动表达、热情并从互动中获得能量；分数较低通常表示更内敛、安静或偏好较低强度的社交表达。两端都不是优劣判断。',
            bands: [],
            guidance: [],
          },
          {
            scoreKey: 'agreeableness',
            headline: '宜人性',
            source: { type: 'score_only' },
            summary: '宜人性描述你在人际互动中表现出的体谅、温暖与合作倾向。分数较高通常表示更重视同理、合作和关系和谐；分数较低可能更多表现为直接、质疑或竞争性的互动方式，并不等同于道德品质高低。',
            bands: [],
            guidance: [],
          },
          {
            scoreKey: 'conscientiousness',
            headline: '尽责性',
            source: { type: 'score_only' },
            summary: '尽责性描述你在可靠、自律、计划和有条理行动方面的一般倾向。分数较高通常表示更偏向计划、坚持和按目标推进；分数较低可能更灵活、随性或较少依赖固定结构。TIPI 只能提供这一广义倾向的简要描述。',
            bands: [],
            guidance: [],
          },
          {
            scoreKey: 'emotional_stability',
            headline: '情绪稳定性',
            source: { type: 'score_only' },
            summary: '情绪稳定性描述你在压力或情绪波动情境中保持平静与稳定的一般倾向。分数较高通常表示更平静、情绪波动较少；分数较低表示更容易体验焦虑、心烦或情绪起伏。这一维度不是心理健康诊断。',
            bands: [],
            guidance: [],
          },
          {
            scoreKey: 'openness_to_experience',
            headline: '经验开放性',
            source: { type: 'score_only' },
            summary: '经验开放性描述你对新经验、新想法和复杂思考的接受倾向。分数较高通常表示更愿意接触新事物并探索不同观点；分数较低可能更偏好熟悉、传统、具体和稳定的方式。两种倾向在不同任务和环境中各有适用情境。',
            bands: [],
            guidance: [],
          },
        ],
        limitations: [
          'TIPI 每个人格维度仅由 2 个项目构成，目标是极简测量；其个体层面的精细度低于较长的大五人格工具。',
          'TIPI 不计算 10 题人格总分；五个维度应分别解释。',
          '本 PILOT package 未启用中国人群常模、百分位或 cut-off，因此不把分数划分为“高/低人格”或异常范围。',
          'TIPI 是自我报告工具，结果会受到作答情境、自我认识和反应方式影响，不等同于能力、智力、行为表现或精神健康状态。',
          '由于每个维度仅有两题且包含相反方向的项目，Cronbach α 不适合作为 TIPI 维度质量的主要判断依据。',
        ],
        disclaimer: '本报告用于研究和描述性自我了解，不用于心理诊断、精神健康判断、能力鉴定、人格定型或高风险选拔。请将五个维度理解为连续的人格倾向，而不是固定类型或优劣标签。',
      },
      referencePolicy: {
        type: 'none',
      },
    },
    goldenCases: [
      {
        name: 'all-midpoint',
        answers: [
          { itemCode: 'TIPI-01', responseValue: '4' },
          { itemCode: 'TIPI-02', responseValue: '4' },
          { itemCode: 'TIPI-03', responseValue: '4' },
          { itemCode: 'TIPI-04', responseValue: '4' },
          { itemCode: 'TIPI-05', responseValue: '4' },
          { itemCode: 'TIPI-06', responseValue: '4' },
          { itemCode: 'TIPI-07', responseValue: '4' },
          { itemCode: 'TIPI-08', responseValue: '4' },
          { itemCode: 'TIPI-09', responseValue: '4' },
          { itemCode: 'TIPI-10', responseValue: '4' },
        ],
        expected: {
          quality: 'interpretable',
          scores: {
            extraversion: 4,
            agreeableness: 4,
            conscientiousness: 4,
            emotional_stability: 4,
            openness_to_experience: 4,
          },
          totalScoreKeys: [
            'extraversion',
            'agreeableness',
            'conscientiousness',
            'emotional_stability',
            'openness_to_experience',
          ],
        },
      },
      {
        name: 'all-positive-poles-high',
        answers: [
          { itemCode: 'TIPI-01', responseValue: '7' },
          { itemCode: 'TIPI-02', responseValue: '1' },
          { itemCode: 'TIPI-03', responseValue: '7' },
          { itemCode: 'TIPI-04', responseValue: '1' },
          { itemCode: 'TIPI-05', responseValue: '7' },
          { itemCode: 'TIPI-06', responseValue: '1' },
          { itemCode: 'TIPI-07', responseValue: '7' },
          { itemCode: 'TIPI-08', responseValue: '1' },
          { itemCode: 'TIPI-09', responseValue: '7' },
          { itemCode: 'TIPI-10', responseValue: '1' },
        ],
        expected: {
          quality: 'interpretable',
          scores: {
            extraversion: 7,
            agreeableness: 7,
            conscientiousness: 7,
            emotional_stability: 7,
            openness_to_experience: 7,
          },
          totalScoreKeys: [
            'extraversion',
            'agreeableness',
            'conscientiousness',
            'emotional_stability',
            'openness_to_experience',
          ],
        },
      },
      {
        name: 'all-positive-poles-low',
        answers: [
          { itemCode: 'TIPI-01', responseValue: '1' },
          { itemCode: 'TIPI-02', responseValue: '7' },
          { itemCode: 'TIPI-03', responseValue: '1' },
          { itemCode: 'TIPI-04', responseValue: '7' },
          { itemCode: 'TIPI-05', responseValue: '1' },
          { itemCode: 'TIPI-06', responseValue: '7' },
          { itemCode: 'TIPI-07', responseValue: '1' },
          { itemCode: 'TIPI-08', responseValue: '7' },
          { itemCode: 'TIPI-09', responseValue: '1' },
          { itemCode: 'TIPI-10', responseValue: '7' },
        ],
        expected: {
          quality: 'interpretable',
          scores: {
            extraversion: 1,
            agreeableness: 1,
            conscientiousness: 1,
            emotional_stability: 1,
            openness_to_experience: 1,
          },
          totalScoreKeys: [
            'extraversion',
            'agreeableness',
            'conscientiousness',
            'emotional_stability',
            'openness_to_experience',
          ],
        },
      },
    ],
  },
} satisfies ScaleInstrumentSourceV1
