// Generated by generate-situational-instruments.mjs. Do not edit.
import instrument0 from '../instruments/sjt-anxiety-golden/1.0.0/instrument.json'
import publication0 from '../instruments/sjt-anxiety-golden/1.0.0/publication.json'
import scientific0 from '../instruments/sjt-anxiety-golden/1.0.0/scientific.json'
import instrument1 from '../instruments/sjt-assertiveness-golden/1.0.0/instrument.json'
import publication1 from '../instruments/sjt-assertiveness-golden/1.0.0/publication.json'
import scientific1 from '../instruments/sjt-assertiveness-golden/1.0.0/scientific.json'
import instrument2 from '../instruments/sjt-responsibility-golden/1.0.0/instrument.json'
import publication2 from '../instruments/sjt-responsibility-golden/1.0.0/publication.json'
import scientific2 from '../instruments/sjt-responsibility-golden/1.0.0/scientific.json'
export const GENERATED_SITUATIONAL_INSTRUMENT_SOURCES: readonly unknown[] = [
  { content: instrument0, publication: publication0, scientific: scientific0 },
  { content: instrument1, publication: publication1, scientific: scientific1 },
  { content: instrument2, publication: publication2, scientific: scientific2 },
]
