const { TASK_ROOT, BACK, FRONT } = require('./manifests.cjs')
/** A path category is not permission to trust generated bytes; manifest --check is mandatory. */
function classifyChangedPath(file, packages) {
  if(typeof file!=='string'||file.includes('\\')||file.startsWith('/')||file.split('/').some(p=>p==='..'||p==='.'))return 'SHARED_CORE'
  if([`${BACK}/execution.ts`,`${BACK}/catalog.ts`,`${BACK}/seeds.ts`,`${BACK}/presentation.ts`,`${BACK}/scientific.ts`,`${BACK}/identities.json`,`${FRONT}/runners.ts`].includes(file))return 'GENERATED'
  for(const p of packages){
    if(file.startsWith(`${TASK_ROOT}/${p.task}/`))return /\/(tests|fixtures)\//.test(file)?'TEST':'TASK_OWNED'
    // Only the declared runner's own directory, never tasks/shared or another task.
    if(file.startsWith(`server-version/frontend/src/modules/cognitive/tasks/${p.task}/`))return /\/__tests__\//.test(file)?'TEST':'TASK_OWNED'
  }
  return 'SHARED_CORE'
}
module.exports={classifyChangedPath}
