const fs = require('node:fs')
const path = require('node:path')
const ts = require('../../backend/node_modules/typescript')
const ROOT = path.resolve(__dirname, '../../..')
const TASK_ROOT = 'server-version/backend/src/modules/cognitive/tasks'
const BACK = 'server-version/backend/src/modules/cognitive/generated'
const FRONT = 'server-version/frontend/src/modules/cognitive/generated'
const HEADER = '// Generated by cognitive:manifest:generate. Do not edit.\n'
const fail = (code, file, detail) => { throw new Error(`${code}: ${file}: ${detail}`) }
const stable = (a, b) => a < b ? -1 : a > b ? 1 : 0
const symbol = value => typeof value === 'string' && /^[A-Za-z_$][\w$]*$/.test(value)
const identity = i => `${i.testType}/${i.engineVersion}/${i.scoringVersion}`
const engine = i => `${i.testType}/${i.engineVersion}`
function safeFile(root, relative) {
  if (typeof relative !== 'string' || path.isAbsolute(relative) || relative.includes('\\') || relative.split('/').some(p => p === '..' || p === '.')) fail('COG_PACKAGE_PATH_INVALID', String(relative), 'relative contained path required')
  const absolute = path.resolve(root, relative)
  if (!fs.existsSync(absolute) || !fs.statSync(absolute).isFile() || fs.realpathSync(absolute) !== path.resolve(fs.realpathSync(root), relative)) fail('COG_PACKAGE_FILE_MISSING', relative, 'regular non-symlink file required')
  return absolute
}
function reference(root, directory, ref) {
  if (!ref || !symbol(ref.export)) fail('COG_PACKAGE_EXPORT_INVALID', directory, 'named export required')
  const file = safeFile(root, `${directory}/${ref.file}`)
  const source = ts.createSourceFile(file, fs.readFileSync(file, 'utf8'), ts.ScriptTarget.Latest, true)
  const exported = source.statements.some(s => s.modifiers?.some(m => m.kind === ts.SyntaxKind.ExportKeyword) && (
    s.name?.text === ref.export || (ts.isVariableStatement(s) && s.declarationList.declarations.some(d => d.name.getText(source) === ref.export))))
  if (!exported) fail('COG_PACKAGE_EXPORT_INVALID', file, ref.export)
  return path.relative(root, file).split(path.sep).join('/')
}
function discover(root = ROOT, taskRoot = TASK_ROOT) {
  const dirs = fs.readdirSync(path.join(root, taskRoot), { withFileTypes: true }).filter(d => d.isDirectory()).map(d => d.name).sort(stable)
  const seenTasks = new Set(), seenIdentity = new Set(), seenRunner = new Set()
  const packages = dirs.map(dir => {
    const directory = `${taskRoot}/${dir}`, file = `${directory}/task-package.json`
    const d = JSON.parse(fs.readFileSync(safeFile(root, file), 'utf8'))
    if (d.schemaVersion !== 1 || typeof d.task !== 'string' || !/^[a-zA-Z0-9_-]+$/.test(d.task) || d.task !== dir || !Array.isArray(d.identities) || !d.identities.length || !Array.isArray(d.frontend) || !d.frontend.length) fail('COG_PACKAGE_SCHEMA_INVALID', file, 'invalid package v1')
    if (seenTasks.has(d.task)) fail('COG_TASK_DUPLICATE', file, d.task)
    seenTasks.add(d.task)
    for (const i of d.identities) {
      if (i.testType !== d.task || ![i.engineVersion, i.scoringVersion].every(v => typeof v === 'string' && /^[\w.-]+$/.test(v))) fail('COG_IDENTITY_INVALID', file, identity(i))
      if (seenIdentity.has(identity(i))) fail('COG_IDENTITY_DUPLICATE', file, identity(i))
      seenIdentity.add(identity(i))
    }
    const backendFile = reference(root, directory, d.backend)
    const runners = d.frontend.map(r => {
      if (r.testType !== d.task || !d.identities.some(i => engine(i) === engine(r))) fail('COG_RUNNER_ORPHAN', file, engine(r))
      if (seenRunner.has(engine(r))) fail('COG_RUNNER_DUPLICATE', file, engine(r))
      seenRunner.add(engine(r))
      return { ...r, resolvedFile: reference(root, path.posix.dirname(r.file), {file:path.posix.basename(r.file),export:r.export}) }
    })
    for (const i of d.identities) if (!runners.some(r => engine(r) === engine(i))) fail('COG_RUNNER_MISSING', file, engine(i))
    if (d.task !== 'fake' && !d.catalog) fail('COG_CATALOG_MISSING', file, d.task)
    if (!d.presentation) fail('COG_PRESENTATION_MISSING', file, d.task)
    if (d.order !== undefined && (!Number.isSafeInteger(d.order) || d.order < 0)) fail('COG_PACKAGE_SCHEMA_INVALID', file, 'invalid order')
    for (const i of d.identities) if (i.order !== undefined && (!Number.isSafeInteger(i.order) || i.order < 0)) fail('COG_PACKAGE_SCHEMA_INVALID', file, 'invalid identity order')
    if (!d.seeds || !Array.isArray(d.seeds.orders)) fail('COG_SEED_MISSING', file, d.task)
    return { ...d, directory, file, backendFile, runners, catalogFile: d.catalog ? reference(root,directory,d.catalog) : null, seedFile: reference(root,directory,d.seeds), presentationFile: d.presentation ? reference(root,directory,d.presentation) : null }
  })
  return packages.sort((a,b) => (a.order ?? Number.MAX_SAFE_INTEGER) - (b.order ?? Number.MAX_SAFE_INTEGER) || stable(a.task,b.task))
}
function importPath(output, input) {
  const p = path.posix.relative(path.posix.dirname(output), input).replace(/\.tsx?$/, '')
  return p.startsWith('.') ? p : `./${p}`
}
function projections(packages, back = BACK, front = FRONT) {
  const result = new Map()
  const projection = (output, refs, expression) => {
    const imports = refs.map((r,i) => `import { ${r.export} as task${i} } from '${importPath(output,r.file)}'`).join('\n')
    result.set(output, HEADER + imports + '\n' + expression + '\n')
  }
  const ordered = packages.flatMap((p,pi)=>p.identities.map((id,index)=>({id,pi,index}))).sort((a,b)=>(a.id.order??Number.MAX_SAFE_INTEGER)-(b.id.order??Number.MAX_SAFE_INTEGER)||stable(identity(a.id),identity(b.id)))
  projection(`${back}/execution.ts`, packages.map(p=>({file:p.backendFile,export:p.backend.export})), 'export const cognitiveExecutionEntries = [\n'+ordered.map(e=>`  task${e.pi}[${e.index}],`).join('\n')+'\n]')
  const runners = packages.flatMap(p=>p.runners)
  projection(`${front}/runners.ts`,runners.map(r=>({file:r.resolvedFile,export:r.export})),`export const cognitiveRunnerEntries = [${runners.map((_,i)=>`task${i}`).join(', ')}]`)
  const catalogs=packages.filter(p=>p.catalogFile)
  projection(`${back}/catalog.ts`,catalogs.map(p=>({file:p.catalogFile,export:p.catalog.export})),`export const cognitiveCatalog = {\n${catalogs.map((p,i)=>`  '${p.task}': task${i},`).join('\n')}\n}`)
  const seeds=packages.flatMap((p,pi)=>p.seeds.orders.map((order,index)=>({order,index,pi,task:p.task}))).sort((a,b)=>(a.order??Number.MAX_SAFE_INTEGER)-(b.order??Number.MAX_SAFE_INTEGER)||stable(a.task,b.task)||a.index-b.index)
  projection(`${back}/seeds.ts`,packages.map(p=>({file:p.seedFile,export:p.seeds.export})),`export const cognitiveSeeds = [\n${seeds.map(s=>`  task${s.pi}[${s.index}],`).join('\n')}\n]`)
  const presentations=packages.filter(p=>p.presentationFile)
  if(presentations.length) projection(`${back}/presentation.ts`,presentations.map(p=>({file:p.presentationFile,export:p.presentation.export})),`export const cognitivePresentations = [${presentations.map((_,i)=>`...task${i}`).join(', ')}]`)
  result.set(`${back}/identities.json`,JSON.stringify({schemaVersion:1,generatedBy:'cognitive:manifest:generate; do not edit',identities:ordered.map(e=>({testType:e.id.testType,engineVersion:e.id.engineVersion,scoringVersion:e.id.scoringVersion})),runners:runners.map(r=>({testType:r.testType,engineVersion:r.engineVersion}))},null,2)+'\n')
  return result
}
function generate({ root=ROOT,taskRoot=TASK_ROOT,back=BACK,front=FRONT,check=false }={}) {
  const packages=discover(root,taskRoot), outputs=projections(packages,back,front)
  for(const [file,content] of outputs){
    const target=path.join(root,file)
    if(check){if(!fs.existsSync(target)||fs.readFileSync(target,'utf8')!==content) fail('COG_MANIFEST_DRIFT',file,'regenerate task manifests')}
    else {fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,content)}
  }
  if (check) for (const dir of [back,front]) {
    for (const name of fs.readdirSync(path.join(root,dir))) {
      if (!outputs.has(`${dir}/${name}`)) fail('COG_MANIFEST_ORPHAN',`${dir}/${name}`,'unexpected generated file')
    }
  }
  return {packages,outputs}
}
module.exports={ROOT,TASK_ROOT,BACK,FRONT,discover,projections,generate,identity,engine,fail}
if(require.main===module){try{generate({check:process.argv.includes('--check')});console.log('Cognitive manifests: PASS')}catch(e){console.error(e.message);process.exitCode=1}}
