import React, {useEffect,useRef,useState} from 'react'
import api from '../api/client'
import {useAuth} from '../contexts/AuthContext'
type Policy={mode:'NONE'|'COMPLETION_ONLY'|'INDIVIDUAL_SUMMARY';metricKeys:string[];longitudinalMetricKeys:string[]}
type Snapshot={version:number;commandKey:string;allowedActions:string[];policy:Policy}
export const ParentToolDisclosureSettings:React.FC<{instrumentKey:string;instrumentVersion:string}>=({instrumentKey,instrumentVersion})=>{
 const {user}=useAuth(),allowed=user?.mobile?.capabilities.canManageParentToolDisclosure===true
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[mode,setMode]=useState<Policy['mode']>('NONE'),[metrics,setMetrics]=useState(''),[longitudinal,setLongitudinal]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[reload,setReload]=useState(0)
 const sequence=useRef(0),inFlight=useRef(false),sealed=useRef<Policy|null>(null)
 const path='/parent-tool-policies/SCALE/'+encodeURIComponent(instrumentKey)+'/'+encodeURIComponent(instrumentVersion)
 useEffect(()=>{const n=++sequence.current;setSnapshot(null);sealed.current=null;if(allowed)void api.get<Snapshot>(path).then(r=>{if(n!==sequence.current)return;setSnapshot(r.data);setMode(r.data.policy.mode);setMetrics(r.data.policy.metricKeys.join('，'));setLongitudinal(r.data.policy.longitudinalMetricKeys.join('，'))}).catch(e=>{if(n===sequence.current)setError(e.message)});return()=>{sequence.current+=1}},[path,allowed,reload])
 if(!allowed)return null
 const save=async()=>{if(!snapshot||inFlight.current||!confirm)return;inFlight.current=true;setBusy(true);setError('');const n=sequence.current;const keys=(value:string)=>value.split(/[,，\s]+/).filter(Boolean);if(!sealed.current)sealed.current={mode,metricKeys:mode==='INDIVIDUAL_SUMMARY'?keys(metrics):[],longitudinalMetricKeys:mode==='INDIVIDUAL_SUMMARY'?keys(longitudinal):[]};try{await api.put(path,{policy:sealed.current,expectedVersion:snapshot.version,commandKey:snapshot.commandKey});const r=await api.get<Snapshot>(path);if(n!==sequence.current)return;setSnapshot(r.data);sealed.current=null;setConfirm(false)}catch(e:any){if(n===sequence.current){setError(e.message);setConfirm(false);if(e.status)sealed.current=null;if(e.status===409)setSnapshot(null)}}finally{inFlight.current=false;if(n===sequence.current)setBusy(false)}}
 return <section className="rounded-xl border border-gray-200 bg-white p-5 mt-5"><h2 className="font-semibold">家长披露设置</h2><p className="text-sm text-gray-600 mt-2">超级管理员设置该工具版本的披露上限；学生对每份报告的同意与独立授权继续生效。原始作答、单题信息和研究导出不开放。</p>{error&&<p role="alert" className="text-red-700 mt-2">{error}</p>}{!snapshot&&<button type="button" className="btn-secondary mt-3" onClick={()=>setReload(v=>v+1)}>刷新披露设置</button>}{snapshot&&<><label className="block mt-3">家长可见范围<select className="block border rounded p-2" value={mode} disabled={busy||Boolean(sealed.current)} onChange={e=>setMode(e.target.value as Policy['mode'])}><option value="NONE">不披露</option><option value="COMPLETION_ONLY">仅完成情况</option><option value="INDIVIDUAL_SUMMARY">获准的个人摘要</option></select></label>{mode==='INDIVIDUAL_SUMMARY'&&<><label className="block mt-3">允许披露的指标编号（来自正式报告方案，逗号分隔）<input className="block border rounded p-2 w-full" value={metrics} disabled={busy||Boolean(sealed.current)} onChange={e=>setMetrics(e.target.value)}/></label><label className="block mt-3">允许纵向展示的指标编号<input className="block border rounded p-2 w-full" value={longitudinal} disabled={busy||Boolean(sealed.current)} onChange={e=>setLongitudinal(e.target.value)}/></label></>}{confirm?<div className="mt-3"><p>收紧设置会立即限制后续访问；放宽不会扩充已同意报告，也不会发布草稿或教师报告。</p><button type="button" className="btn-primary mt-2" disabled={busy} onClick={()=>void save()}>确认保存</button><button type="button" className="btn-secondary ml-2" disabled={busy} onClick={()=>setConfirm(false)}>取消</button></div>:<button type="button" className="btn-primary mt-3" disabled={busy||!snapshot.allowedActions.includes('UPDATE')} onClick={()=>setConfirm(true)}>核对并保存</button>}</>}</section>
}
