const { workspacePage } = require('../../app/pages/index')
Page(workspacePage({
 setup(options){this.domain=options.domain;this.id=options.id||undefined;this.action=options.action;this.sourceCourseId=options.courseId;this.values={};this.sealed=null;this.sealedImages=null;this.retryAt=0;this.visible=true;this.picking=false},
 keepOnShow(){return Boolean(this.form)||this.picking},
 reset(){this.values={};this.form=null;this.sealed=null;this.visible=false;this.images=[];this.sealedImages=null;this.retryAt=0;this.picking=false},
 async fetch(runtime){const sequence=this.sequence,form=await runtime.operations.prepare(this.domain,this.id,this.action,this.sourceCourseId);if(sequence!==this.sequence||!this.visible)return {};this.form=form;this.values={};this.images=this.form.images||[];this.sealed=null;return {images:this.images,canUploadImages:this.form.canUploadImages,title:this.form.title,fields:this.form.fields,confirmation:this.form.confirmation,confirmationOpen:false,sealed:false,conflict:false,formError:'',result:null,booleanChoices:[{value:true,label:'允许'},{value:false,label:'不允许'}]}},
 methods:{
 change(event){if(!this.form||!this.visible||this.data.result||this.data.status==='submitting'||this.sealed)return;const key=event.currentTarget.dataset.key;if(!this.form.fields.some(f=>f.key===key))return;this.values[key]=event.detail.value;this.setData({fields:this.form.fields.map(f=>Object.assign({},f,{value:this.values[f.key]===undefined?f.value:this.values[f.key]}))})},
 async choose(event){const key=event.currentTarget.dataset.key;const form=this.form,sequence=this.sequence,f=form&&form.fields.find(f=>f.key===key);if(!f||!f.selector||this.data.status==='submitting'||this.sealed)return;wx.navigateTo({url:'/pages/select/index?domain='+encodeURIComponent(f.selector)+'&parent='+encodeURIComponent(f.selectorParent||'')+'&multiple='+(f.multiple?'1':'0'),events:{selected:selection=>{if(!this.visible||sequence!==this.sequence||this.form!==form||this.sealed||this.data.result)return;this.values[key]=selection.value;this.setData({fields:this.data.fields.map(item=>item.key===key?Object.assign({},item,{value:selection.value,selectionLabel:selection.label}):item)})}}})},
 confirm(){if(this.data.status==='submitting'||this.data.conflict||this.data.result||!this.form)return;if(Date.now()<this.retryAt){this.setData({formError:'请等待 '+Math.ceil((this.retryAt-Date.now())/1000)+' 秒后重试原提交'});return;}this.setData({confirmationOpen:true,formError:''})},
 cancel(){if(this.data.status!=='submitting')this.setData({confirmationOpen:false})},
 async submit(){if(this.data.status==='submitting'||!this.data.confirmationOpen||this.data.conflict||this.data.result||!this.form||Date.now()<this.retryAt)return;const sequence=this.sequence;this.setData({status:'submitting',formError:''});
  // Once a submission is sent, retries retain its exact payload and key. An
  // edit requires a fresh server revision obtained by reopening the form.
  if(!this.sealed){this.sealed=JSON.parse(JSON.stringify(this.values));this.sealedImages=JSON.parse(JSON.stringify(this.images))}
  try{const result=await getApp().runtime.operations.execute(this.domain,this.id,this.action,this.form,this.sealed,{images:this.sealedImages});if(sequence!==this.sequence)return;this.setData({status:'ready',fields:[],confirmationOpen:false,result:{message:'服务器已确认操作完成',handoffFile:result&&result.handoffFile||'',code:result&&result.code||'',publicLink:result&&result.token?getApp().runtime.operations.publicLink(result.token):''}});this.values={};this.sealed=null;this.sealedImages=null;this.images=[];this.setData({images:[],sealed:false})}
  catch(error){if(sequence!==this.sequence)return;const conflict=error.status===409;if(error.retryAfterMs)this.retryAt=Date.now()+error.retryAfterMs;if(error.kind==='invalidRequest'||(error.status>=400&&error.status<500&&error.status!==429)){this.sealed=null;this.sealedImages=null}this.setData({status:'ready',confirmationOpen:false,formError:error.message+(conflict?'。请返回刷新后重新操作。':error.status===429?'。请等待 '+Math.ceil((error.retryAfterMs||0)/1000)+' 秒后重试原提交。':'。若需重试，请保持原提交内容。'),conflict});if(!['submit'].includes(this.action)){this.sealed=null;if(error.kind==='network'||error.status>=500)this.setData({conflict:true,formError:error.message+'。服务器确认结果未知，请返回列表核对后再操作。'})}this.setData({sealed:Boolean(this.sealed)})}
 },
 async upload(){if(!this.data.canUploadImages||this.sealed||this.data.status==='submitting'||this.picking||this.images.length>=9)return;const sequence=this.sequence;this.picking=true;try{const files=await getApp().runtime.media.chooseImages(9-this.images.length,()=>sequence===this.sequence&&this.visible&&!this.sealed);if(sequence!==this.sequence||!this.visible||this.sealed)return;this.setData({status:'submitting',formError:''});for(const file of files){if(this.images.length>=9)break;const asset=await getApp().runtime.operations.uploadImage(this.domain,this.id,this.action,file.tempFilePath);if(sequence!==this.sequence||!this.visible)return;this.images.push(asset);this.setData({images:this.images})}this.setData({status:'ready'})}catch(e){if(sequence===this.sequence&&e.kind!=='cancelled')this.setData({status:'ready',formError:e.message||'未选择图片'})}finally{this.picking=false}},
 removeImage(e){if(this.sealed||this.data.status==='submitting')return;this.images=this.images.filter((_,i)=>i!==Number(e.currentTarget.dataset.index));this.setData({images:this.images})},
 copyLink(){if(this.data.result&&this.data.result.publicLink)wx.setClipboardData({data:this.data.result.publicLink})},
 back(){wx.navigateBack({delta:1})},
 }}))
