import type { ScaleInstrumentSourceV1 } from '../../../onboarding/types'

export const SCALE_INSTRUMENT_SOURCE = {
  schemaVersion: 1,
  identity: {
    instrumentKey: 'cross_domain_talent_beliefs_zh_cn',
    instrumentVersion: '1.0.0',
  },
  catalog: {
    schemaVersion: 1,
    catalogManifestVersion: 1,
    catalogStatus: 'REVIEWED',
    scientificMaturity: 'PILOT',
    identity: {
      canonicalName: 'Cross-Domain Talent Beliefs — Project Chinese 4-item',
      abbreviation: 'CDTB-4',
      instrumentFamily: 'Cross-Domain Talent Beliefs',
    },
    construct: {
      primaryDomain: 'MOTIVATION',
      secondaryDomains: [],
      constructDefinition: '描述个体认为人的天赋水平会在不同学科之间存在稳定高低差异的信念强度。',
      constructLevel: 'SPECIFIC_CONSTRUCT',
      constructOverlapTags: [
        'talent_beliefs',
        'cross_domain',
        'subject_specific_ability',
        'implicit_beliefs',
        'self_report',
      ],
    },
    population: {
      populationNotes: '本工具为学习动机研究自编的 4 题中文指标，用于中学生跨学科天赋差异信念研究。Dweck 心态理论仅作为概念背景；不宣称这是某个既有标准量表的翻译。',
      respondentTypes: ['SELF'],
      developmentalEvidence: 'PARTIAL',
    },
    administration: {
      itemCount: 4,
      estimatedMinutes: 2,
      administrationModes: ['DIGITAL_SELF_ADMINISTERED', 'DIGITAL_SUPERVISED', 'PAPER'],
      timeFrame: '一般信念；无特定回忆时段',
      requiredTraining: false,
      itemOrderLocked: true,
      responseFormatLocked: true,
      layoutConstraints: [
        '保持项目实际使用的 4 个中文题目和 1–6 六点同意度作答格式。',
        '四题均正向计分；不根据该分数推断真实学科天赋差异。',
      ],
    },
    intendedUse: {
      intendedUses: [
        {
          use: 'RESEARCH',
          evidenceStatus: 'SUPPORTED',
        },
        {
          use: 'INDIVIDUAL_REFLECTION',
          evidenceStatus: 'EVIDENCE_UNKNOWN',
          notes: '仅描述跨学科天赋差异信念，不解释为真实能力结构。',
        },
      ],
      forbiddenUses: [
        'DIAGNOSIS',
        'HIGH_STAKES_SELECTION',
        'SCHOOL_RANKING',
        'TEACHER_ACCOUNTABILITY',
        'UNSUPPORTED_GROUP_COMPARISON',
      ],
    },
    evidence: [
      {
        evidenceId: 'cross-domain-talent-beliefs-dweck-background',
        evidenceType: 'CONTENT_VALIDITY',
        population: 'General implicit-theory research samples',
        locale: 'en',
        territory: 'US',
        studyDesign: 'Foundational implicit-theories framework used only as conceptual background for the project-authored items.',
        rating: 'UNKNOWN',
        citation: 'Dweck CS, Chiu C-y, Hong Y-y. (1995). Implicit theories and their role in judgments and reactions. Psychological Inquiry, 6(4), 267–285.',
        doi: '10.1207/s15327965pli0604_1',
        url: 'https://doi.org/10.1207/s15327965pli0604_1',
        notes: 'Conceptual background only; the four project items are not presented as a published Dweck scale.',
      },
      {
        evidenceId: 'cross-domain-talent-beliefs-project-t1-alpha',
        evidenceType: 'INTERNAL_CONSISTENCY',
        population: 'T1 middle-school learning-motivation study sample',
        locale: 'zh-CN',
        territory: 'CN',
        studyDesign: 'Internal consistency recomputed from the project Final canonical item data.',
        rating: 'SUFFICIENT',
        citation: 'Learning Motivation Project Canonical Data Package — Final scoring audit (internal project evidence).',
        notes: 'Four-item Cross-Domain Talent Beliefs alpha = 0.852 in the Final T1 general sample.',
      },
    ],
    referenceApplicability: [],
  },
  localization: {
    schemaVersion: 1,
    sourceLocale: 'zh-CN',
    targetLocale: 'zh-CN',
    localizationVersion: '1.0.0',
    translationSource: 'Project-authored Chinese wording used in the T1 learning-motivation questionnaire.',
    adaptationMethod: 'ORIGINAL_SOURCE',
    expertReviewStatus: 'COMPLETED',
    cognitiveDebriefStatus: 'NOT_ESTABLISHED',
    localEvidenceRefs: ['cross-domain-talent-beliefs-project-t1-alpha'],
    reviewStatus: 'PENDING',
    notes: '该 executable 冻结研究实际使用的中文题干与六点作答格式。',
  },
  applicability: {
    schemaVersion: 1,
    policyVersion: 'cross-domain-talent-beliefs-zh-cn-v1',
    respondentTypes: ['SELF'],
    requiredContextKeys: [],
  },
  disclosure: {
    schemaVersion: 1,
    policyVersion: 'cross-domain-talent-beliefs-zh-cn-v1',
    audiences: {
      respondent: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: false,
        methods: true,
        educationalContent: false,
      },
      subject: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: false,
        methods: true,
        educationalContent: false,
      },
      teacher: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: false,
        methods: true,
        educationalContent: false,
      },
      researcher: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: true,
        methods: true,
        educationalContent: false,
      },
    },
    unknownAudience: 'DENY',
  },
  usageRequirements: {
    schemaVersion: 1,
    policyVersion: 'cross-domain-talent-beliefs-zh-cn-v1',
    requiredRightsActions: ['electronicAdministration', 'scoring', 'display'],
    allowedCommercialNatures: ['NON_COMMERCIAL', 'COMMERCIAL'],
    notes: [
      '项目方确认本项目自编版本可继续用于 Huisurvey 电子施测、计分与展示。',
    ],
  },
  executable: {
    releaseStatus: 'PUBLISHED',
    contentLocale: 'zh-CN',
    references: [],
    definition: {
      schemaVersion: 2,
      respondentType: 'participant_self_report',
      source: {
        title: 'Cross-Domain Talent Beliefs — project-developed measure',
        citation: 'Learning Motivation Project self-developed 4-item measure; Dweck et al. (1995) used as conceptual background only.',
        url: 'https://doi.org/10.1207/s15327965pli0604_1',
        publicationYear: 2018,
      },
      license: {
        status: 'self_authored',
        redistribution: 'allowed',
        note: '项目自编中文内容；项目方确认可在 Huisurvey 中继续使用与分发。',
      },
      display: {
        randomizeItems: false,
      },
      responseSets: [
        {
          key: 'agreement_1_6_t1_zh_cn',
          options: [
            { value: '1', label: '完全不同意', score: 1 },
            { value: '2', label: '比较不同意', score: 2 },
            { value: '3', label: '有点不同意', score: 3 },
            { value: '4', label: '有点同意', score: 4 },
            { value: '5', label: '比较同意', score: 5 },
            { value: '6', label: '完全同意', score: 6 },
          ],
        },
      ],
      items: [
        {
          itemCode: 'CDTB-01',
          content: '在不同的学科上，我的天赋水平是不一致的。',
          type: 'single',
          required: true,
          sortOrder: 0,
          responseSetKey: 'agreement_1_6_t1_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'CDTB-02',
          content: '我不同学科的天赋水平，是有高低差异的。',
          type: 'single',
          required: true,
          sortOrder: 1,
          responseSetKey: 'agreement_1_6_t1_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'CDTB-03',
          content: '有的学科天赋高，有的学科天赋低，每个人都是如此。',
          type: 'single',
          required: true,
          sortOrder: 2,
          responseSetKey: 'agreement_1_6_t1_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'CDTB-04',
          content: '每个人的天赋水平，在不同学科上都会有高有低。',
          type: 'single',
          required: true,
          sortOrder: 3,
          responseSetKey: 'agreement_1_6_t1_zh_cn',
          randomizeOptions: false,
        },
      ],
      scoring: {
        scoringVersion: '1.0.0',
        itemRules: [
          { itemCode: 'CDTB-01', transform: { type: 'identity' } },
          { itemCode: 'CDTB-02', transform: { type: 'identity' } },
          { itemCode: 'CDTB-03', transform: { type: 'identity' } },
          { itemCode: 'CDTB-04', transform: { type: 'identity' } },
        ],
        defaultMissingPolicy: {
          type: 'complete_required',
        },
        scores: [
          {
            key: 'cross_domain_talent_beliefs',
            type: 'total',
            label: '跨学科天赋差异信念',
            description: '四题平均分；分数越高表示越认同人的天赋会在不同学科之间存在高低差异。',
            direction: 'higher_is_more',
            canonical: true,
            displayPrecision: 2,
            missingPolicy: {
              type: 'prorate_if_min_answered',
              minimumAnswered: 3,
            },
            source: {
              type: 'items',
              items: [
                { itemCode: 'CDTB-01', weight: 1 },
                { itemCode: 'CDTB-02', weight: 1 },
                { itemCode: 'CDTB-03', weight: 1 },
                { itemCode: 'CDTB-04', weight: 1 },
              ],
              aggregation: 'mean',
            },
          },
        ],
      },
      report: {
        reportVersion: '1.0.0',
        primaryScoreKeys: ['cross_domain_talent_beliefs'],
        scoreOrder: ['cross_domain_talent_beliefs'],
        interpretations: [
          {
            scoreKey: 'cross_domain_talent_beliefs',
            headline: '跨学科天赋差异信念',
            source: { type: 'score_only' },
            summary: '该分数描述你在多大程度上认同“人的天赋会在不同学科之间有稳定高低差异”这一观点。分数较高表示更倾向认为学科间天赋差异明显；分数较低表示较少认同这种差异观。它测量的是一种信念，不是对你本人或他人真实学科能力结构的判断。',
            bands: [],
            guidance: [],
          },
        ],
        limitations: [
          '这是项目自编 4 题 PILOT 指标，不是公开标准量表的直接翻译。',
          '本 package 不提供常模、百分位、cut-off 或任何“天赋类型”分类。',
          '分数只反映对学科间天赋差异的信念，不能用于推断某个学生真实在哪些学科更有天赋。',
          '该构念与一般固定心态有关但并不相同，两者应分别解释。',
        ],
        disclaimer: '本报告仅用于研究和描述性自我了解，不用于天赋鉴定、选科分流、能力预测、诊断或高风险教育决策。',
      },
      referencePolicy: {
        type: 'none',
      },
    },
    goldenCases: [
      {
        name: 'all-lowest',
        answers: [
          { itemCode: 'CDTB-01', responseValue: '1' },
          { itemCode: 'CDTB-02', responseValue: '1' },
          { itemCode: 'CDTB-03', responseValue: '1' },
          { itemCode: 'CDTB-04', responseValue: '1' },
        ],
        expected: {
          quality: 'interpretable',
          scores: {
            cross_domain_talent_beliefs: 1,
          },
          totalScoreKeys: ['cross_domain_talent_beliefs'],
        },
      },
      {
        name: 'all-highest',
        answers: [
          { itemCode: 'CDTB-01', responseValue: '6' },
          { itemCode: 'CDTB-02', responseValue: '6' },
          { itemCode: 'CDTB-03', responseValue: '6' },
          { itemCode: 'CDTB-04', responseValue: '6' },
        ],
        expected: {
          quality: 'interpretable',
          scores: {
            cross_domain_talent_beliefs: 6,
          },
          totalScoreKeys: ['cross_domain_talent_beliefs'],
        },
      },
      {
        name: 'three-of-four',
        answers: [
          { itemCode: 'CDTB-01', responseValue: '2' },
          { itemCode: 'CDTB-02', responseValue: '4' },
          { itemCode: 'CDTB-03', responseValue: '6' },
        ],
        expected: {
          quality: 'limited',
          scores: {
            cross_domain_talent_beliefs: 4,
          },
          totalScoreKeys: ['cross_domain_talent_beliefs'],
        },
      },
    ],
  },
} satisfies ScaleInstrumentSourceV1
