const { workspacePage } = require('../../app/pages/index')
const { ApiError } = require('../../core/errors/index')
Page(workspacePage({
 setup(o){this.handle={family:o.family,rootId:o.rootId,resourceId:o.resourceId,webTarget:o.webTarget};this.index=0;this.unit=null;this.active=true},
 reset(){this.unit=null;this.active=false},
 async fetch(runtime){this.active=true;try{const sequence=this.sequence,unit=await runtime.assessments.resume(this.handle);if(sequence!==this.sequence||!this.active)return {};this.unit=unit;return this.project()}catch(e){if(['unsupportedRenderer','definitionMismatch','draftConflict'].includes(e.kind)&&this.handle.webTarget)return {title:'继续测评',runtimeState:'web',notice:e.message,canWeb:true};throw e}},
 methods:{
 project(){const unit=this.unit,draft=unit.draft,values=draft?{...draft.values,...unit.pendingValues}:{};this.index=Math.min(this.index,Math.max(0,unit.items.length-1));return {title:unit.title,description:unit.instruction,runtimeState:unit.state,item:getApp().runtime.assessments.renderers.view(unit.items,values,this.index,!draft||draft.state==='sealed'||unit.state==='conflict'),completed:unit.rootStatus==='COMPLETED',hasUnit:Boolean(unit.meta),canSubmit:Boolean(unit.meta&&unit.draft)&&!['conflict','draftConflict'].includes(unit.state),canFinish:unit.needsComplete,canRestart:unit.state==='conflict'||unit.state==='draftConflict',canDiscard:unit.state==='draftConflict'||Boolean(unit.recovery&&unit.currentMeta&&unit.currentMeta.attemptEpoch!==unit.meta.attemptEpoch),canReport:unit.rootStatus==='COMPLETED',canWeb:Boolean(this.handle.webTarget),saveError:'',submitError:'',saving:false,notice:unit.state==='draftConflict'?'草稿身份与服务器不同，请在正式网页核对并重启后继续。':unit.recovery?'服务器已进入其他单元，本机上一份提交仍待确认。请重试原提交以取得回执。':draft&&draft.state==='sealed'?'本机已封存答案，重试将发送同一份最终提交。':unit.rootStatus==='COMPLETED'?'服务器已确认测评完成':'答案保存到本机；完成当前单元后统一提交。'}},
 onHide(){this.sequence+=1;this.active=false;this.unit=null;this.setData({item:null,hasUnit:false,canSubmit:false,canReport:false,saveError:'',submitError:''})},
 async change(e){if(!this.unit||this.data.status==='submitting'||(!this.unit.draft||this.unit.draft.state==='sealed'))return;const sequence=this.sequence,unit=this.unit,key=this.data.item.key;this.setData({saving:true,saveError:''});try{await getApp().runtime.assessments.change(unit,key,e.detail.value);if(this.active&&sequence===this.sequence&&this.unit===unit)this.setData(this.project())}catch(error){if(this.active&&sequence===this.sequence)this.setData({saving:false,saveError:error.message,canSubmit:false})}},
 async save(){if(!this.unit||this.data.status==='submitting')return;const sequence=this.sequence;try{await getApp().runtime.assessments.savePending(this.unit);if(this.active&&sequence===this.sequence)this.setData(this.project())}catch(e){if(this.active&&sequence===this.sequence)this.setData({saveError:e.message,canSubmit:false})}},
 previous(){if(this.data.status!=='submitting'&&this.index>0){this.index--;this.setData(this.project())}},
 next(){if(this.unit&&this.data.status!=='submitting'&&this.index<this.unit.items.length-1){this.index++;this.setData(this.project())}},
 async submit(){if(!this.unit||!this.data.canSubmit||this.data.status==='submitting')return;const sequence=this.sequence,unit=this.unit;this.setData({status:'submitting',submitError:''});try{await getApp().runtime.assessments.submit(unit);if(!this.active||sequence!==this.sequence)return;this.index=0;await this.load()}catch(error){if(!this.active||sequence!==this.sequence)return;this.setData({...this.project(),status:'ready',submitError:error.message+(error.retryAfterMs?'。请等待 '+Math.ceil(error.retryAfterMs/1000)+' 秒后重试。':''),saving:false,canSubmit:unit.state!=='conflict'&&error.kind!=='storageUnavailable',canRestart:unit.state==='conflict',saveError:error.kind==='storageUnavailable'&&unit.draft?.state==='draft'?error.message:''})}},
 async finish(){if(!this.unit||this.data.status==='submitting')return;const sequence=this.sequence;this.setData({status:'submitting'});try{await getApp().runtime.assessments.finish(this.unit);if(this.active&&sequence===this.sequence)await this.load()}catch(e){if(this.active&&sequence===this.sequence)this.setData({status:'ready',submitError:e.message})}},
 async discard(){if(!this.unit||!this.data.canDiscard||this.data.status==='submitting')return;const sequence=this.sequence;const answer=await new Promise(resolve=>wx.showModal({title:'清理旧草稿',content:'服务器已经进入其他轮次或定义。清理本机旧草稿后重新读取当前测评；此操作不会提交旧答案。',success:resolve,fail:()=>resolve({confirm:false})}));if(!answer.confirm||sequence!==this.sequence||!this.active)return;try{await getApp().runtime.assessments.discardStale(this.unit);if(sequence===this.sequence&&this.active)await this.load()}catch(e){if(sequence===this.sequence&&this.active)this.setData({submitError:e.message})}},
 async restart(){if(!this.unit||this.data.status==='submitting')return;const sequence=this.sequence;const answer=await new Promise(resolve=>wx.showModal({title:'重启测评',content:'重启会改变测评轮次，旧草稿不能提交。请确认是否重新作答。',success:resolve,fail:()=>resolve({confirm:false})}));if(!answer.confirm||!this.active||sequence!==this.sequence)return;this.setData({status:'submitting'});try{const result=await getApp().runtime.assessments.restart(this.unit);if(this.active&&sequence===this.sequence){this.handle={...this.handle,...result.handle};this.index=0;await this.load()}}catch(e){if(this.active&&sequence===this.sequence)this.setData({status:'ready',submitError:e.message})}},
 report(){if(this.unit&&this.data.canReport)wx.navigateTo({url:'/pages/report/index?family='+encodeURIComponent(this.unit.family)+'&id='+encodeURIComponent(this.unit.rootId)+(this.handle.webTarget?'&webTarget='+encodeURIComponent(require('../../domains/assessments/reports').reportTargetForAttempt(this.unit.family,this.unit.rootId)||this.handle.webTarget):'')})},
 web(){if(this.handle.webTarget)wx.navigateTo({url:'/pages/web-runtime/index?path='+encodeURIComponent(this.handle.webTarget)})},
 }}))
