import type { ScaleInstrumentSourceV1 } from '../../../onboarding/types'

export const SCALE_INSTRUMENT_SOURCE = {
  schemaVersion: 1,
  identity: {
    instrumentKey: 'grit_s_zh_cn',
    instrumentVersion: '1.0.0',
  },
  catalog: {
    schemaVersion: 1,
    catalogManifestVersion: 1,
    catalogStatus: 'REVIEWED',
    scientificMaturity: 'PILOT',
    identity: {
      canonicalName: 'Short Grit Scale (Grit-S) — Chinese Standard 5-point',
      abbreviation: 'Grit-S',
      instrumentFamily: 'Short Grit Scale',
    },
    construct: {
      primaryDomain: 'SELF_REGULATION',
      secondaryDomains: ['MOTIVATION'],
      constructDefinition: '以兴趣一致性与努力坚持两个方面描述个体在长期目标上的持续投入倾向。',
      constructLevel: 'SPECIFIC_CONSTRUCT',
      constructOverlapTags: [
        'grit',
        'consistency_of_interest',
        'perseverance_of_effort',
        'long_term_goals',
        'self_report',
      ],
    },
    population: {
      populationNotes: 'Grit-S 为一般自陈工具，原始研究覆盖青少年、学生与成人样本。本 package 使用标准 8 题结构与标准 5 点“像不像我”作答格式，不沿用本项目历史问卷的同意度锚点。',
      respondentTypes: ['SELF'],
      developmentalEvidence: 'ESTABLISHED',
    },
    administration: {
      itemCount: 8,
      estimatedMinutes: 3,
      administrationModes: ['DIGITAL_SELF_ADMINISTERED', 'DIGITAL_SUPERVISED', 'PAPER'],
      timeFrame: '一般/长期行为倾向；无特定回忆时段',
      requiredTraining: false,
      itemOrderLocked: true,
      responseFormatLocked: true,
      layoutConstraints: [
        '保持标准 Grit-S 的 8 题顺序与 5 点“像不像我”作答语义。',
        '兴趣一致性项目 1、3、5、6 反向计分；努力坚持项目 2、4、7、8 正向计分。',
      ],
    },
    intendedUse: {
      intendedUses: [
        {
          use: 'RESEARCH',
          evidenceStatus: 'SUPPORTED',
        },
        {
          use: 'INDIVIDUAL_REFLECTION',
          evidenceStatus: 'EVIDENCE_UNKNOWN',
          notes: '仅用于描述长期目标坚持相关倾向，不提供规范性等级。',
        },
      ],
      forbiddenUses: [
        'DIAGNOSIS',
        'HIGH_STAKES_SELECTION',
        'SCHOOL_RANKING',
        'TEACHER_ACCOUNTABILITY',
        'UNSUPPORTED_GROUP_COMPARISON',
      ],
    },
    evidence: [
      {
        evidenceId: 'grit-s-duckworth-quinn-2009',
        evidenceType: 'STRUCTURAL_VALIDITY',
        population: 'Adolescents, students, military cadets, and adults in the original Grit-S development and validation studies',
        locale: 'en',
        territory: 'US',
        studyDesign: 'Development and validation of the 8-item short form with consistency-of-interest and perseverance-of-effort facets, retest evidence, and predictive/convergent analyses.',
        rating: 'SUFFICIENT',
        citation: 'Duckworth AL, Quinn PD. (2009). Development and validation of the Short Grit Scale (Grit-S). Journal of Personality Assessment, 91(2), 166–174.',
        doi: '10.1080/00223890802634290',
        url: 'https://doi.org/10.1080/00223890802634290',
        notes: 'The current author site still provides the 8-item Grit Scale while noting that the longer 12-item form is preferred when burden permits.',
      },
    ],
    referenceApplicability: [],
  },
  localization: {
    schemaVersion: 1,
    sourceLocale: 'en',
    targetLocale: 'zh-CN',
    localizationVersion: '1.0.0',
    translationSource: 'Authorized Chinese item wording previously used in the learning-motivation study, reordered to the canonical 8-item Grit-S sequence; standard response semantics restored.',
    adaptationMethod: 'DIRECT_TRANSLATION',
    expertReviewStatus: 'PENDING',
    cognitiveDebriefStatus: 'NOT_ESTABLISHED',
    localEvidenceRefs: [],
    reviewStatus: 'PENDING',
    notes: '题干沿用项目已授权中文措辞；产品版本恢复标准“像不像我”5 点反应格式。',
  },
  applicability: {
    schemaVersion: 1,
    policyVersion: 'grit-s-zh-cn-standard-v1',
    respondentTypes: ['SELF'],
    requiredContextKeys: [],
  },
  disclosure: {
    schemaVersion: 1,
    policyVersion: 'grit-s-zh-cn-standard-v1',
    audiences: {
      respondent: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: false,
        methods: true,
        educationalContent: false,
      },
      subject: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: false,
        methods: true,
        educationalContent: false,
      },
      teacher: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: false,
        methods: true,
        educationalContent: false,
      },
      researcher: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: true,
        methods: true,
        educationalContent: false,
      },
    },
    unknownAudience: 'DENY',
  },
  usageRequirements: {
    schemaVersion: 1,
    policyVersion: 'grit-s-zh-cn-standard-v1',
    requiredRightsActions: ['electronicAdministration', 'scoring', 'display'],
    allowedCommercialNatures: ['NON_COMMERCIAL', 'COMMERCIAL'],
    notes: [
      '项目方确认本量表及中文版本已取得计划部署所需授权。',
      '授权事实由 InstrumentAuthorization 记录；本 source 仅声明运行所需 rights actions。',
    ],
  },
  executable: {
    releaseStatus: 'PUBLISHED',
    contentLocale: 'zh-CN',
    references: [],
    definition: {
      schemaVersion: 2,
      respondentType: 'participant_self_report',
      source: {
        title: 'Short Grit Scale (Grit-S)',
        citation: 'Duckworth AL, Quinn PD. (2009). Development and validation of the Short Grit Scale (Grit-S).',
        url: 'https://www.angeladuckworth.com/measures',
        publicationYear: 2009,
      },
      license: {
        status: 'authorized',
        redistribution: 'restricted',
        note: '项目方确认已取得计划部署所需授权；发布和部署范围仍由 authorization/governance 层控制。',
      },
      display: {
        randomizeItems: false,
      },
      responseSets: [
        {
          key: 'grit_s_likeness_1_5_zh_cn',
          options: [
            { value: '1', label: '一点也不像我', score: 1 },
            { value: '2', label: '不太像我', score: 2 },
            { value: '3', label: '有点像我', score: 3 },
            { value: '4', label: '比较像我', score: 4 },
            { value: '5', label: '非常像我', score: 5 },
          ],
        },
      ],
      items: [
        {
          itemCode: 'GRIT-S-01',
          content: '新的想法和计划有时会让我无法专心于已有的想法和计划。',
          type: 'single',
          required: true,
          sortOrder: 0,
          responseSetKey: 'grit_s_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'GRIT-S-02',
          content: '挫折不会使我感到气馁。',
          type: 'single',
          required: true,
          sortOrder: 1,
          responseSetKey: 'grit_s_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'GRIT-S-03',
          content: '当着迷于某个想法或计划不久过后，我会对其失去兴趣。',
          type: 'single',
          required: true,
          sortOrder: 2,
          responseSetKey: 'grit_s_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'GRIT-S-04',
          content: '我是一个努力学习和工作的人。',
          type: 'single',
          required: true,
          sortOrder: 3,
          responseSetKey: 'grit_s_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'GRIT-S-05',
          content: '我经常设定一个目标，但不久后又改变追求另外一个目标。',
          type: 'single',
          required: true,
          sortOrder: 4,
          responseSetKey: 'grit_s_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'GRIT-S-06',
          content: '我很难让自己专注于一个要好几个月才能完成的任务。',
          type: 'single',
          required: true,
          sortOrder: 5,
          responseSetKey: 'grit_s_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'GRIT-S-07',
          content: '无论什么事情，只要我开了头就要完成它。',
          type: 'single',
          required: true,
          sortOrder: 6,
          responseSetKey: 'grit_s_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'GRIT-S-08',
          content: '我很勤奋，从不轻言放弃。',
          type: 'single',
          required: true,
          sortOrder: 7,
          responseSetKey: 'grit_s_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
      ],
      scoring: {
        scoringVersion: '1.0.0',
        itemRules: [
          { itemCode: 'GRIT-S-01', transform: { type: 'reverse' } },
          { itemCode: 'GRIT-S-02', transform: { type: 'identity' } },
          { itemCode: 'GRIT-S-03', transform: { type: 'reverse' } },
          { itemCode: 'GRIT-S-04', transform: { type: 'identity' } },
          { itemCode: 'GRIT-S-05', transform: { type: 'reverse' } },
          { itemCode: 'GRIT-S-06', transform: { type: 'reverse' } },
          { itemCode: 'GRIT-S-07', transform: { type: 'identity' } },
          { itemCode: 'GRIT-S-08', transform: { type: 'identity' } },
        ],
        defaultMissingPolicy: {
          type: 'complete_required',
        },
        scores: [
          {
            key: 'grit_total',
            type: 'total',
            label: '毅力总分',
            description: '8 个 Grit-S 项目在按键向统一后的平均分。',
            direction: 'higher_is_more',
            canonical: true,
            displayPrecision: 2,
            missingPolicy: { type: 'complete_required' },
            source: {
              type: 'items',
              items: [
                { itemCode: 'GRIT-S-01', weight: 1 },
                { itemCode: 'GRIT-S-02', weight: 1 },
                { itemCode: 'GRIT-S-03', weight: 1 },
                { itemCode: 'GRIT-S-04', weight: 1 },
                { itemCode: 'GRIT-S-05', weight: 1 },
                { itemCode: 'GRIT-S-06', weight: 1 },
                { itemCode: 'GRIT-S-07', weight: 1 },
                { itemCode: 'GRIT-S-08', weight: 1 },
              ],
              aggregation: 'mean',
            },
          },
          {
            key: 'consistency_of_interest',
            type: 'dimension',
            label: '兴趣一致性',
            description: '对长期目标保持相对持续兴趣与方向的一般倾向。',
            direction: 'higher_is_more',
            canonical: true,
            displayPrecision: 2,
            missingPolicy: { type: 'complete_required' },
            source: {
              type: 'items',
              items: [
                { itemCode: 'GRIT-S-01', weight: 1 },
                { itemCode: 'GRIT-S-03', weight: 1 },
                { itemCode: 'GRIT-S-05', weight: 1 },
                { itemCode: 'GRIT-S-06', weight: 1 },
              ],
              aggregation: 'mean',
            },
          },
          {
            key: 'perseverance_of_effort',
            type: 'dimension',
            label: '努力坚持',
            description: '面对困难、挫折和长期任务时持续努力的一般倾向。',
            direction: 'higher_is_more',
            canonical: true,
            displayPrecision: 2,
            missingPolicy: { type: 'complete_required' },
            source: {
              type: 'items',
              items: [
                { itemCode: 'GRIT-S-02', weight: 1 },
                { itemCode: 'GRIT-S-04', weight: 1 },
                { itemCode: 'GRIT-S-07', weight: 1 },
                { itemCode: 'GRIT-S-08', weight: 1 },
              ],
              aggregation: 'mean',
            },
          },
        ],
      },
      report: {
        reportVersion: '1.0.0',
        primaryScoreKeys: ['grit_total', 'consistency_of_interest', 'perseverance_of_effort'],
        scoreOrder: ['grit_total', 'consistency_of_interest', 'perseverance_of_effort'],
        interpretations: [
          {
            scoreKey: 'grit_total',
            headline: '长期目标坚持倾向',
            source: { type: 'score_only' },
            summary: '毅力总分综合描述你在较长期目标上保持方向并持续投入努力的倾向。分数较高表示本次自评中更常表现出持续投入和较稳定的目标追求；分数较低并不等同于能力不足，也可能与目标尚在探索、环境变化或当前资源条件有关。',
            bands: [],
            guidance: [],
          },
          {
            scoreKey: 'consistency_of_interest',
            headline: '兴趣一致性',
            source: { type: 'score_only' },
            summary: '兴趣一致性描述你在较长时间跨度内维持兴趣和目标方向的倾向。分数较高表示较少频繁转移长期目标；分数较低可能意味着兴趣更容易变化，也可能反映探索性更强，不能简单解释为好或坏。',
            bands: [],
            guidance: [],
          },
          {
            scoreKey: 'perseverance_of_effort',
            headline: '努力坚持',
            source: { type: 'score_only' },
            summary: '努力坚持描述你在面对困难、挫折或长期任务时继续投入努力的倾向。分数较高表示更倾向于坚持完成和从挫折中继续推进；分数较低需要结合任务价值、支持条件和负担水平理解。',
            bands: [],
            guidance: [],
          },
        ],
        limitations: [
          'Grit-S 是极简自我报告工具，不能替代对学习机会、资源、能力、环境支持或具体行为表现的评估。',
          '本 PILOT package 不提供中国人群常模、百分位、cut-off 或“高/低毅力”标签。',
          'Grit-S 主要用于个体差异研究；不应把短期前后测变化直接解释为稳定人格特质发生改变。',
          '结果不应用于招生、招聘、奖惩、学校排名或其他高风险决策。',
        ],
        disclaimer: '本报告仅用于研究和描述性自我了解，不用于诊断、能力鉴定或高风险选择。毅力分数描述的是自陈倾向，不是对个人价值、潜力或未来成就的判定。',
      },
      referencePolicy: {
        type: 'none',
      },
    },
    goldenCases: [
      {
        name: 'all-midpoint',
        answers: [
          { itemCode: 'GRIT-S-01', responseValue: '3' },
          { itemCode: 'GRIT-S-02', responseValue: '3' },
          { itemCode: 'GRIT-S-03', responseValue: '3' },
          { itemCode: 'GRIT-S-04', responseValue: '3' },
          { itemCode: 'GRIT-S-05', responseValue: '3' },
          { itemCode: 'GRIT-S-06', responseValue: '3' },
          { itemCode: 'GRIT-S-07', responseValue: '3' },
          { itemCode: 'GRIT-S-08', responseValue: '3' },
        ],
        expected: {
          quality: 'interpretable',
          scores: {
            grit_total: 3,
            consistency_of_interest: 3,
            perseverance_of_effort: 3,
          },
          totalScoreKeys: ['grit_total', 'consistency_of_interest', 'perseverance_of_effort'],
        },
      },
      {
        name: 'trait-high',
        answers: [
          { itemCode: 'GRIT-S-01', responseValue: '1' },
          { itemCode: 'GRIT-S-02', responseValue: '5' },
          { itemCode: 'GRIT-S-03', responseValue: '1' },
          { itemCode: 'GRIT-S-04', responseValue: '5' },
          { itemCode: 'GRIT-S-05', responseValue: '1' },
          { itemCode: 'GRIT-S-06', responseValue: '1' },
          { itemCode: 'GRIT-S-07', responseValue: '5' },
          { itemCode: 'GRIT-S-08', responseValue: '5' },
        ],
        expected: {
          quality: 'interpretable',
          scores: {
            grit_total: 5,
            consistency_of_interest: 5,
            perseverance_of_effort: 5,
          },
          totalScoreKeys: ['grit_total', 'consistency_of_interest', 'perseverance_of_effort'],
        },
      },
      {
        name: 'trait-low',
        answers: [
          { itemCode: 'GRIT-S-01', responseValue: '5' },
          { itemCode: 'GRIT-S-02', responseValue: '1' },
          { itemCode: 'GRIT-S-03', responseValue: '5' },
          { itemCode: 'GRIT-S-04', responseValue: '1' },
          { itemCode: 'GRIT-S-05', responseValue: '5' },
          { itemCode: 'GRIT-S-06', responseValue: '5' },
          { itemCode: 'GRIT-S-07', responseValue: '1' },
          { itemCode: 'GRIT-S-08', responseValue: '1' },
        ],
        expected: {
          quality: 'interpretable',
          scores: {
            grit_total: 1,
            consistency_of_interest: 1,
            perseverance_of_effort: 1,
          },
          totalScoreKeys: ['grit_total', 'consistency_of_interest', 'perseverance_of_effort'],
        },
      },
    ],
  },
} satisfies ScaleInstrumentSourceV1
