import type { ScaleInstrumentSourceV1 } from '../../../onboarding/types'

export const SCALE_INSTRUMENT_SOURCE = {
  schemaVersion: 1,
  identity: {
    instrumentKey: 'bscs_zh_cn',
    instrumentVersion: '1.0.0',
  },
  catalog: {
    schemaVersion: 1,
    catalogManifestVersion: 1,
    catalogStatus: 'REVIEWED',
    scientificMaturity: 'PILOT',
    identity: {
      canonicalName: 'Brief Self-Control Scale — Chinese Standard 13-item',
      abbreviation: 'BSCS',
      instrumentFamily: 'Brief Self-Control Scale',
    },
    construct: {
      primaryDomain: 'SELF_REGULATION',
      secondaryDomains: [],
      constructDefinition: '描述个体抵制诱惑、减少冲动反应并持续朝长期目标行动的总体特质性自我控制倾向。',
      constructLevel: 'SPECIFIC_CONSTRUCT',
      constructOverlapTags: [
        'trait_self_control',
        'impulse_control',
        'temptation_resistance',
        'goal_persistence',
        'self_report',
      ],
    },
    population: {
      populationNotes: 'BSCS 为一般自陈特质自我控制工具。本 package 恢复标准 13 题顺序与 1–5“像不像我”作答语义；不沿用项目历史问卷的同意度锚点或项目内部三分组。',
      respondentTypes: ['SELF'],
      developmentalEvidence: 'PARTIAL',
    },
    administration: {
      itemCount: 13,
      estimatedMinutes: 4,
      administrationModes: ['DIGITAL_SELF_ADMINISTERED', 'DIGITAL_SUPERVISED', 'PAPER'],
      timeFrame: '一般/典型自我描述；无特定回忆时段',
      requiredTraining: false,
      itemOrderLocked: true,
      responseFormatLocked: true,
      layoutConstraints: [
        '保持标准 BSCS 的 13 题顺序与 1–5“像不像我”作答语义。',
        '只把 13 题总体自我控制作为主要量表分数；不把项目历史中的 Disciplined Planning、Impulse Inhibition、Self-Management 当作原量表正式分量表。',
      ],
    },
    intendedUse: {
      intendedUses: [
        {
          use: 'RESEARCH',
          evidenceStatus: 'SUPPORTED',
        },
        {
          use: 'INDIVIDUAL_REFLECTION',
          evidenceStatus: 'EVIDENCE_UNKNOWN',
          notes: '仅提供总体自我控制倾向的描述性反馈，不提供规范性等级。',
        },
      ],
      forbiddenUses: [
        'DIAGNOSIS',
        'HIGH_STAKES_SELECTION',
        'SCHOOL_RANKING',
        'TEACHER_ACCOUNTABILITY',
        'UNSUPPORTED_GROUP_COMPARISON',
      ],
    },
    evidence: [
      {
        evidenceId: 'bscs-tangney-2004',
        evidenceType: 'INTERNAL_CONSISTENCY',
        population: 'University students and community/young adult samples in the original scale-development studies',
        locale: 'en',
        territory: 'US',
        studyDesign: 'Scale development and validation with internal consistency, retest reliability, and associations with academic, adjustment, interpersonal, and health-related outcomes.',
        rating: 'SUFFICIENT',
        citation: 'Tangney JP, Baumeister RF, Boone AL. (2004). High self-control predicts good adjustment, less pathology, better grades, and interpersonal success. Journal of Personality, 72(2), 271–324.',
        doi: '10.1111/j.0022-3506.2004.00263.x',
        url: 'https://doi.org/10.1111/j.0022-3506.2004.00263.x',
      },
      {
        evidenceId: 'bscs-china-dimensionality-2019',
        evidenceType: 'STRUCTURAL_VALIDITY',
        population: 'Chinese university students',
        locale: 'zh-CN',
        territory: 'CN',
        studyDesign: 'Psychometric evaluation of dimensionality and alternative factor structures of the 13-item BSCS among Chinese university students.',
        rating: 'MIXED',
        citation: 'Evaluating the Dimensionality and Psychometric Properties of the Brief Self-Control Scale Amongst Chinese University Students. Frontiers in Psychology (2019).',
        url: 'https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2019.02903/full',
        notes: 'This evidence supports use of the BSCS in Chinese samples while also showing that factor-structure interpretations beyond the overall scale remain contested.',
      },
    ],
    referenceApplicability: [],
  },
  localization: {
    schemaVersion: 1,
    sourceLocale: 'en',
    targetLocale: 'zh-CN',
    localizationVersion: '1.0.0',
    translationSource: 'Authorized Chinese item wording previously used in the learning-motivation study, reordered to the canonical 13-item BSCS sequence; standard response semantics restored.',
    adaptationMethod: 'DIRECT_TRANSLATION',
    expertReviewStatus: 'PENDING',
    cognitiveDebriefStatus: 'NOT_ESTABLISHED',
    localEvidenceRefs: ['bscs-china-dimensionality-2019'],
    reviewStatus: 'PENDING',
    notes: '题干沿用项目已授权中文措辞；产品版本使用标准“像不像我”5 点反应格式。',
  },
  applicability: {
    schemaVersion: 1,
    policyVersion: 'bscs-zh-cn-standard-v1',
    respondentTypes: ['SELF'],
    requiredContextKeys: [],
  },
  disclosure: {
    schemaVersion: 1,
    policyVersion: 'bscs-zh-cn-standard-v1',
    audiences: {
      respondent: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: false,
        methods: true,
        educationalContent: false,
      },
      subject: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: false,
        methods: true,
        educationalContent: false,
      },
      teacher: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: false,
        methods: true,
        educationalContent: false,
      },
      researcher: {
        numericScores: true,
        references: false,
        individualInterpretations: true,
        scoreDerivedLabels: false,
        resultQualityDetails: true,
        rawAnswers: false,
        itemScores: true,
        methods: true,
        educationalContent: false,
      },
    },
    unknownAudience: 'DENY',
  },
  usageRequirements: {
    schemaVersion: 1,
    policyVersion: 'bscs-zh-cn-standard-v1',
    requiredRightsActions: ['electronicAdministration', 'scoring', 'display'],
    allowedCommercialNatures: ['NON_COMMERCIAL', 'COMMERCIAL'],
    notes: [
      '项目方确认本量表及中文版本已取得计划部署所需授权。',
      '授权事实由 InstrumentAuthorization 记录；本 source 不把文献可见性等同于授权范围。',
    ],
  },
  executable: {
    releaseStatus: 'PUBLISHED',
    contentLocale: 'zh-CN',
    references: [],
    definition: {
      schemaVersion: 2,
      respondentType: 'participant_self_report',
      source: {
        title: 'Brief Self-Control Scale (BSCS)',
        citation: 'Tangney JP, Baumeister RF, Boone AL. (2004). High self-control predicts good adjustment, less pathology, better grades, and interpersonal success.',
        url: 'https://doi.org/10.1111/j.0022-3506.2004.00263.x',
        publicationYear: 2004,
      },
      license: {
        status: 'authorized',
        redistribution: 'restricted',
        note: '项目方确认已取得计划部署所需授权；实际部署仍受 authorization/governance scope 约束。',
      },
      display: {
        randomizeItems: false,
      },
      responseSets: [
        {
          key: 'bscs_likeness_1_5_zh_cn',
          options: [
            { value: '1', label: '一点也不像我', score: 1 },
            { value: '2', label: '有一点像我', score: 2 },
            { value: '3', label: '有些像我', score: 3 },
            { value: '4', label: '比较像我', score: 4 },
            { value: '5', label: '非常像我', score: 5 },
          ],
        },
      ],
      items: [
        {
          itemCode: 'BSCS-01',
          content: '我能很好地抵制诱惑。',
          type: 'single',
          required: true,
          sortOrder: 0,
          responseSetKey: 'bscs_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'BSCS-02',
          content: '对我来说改掉坏习惯是困难的。',
          type: 'single',
          required: true,
          sortOrder: 1,
          responseSetKey: 'bscs_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'BSCS-03',
          content: '我很懒。',
          type: 'single',
          required: true,
          sortOrder: 2,
          responseSetKey: 'bscs_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'BSCS-04',
          content: '我经常会说一些不合时宜的话。',
          type: 'single',
          required: true,
          sortOrder: 3,
          responseSetKey: 'bscs_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'BSCS-05',
          content: '只要我觉得好玩的事，就算是对我有害也照做不误。',
          type: 'single',
          required: true,
          sortOrder: 4,
          responseSetKey: 'bscs_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'BSCS-06',
          content: '我会避免做出对自己有害的事。',
          type: 'single',
          required: true,
          sortOrder: 5,
          responseSetKey: 'bscs_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'BSCS-07',
          content: '我希望自己能更自律一些。',
          type: 'single',
          required: true,
          sortOrder: 6,
          responseSetKey: 'bscs_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'BSCS-08',
          content: '人们说我能严格自律。',
          type: 'single',
          required: true,
          sortOrder: 7,
          responseSetKey: 'bscs_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'BSCS-09',
          content: '享乐有时让我无法完成工作。',
          type: 'single',
          required: true,
          sortOrder: 8,
          responseSetKey: 'bscs_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'BSCS-10',
          content: '我很难集中精力或注意力。',
          type: 'single',
          required: true,
          sortOrder: 9,
          responseSetKey: 'bscs_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'BSCS-11',
          content: '我能为了长远目标而有效率地工作或学习。',
          type: 'single',
          required: true,
          sortOrder: 10,
          responseSetKey: 'bscs_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'BSCS-12',
          content: '有时我会忍不住去做一些事情，即使我知道那样做是错的。',
          type: 'single',
          required: true,
          sortOrder: 11,
          responseSetKey: 'bscs_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
        {
          itemCode: 'BSCS-13',
          content: '做事时，我经常不进行全面考虑就采取行动。',
          type: 'single',
          required: true,
          sortOrder: 12,
          responseSetKey: 'bscs_likeness_1_5_zh_cn',
          randomizeOptions: false,
        },
      ],
      scoring: {
        scoringVersion: '1.0.0',
        itemRules: [
          { itemCode: 'BSCS-01', transform: { type: 'identity' } },
          { itemCode: 'BSCS-02', transform: { type: 'reverse' } },
          { itemCode: 'BSCS-03', transform: { type: 'reverse' } },
          { itemCode: 'BSCS-04', transform: { type: 'reverse' } },
          { itemCode: 'BSCS-05', transform: { type: 'reverse' } },
          { itemCode: 'BSCS-06', transform: { type: 'identity' } },
          { itemCode: 'BSCS-07', transform: { type: 'reverse' } },
          { itemCode: 'BSCS-08', transform: { type: 'identity' } },
          { itemCode: 'BSCS-09', transform: { type: 'reverse' } },
          { itemCode: 'BSCS-10', transform: { type: 'reverse' } },
          { itemCode: 'BSCS-11', transform: { type: 'identity' } },
          { itemCode: 'BSCS-12', transform: { type: 'reverse' } },
          { itemCode: 'BSCS-13', transform: { type: 'reverse' } },
        ],
        defaultMissingPolicy: {
          type: 'complete_required',
        },
        scores: [
          {
            key: 'self_control',
            type: 'total',
            label: '总体自我控制',
            description: '13 个 BSCS 项目在按键向统一后的平均分。',
            direction: 'higher_is_more',
            canonical: true,
            displayPrecision: 2,
            missingPolicy: { type: 'complete_required' },
            source: {
              type: 'items',
              items: [
                { itemCode: 'BSCS-01', weight: 1 },
                { itemCode: 'BSCS-02', weight: 1 },
                { itemCode: 'BSCS-03', weight: 1 },
                { itemCode: 'BSCS-04', weight: 1 },
                { itemCode: 'BSCS-05', weight: 1 },
                { itemCode: 'BSCS-06', weight: 1 },
                { itemCode: 'BSCS-07', weight: 1 },
                { itemCode: 'BSCS-08', weight: 1 },
                { itemCode: 'BSCS-09', weight: 1 },
                { itemCode: 'BSCS-10', weight: 1 },
                { itemCode: 'BSCS-11', weight: 1 },
                { itemCode: 'BSCS-12', weight: 1 },
                { itemCode: 'BSCS-13', weight: 1 },
              ],
              aggregation: 'mean',
            },
          },
        ],
      },
      report: {
        reportVersion: '1.0.0',
        primaryScoreKeys: ['self_control'],
        scoreOrder: ['self_control'],
        interpretations: [
          {
            scoreKey: 'self_control',
            headline: '总体自我控制倾向',
            source: { type: 'score_only' },
            summary: '该分数描述你在日常情境中抵制诱惑、避免冲动反应、维持注意并朝长期目标行动的总体自陈倾向。分数较高表示这些自我调节行为在自我描述中更典型；分数较低并不等同于能力不足，应结合当前压力、环境结构、任务要求和支持条件理解。',
            bands: [],
            guidance: [],
          },
        ],
        limitations: [
          'BSCS 是自我报告的特质性自我控制指标，不等同于执行功能任务、注意力测试或客观行为表现。',
          '本 package 只解释标准 13 题总体分，不把项目历史中的三类探索性分组作为正式分量表。',
          '本 PILOT package 不提供中国人群常模、百分位、cut-off 或“自控力高/低”标签。',
          '自我控制分数可能受到情境压力、睡眠、环境诱因、社会期望和自我认识影响。',
        ],
        disclaimer: '本报告用于研究和描述性自我了解，不用于心理诊断、注意力障碍判断、能力鉴定、纪律评价或高风险选拔。',
      },
      referencePolicy: {
        type: 'none',
      },
    },
    goldenCases: [
      {
        name: 'all-midpoint',
        answers: [
          { itemCode: 'BSCS-01', responseValue: '3' },
          { itemCode: 'BSCS-02', responseValue: '3' },
          { itemCode: 'BSCS-03', responseValue: '3' },
          { itemCode: 'BSCS-04', responseValue: '3' },
          { itemCode: 'BSCS-05', responseValue: '3' },
          { itemCode: 'BSCS-06', responseValue: '3' },
          { itemCode: 'BSCS-07', responseValue: '3' },
          { itemCode: 'BSCS-08', responseValue: '3' },
          { itemCode: 'BSCS-09', responseValue: '3' },
          { itemCode: 'BSCS-10', responseValue: '3' },
          { itemCode: 'BSCS-11', responseValue: '3' },
          { itemCode: 'BSCS-12', responseValue: '3' },
          { itemCode: 'BSCS-13', responseValue: '3' },
        ],
        expected: {
          quality: 'interpretable',
          scores: {
            self_control: 3,
          },
          totalScoreKeys: ['self_control'],
        },
      },
      {
        name: 'trait-high',
        answers: [
          { itemCode: 'BSCS-01', responseValue: '5' },
          { itemCode: 'BSCS-02', responseValue: '1' },
          { itemCode: 'BSCS-03', responseValue: '1' },
          { itemCode: 'BSCS-04', responseValue: '1' },
          { itemCode: 'BSCS-05', responseValue: '1' },
          { itemCode: 'BSCS-06', responseValue: '5' },
          { itemCode: 'BSCS-07', responseValue: '1' },
          { itemCode: 'BSCS-08', responseValue: '5' },
          { itemCode: 'BSCS-09', responseValue: '1' },
          { itemCode: 'BSCS-10', responseValue: '1' },
          { itemCode: 'BSCS-11', responseValue: '5' },
          { itemCode: 'BSCS-12', responseValue: '1' },
          { itemCode: 'BSCS-13', responseValue: '1' },
        ],
        expected: {
          quality: 'interpretable',
          scores: {
            self_control: 5,
          },
          totalScoreKeys: ['self_control'],
        },
      },
      {
        name: 'trait-low',
        answers: [
          { itemCode: 'BSCS-01', responseValue: '1' },
          { itemCode: 'BSCS-02', responseValue: '5' },
          { itemCode: 'BSCS-03', responseValue: '5' },
          { itemCode: 'BSCS-04', responseValue: '5' },
          { itemCode: 'BSCS-05', responseValue: '5' },
          { itemCode: 'BSCS-06', responseValue: '1' },
          { itemCode: 'BSCS-07', responseValue: '5' },
          { itemCode: 'BSCS-08', responseValue: '1' },
          { itemCode: 'BSCS-09', responseValue: '5' },
          { itemCode: 'BSCS-10', responseValue: '5' },
          { itemCode: 'BSCS-11', responseValue: '1' },
          { itemCode: 'BSCS-12', responseValue: '5' },
          { itemCode: 'BSCS-13', responseValue: '5' },
        ],
        expected: {
          quality: 'interpretable',
          scores: {
            self_control: 1,
          },
          totalScoreKeys: ['self_control'],
        },
      },
    ],
  },
} satisfies ScaleInstrumentSourceV1
