#!/bin/bash
# =============================================================================
# PTool 增强备份系统
# 功能: 全量备份 + 加密 + 异地存储 + 校验/恢复
# 说明: 原有 WAL tar 增量备份已暂停，待正式 PITR 链路实现后再启用
# =============================================================================

set -Eeuo pipefail

# 配置
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/backup-config.env"

# 默认配置
BACKUP_BASE_DIR="${BACKUP_BASE_DIR:-/backup/ptool}"
LOCAL_BACKUP_DIR="${LOCAL_BACKUP_DIR:-$BACKUP_BASE_DIR/local}"
ENCRYPTED_DIR="${ENCRYPTED_DIR:-$BACKUP_BASE_DIR/encrypted}"
LOG_FILE="${LOG_FILE:-/var/log/ptool/monitoring/backup.log}"
DB_NAME="${DB_NAME:-ptool}"
DB_USER="${DB_USER:-ptool}"
POSTGRES_CONTAINER="${POSTGRES_CONTAINER:-ptool-postgres}"
BACKEND_CONTAINER="${BACKEND_CONTAINER:-ptool-backend}"
APP_ROOT="${APP_ROOT:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"
LOCAL_RETENTION_DAYS="${LOCAL_RETENTION_DAYS:-7}"
COS_RETENTION_DAYS="${COS_RETENTION_DAYS:-7}"

# 加密配置
ENABLE_ENCRYPTION="${ENABLE_ENCRYPTION:-true}"
ENCRYPTION_KEY="${BACKUP_ENCRYPTION_KEY:-}"

# 远程存储配置 (可选)
REMOTE_TYPE="${REMOTE_TYPE:-}"  # s3, cos, oss, scp
REMOTE_ENDPOINT="${REMOTE_ENDPOINT:-}"
REMOTE_BUCKET="${REMOTE_BUCKET:-}"
REMOTE_ACCESS_KEY="${REMOTE_ACCESS_KEY:-}"
REMOTE_SECRET_KEY="${REMOTE_SECRET_KEY:-}"
COS_REGION="${COS_REGION:-ap-beijing}"
COS_BACKUP_PREFIX="${COS_BACKUP_PREFIX:-backups/ptool}"

# Temporary plaintext is kept in private directories and removed when this
# process exits, including failure paths.  The paths are generated by
# mktemp, never taken from a user-controlled recursive target.
TEMP_DIRS=()
cleanup_temp_dirs() {
    local temp_dir
    for temp_dir in "${TEMP_DIRS[@]}"; do
        if [ -n "$temp_dir" ]; then
            rm -rf -- "$temp_dir"
        fi
    done
}
register_temp_dir() {
    TEMP_DIRS+=("$1")
}
trap cleanup_temp_dirs EXIT

# 加载自定义配置
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
fi

# The Compose .env is the supported source for COS credentials.  Export only
# the names consumed by the Node.js helper; never read a tracked .env file or
# print credential values from this script.
export COS_SECRET_ID="${COS_SECRET_ID:-${REMOTE_ACCESS_KEY:-}}"
export COS_SECRET_KEY="${COS_SECRET_KEY:-${REMOTE_SECRET_KEY:-}}"
export COS_BUCKET="${COS_BUCKET:-${REMOTE_BUCKET:-}}"
export COS_REGION="${COS_REGION:-ap-beijing}"

# 初始化
init() {
    mkdir -p "$LOCAL_BACKUP_DIR" "$ENCRYPTED_DIR" "$(dirname "$LOG_FILE")"
    touch "$LOG_FILE"

    ENCRYPTION_KEY="${BACKUP_ENCRYPTION_KEY:-}"
    if [ "$ENABLE_ENCRYPTION" = "true" ]; then
        if [ -z "$ENCRYPTION_KEY" ]; then
            log "错误: ENABLE_ENCRYPTION=true 时必须设置 BACKUP_ENCRYPTION_KEY"
            return 1
        fi
        if [ "${#ENCRYPTION_KEY}" -lt 32 ]; then
            log "错误: BACKUP_ENCRYPTION_KEY 至少需要32个字符"
            return 1
        fi
    fi

    if [ "$REMOTE_TYPE" = "cos" ]; then
        if [ -z "$COS_SECRET_ID" ] || [ -z "$COS_SECRET_KEY" ] || [ -z "$COS_BUCKET" ] || [ -z "$COS_REGION" ]; then
            log "错误: REMOTE_TYPE=cos 时必须设置 COS_SECRET_ID、COS_SECRET_KEY、COS_BUCKET 和 COS_REGION"
            return 1
        fi
    fi
}

# 日志
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >&2
}

# 发送通知
notify() {
    local message="$1"
    logger -t ptool-backup "$message"
    
    if [ -n "${BACKUP_WEBHOOK:-}" ]; then
        curl -s -X POST "$BACKUP_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "{\"event\":\"backup\",\"message\":\"$message\",\"timestamp\":\"$(date -Iseconds)\"}" \
            > /dev/null 2>&1 || true
    fi
}

# 生成备份文件名
generate_backup_name() {
    local type="$1"  # full 或 incremental
    local timestamp=$(date +%Y%m%d_%H%M%S)
    echo "ptool_${type}_${timestamp}"
}

# 数据库备份
backup_database() {
    local backup_name="$1"
    local backup_dir="$2"
    local sql_file="${backup_dir}/${backup_name}.sql"
    
    log "备份数据库: $DB_NAME"
    
    validate_postgres_container

    # The database is private to the Compose network.  Dump through the
    # running Postgres container instead of using host sudo/peer auth.
    docker exec "$POSTGRES_CONTAINER" pg_dump \
        --username="$DB_USER" \
        --dbname="$DB_NAME" \
        --format=custom \
        --compress=9 \
        > "$sql_file" 2>>"$LOG_FILE"
    
    if [ -f "$sql_file" ]; then
        local size=$(du -h "$sql_file" | cut -f1)
        log "数据库备份完成: $sql_file (大小: $size)"
        echo "$sql_file"
    else
        log "错误: 数据库备份失败"
        return 1
    fi
}

# 文件备份
backup_files() {
    local backup_name="$1"
    local backup_dir="$2"
    local tar_file="${backup_dir}/${backup_name}_files.tar.gz"
    
    log "备份应用文件..."
    
    local temp_dir
    temp_dir=$(mktemp -d)
    if ! docker cp "$BACKEND_CONTAINER:/app/uploads" "$temp_dir/uploads" >>"$LOG_FILE" 2>&1; then
        rm -rf "$temp_dir"
        log "错误: 无法从 Docker backend 容器复制 uploads 数据"
        return 1
    fi

    # Uploads live in the named Docker volume; copy the volume content out
    # through the container boundary and exclude transient/video artifacts.
    if ! tar -czf "$tar_file" \
        --exclude='*.tmp' \
        --exclude='*.log' \
        --exclude='node_modules' \
        --exclude='uploads/videos' \
        -C "$temp_dir" uploads; then
        rm -rf "$temp_dir"
        log "错误: 无法生成应用文件备份"
        return 1
    fi
    rm -rf "$temp_dir"
    
    if [ -f "$tar_file" ]; then
        local size=$(du -h "$tar_file" | cut -f1)
        log "文件备份完成: $tar_file (大小: $size)"
        echo "$tar_file"
    fi
}

# 配置文件备份
backup_configs() {
    local backup_name="$1"
    local backup_dir="$2"
    local config_file="${backup_dir}/${backup_name}_configs.tar.gz"
    
    log "备份配置文件..."
    
    local config_paths=()
    for candidate in docker-compose.yml .env frontend/.env.production; do
        if [ -e "$APP_ROOT/$candidate" ]; then
            config_paths+=("$candidate")
        fi
    done

    if [ "${#config_paths[@]}" -eq 0 ]; then
        log "错误: 未找到 Compose 配置，拒绝生成空配置备份"
        return 1
    fi

    # Compose is the supported production topology.  The .env, when present,
    # is encrypted together with the backup and is never written to logs.
    tar -czf "$config_file" -C "$APP_ROOT" "${config_paths[@]}"
    
    if [ -f "$config_file" ]; then
        local size=$(du -h "$config_file" | cut -f1)
        log "配置备份完成: $config_file (大小: $size)"
        echo "$config_file"
    fi
}

validate_postgres_container() {
    if [[ ! "$POSTGRES_CONTAINER" =~ ^[A-Za-z0-9_.-]+$ ]]; then
        log "错误: POSTGRES_CONTAINER 名称无效"
        return 1
    fi

    local image
    if ! docker inspect "$POSTGRES_CONTAINER" >/dev/null 2>&1; then
        log "错误: Docker PostgreSQL 容器不存在: $POSTGRES_CONTAINER"
        return 1
    fi
    image=$(docker inspect --format '{{.Config.Image}}' "$POSTGRES_CONTAINER")
    if [[ "$image" != *postgres* ]]; then
        log "错误: 恢复目标不是 PostgreSQL 镜像"
        return 1
    fi
}

openssl_encrypt() {
    local input_file="$1"
    local output_file="$2"
    BACKUP_ENCRYPTION_KEY="$ENCRYPTION_KEY" openssl enc -aes-256-cbc \
        -salt -pbkdf2 -iter 100000 \
        -pass env:BACKUP_ENCRYPTION_KEY \
        -in "$input_file" -out "$output_file"
}

openssl_decrypt() {
    local input_file="$1"
    local output_file="$2"
    BACKUP_ENCRYPTION_KEY="$ENCRYPTION_KEY" openssl enc -aes-256-cbc -d \
        -pbkdf2 -iter 100000 \
        -pass env:BACKUP_ENCRYPTION_KEY \
        -in "$input_file" -out "$output_file"
}

# 加密备份文件
encrypt_backup() {
    local input_file="$1"
    local output_file="${ENCRYPTED_DIR}/$(basename $input_file).enc"
    
    if [ "$ENABLE_ENCRYPTION" != "true" ]; then
        cp "$input_file" "$ENCRYPTED_DIR/"
        sha256sum "$input_file" | awk '{print $1}' > "${ENCRYPTED_DIR}/$(basename "$input_file").sha256"
        return 0
    fi
    
    log "加密备份文件: $(basename $input_file)"
    
    # Use the same explicit PBKDF2 parameters for encryption and decryption.
    openssl_encrypt "$input_file" "$output_file"
    
    # 计算校验和
    local checksum
    checksum=$(sha256sum "$input_file" | awk '{print $1}')
    echo "$checksum" > "${output_file}.sha256"
    
    log "加密完成: $output_file"
    echo "$output_file"
}

# Node.js COS 工具路径
COS_BACKUP_JS="${SCRIPT_DIR}/cos-backup.js"

# 上传到远程存储 (使用 Node.js SDK)
upload_to_remote() {
    local file="$1"
    local filename="$(basename $file)"
    local remote_path="${COS_BACKUP_PREFIX}/${filename}"
    
    if [ -z "$REMOTE_TYPE" ]; then
        log "未配置远程存储，跳过上传"
        return 0
    fi
    
    if [ "$REMOTE_TYPE" != "cos" ]; then
        log "不支持的远程存储类型: $REMOTE_TYPE (仅支持 cos)"
        return 1
    fi
    
    log "上传到 COS: $remote_path"
    
    # 使用 Node.js SDK 上传
    local result
    result=$(node "$COS_BACKUP_JS" upload "$file" "$remote_path" 2>&1)
    local upload_status=$?
    
    # 输出到日志
    echo "$result" | tee -a "$LOG_FILE"
    
    if [ $upload_status -eq 0 ]; then
        # 解析 JSON 获取文件大小
        local file_size=$(du -b "$file" | cut -f1)
        log "上传成功: $filename -> cos://$REMOTE_BUCKET/$remote_path"
        # 记录上传的备份信息
        echo "$(date -Iseconds)|$filename|$remote_path|$file_size" >> "$BACKUP_BASE_DIR/remote-backups.log"
        return 0
    else
        log "错误: 上传失败 $filename"
        return 1
    fi
}

# 清理 COS 上的旧备份 (使用 Node.js SDK)
cleanup_cos_backups() {
    log "清理 COS 上的旧备份..."
    
    local cos_days=${COS_RETENTION_DAYS:-7}
    local result
    result=$(node "$COS_BACKUP_JS" cleanup "$COS_BACKUP_PREFIX/" "$cos_days" 2>&1)
    local cleanup_status=$?
    
    echo "$result" | tee -a "$LOG_FILE"
    
    if [ $cleanup_status -eq 0 ]; then
        local deleted=$(echo "$result" | grep -o '"deleted":[0-9]*' | cut -d: -f2)
        log "COS 清理完成: ${deleted:-0} 个文件 (保留 ${cos_days} 天)"
    else
        log "COS 清理失败"
    fi
}

# 列出 COS 上的备份 (使用 Node.js SDK)
list_cos_backups() {
    local result
    result=$(node "$COS_BACKUP_JS" list "$COS_BACKUP_PREFIX/" 2>&1)
    local list_status=$?
    
    if [ $list_status -eq 0 ]; then
        # 解析 JSON 输出
        local count=$(echo "$result" | grep -o '"count":[0-9]*' | head -1 | cut -d: -f2)
        echo "COS 备份数: ${count:-0}"
        
        # 列出文件
        echo "$result" | grep -o '"key":"[^"]*"' | cut -d'"' -f4 | while read key; do
            if [ -n "$key" ]; then
                echo "  - $key"
            fi
        done
    else
        echo "无法获取 COS 备份列表"
    fi
}



# 全量备份
full_backup() {
    log "========== 开始全量备份 =========="
    
    local backup_name=$(generate_backup_name "full")
    local backup_dir="${LOCAL_BACKUP_DIR}/${backup_name}"
    mkdir -p "$backup_dir"
    
    # 1. 备份数据库
    local db_backup
    db_backup=$(backup_database "$backup_name" "$backup_dir")
    
    # 2. 备份文件
    local file_backup
    file_backup=$(backup_files "$backup_name" "$backup_dir")
    
    # 3. 备份配置
    local config_backup
    config_backup=$(backup_configs "$backup_name" "$backup_dir")
    
    # 4. 创建备份清单
    cat > "${backup_dir}/manifest.json" << EOF
{
    "type": "full",
    "name": "$backup_name",
    "timestamp": "$(date -Iseconds)",
    "hostname": "$(hostname)",
    "files": [
        $(if [ -n "$db_backup" ]; then echo "\"$(basename $db_backup)\""; fi)
        $(if [ -n "$file_backup" ]; then echo "\"$(basename $file_backup)\""; fi)
        $(if [ -n "$config_backup" ]; then echo "\"$(basename $config_backup)\""; fi)
    ],
    "version": "1.0"
}
EOF
    
    # 5. 加密备份
    for file in "$db_backup" "$file_backup" "$config_backup"; do
        if [ -f "$file" ]; then
            encrypt_backup "$file"
        fi
    done
    
    # 6. 上传到远程
    for enc_file in "${ENCRYPTED_DIR}"/*.enc; do
        if [ -f "$enc_file" ]; then
            upload_to_remote "$enc_file"
        fi
    done
    
    # 7. 清理本地临时文件
    rm -rf "$backup_dir"
    
    # 8. 记录备份信息
    local total_size=$(du -sh "$ENCRYPTED_DIR" | cut -f1)
    log "全量备份完成: $backup_name (总大小: $total_size)"
    notify "全量备份完成: $backup_name"
    
    # 9. 清理旧备份
    cleanup_old_backups
    
    log "========== 全量备份结束 =========="
}

# 增量备份（暂停）
incremental_backup() {
    log "错误: 增量 WAL 备份已暂停；请先实现 base backup + WAL archiving/PITR"
    return 1
}

# 清理旧备份
cleanup_old_backups() {
    log "清理旧备份..."
    
    # 本地清理（保留N天）- 修复: 使用 mtime +$((local_days-1)) 确保严格保留指定天数
    local local_days=${LOCAL_RETENTION_DAYS:-3}
    local local_count
    local_count=$(find "$ENCRYPTED_DIR" -type f -name "*.enc" -mtime +$((local_days-1)) 2>/dev/null | wc -l | tr -d ' ')
    find "$ENCRYPTED_DIR" -type f -name "*.enc" -mtime +$((local_days-1)) -delete
    find "$ENCRYPTED_DIR" -type f -name "*.sha256" -mtime +$((local_days-1)) -delete
    log "本地清理完成: ${local_count} 个文件 (保留 ${local_days} 天)"
    
    # 远程清理 (COS，保留7天)
    if [ "$REMOTE_TYPE" == "cos" ] && [ -n "$REMOTE_BUCKET" ]; then
        cleanup_cos_backups
    fi
    
    log "备份清理完成"
}



# 验证备份
verify_backup() {
    local backup_file="$1"
    
    log "验证备份文件: $(basename $backup_file)"
    
    # 1. 检查文件存在
    if [ ! -f "$backup_file" ]; then
        log "错误: 备份文件不存在"
        return 1
    fi
    
    if [ "$ENABLE_ENCRYPTION" = "true" ] && [[ "$backup_file" != *.enc ]]; then
        log "错误: 加密模式下只能验证 .enc 备份文件"
        return 1
    fi

    # 2. Decrypt to a private temporary directory using the same parameters
    # used during encryption.  The plaintext never remains in the backup dir.
    local temp_dir
    temp_dir=$(mktemp -d)
    register_temp_dir "$temp_dir"
    local decrypted="$temp_dir/backup"

    if [[ "$backup_file" == *.enc ]]; then
        if ! openssl_decrypt "$backup_file" "$decrypted" 2>>"$LOG_FILE"; then
            log "错误: 解密失败，备份文件可能损坏或密钥不匹配"
            return 1
        fi
    else
        cp "$backup_file" "$decrypted"
    fi

    # 3. Recompute the checksum over the decrypted plaintext.  A missing or
    # malformed checksum is a hard failure, not a warning.
    local checksum_file="${backup_file}.sha256"
    if [ ! -f "$checksum_file" ]; then
        log "错误: 缺少校验和文件"
        return 1
    fi
    local expected actual
    expected=$(tr -d '[:space:]' < "$checksum_file")
    if [[ ! "$expected" =~ ^[[:xdigit:]]{64}$ ]]; then
        log "错误: 校验和文件格式无效"
        return 1
    fi
    actual=$(sha256sum "$decrypted" | awk '{print $1}')
    if [ "$expected" != "$actual" ]; then
        log "错误: 备份校验和不匹配"
        return 1
    fi

    log "备份解密和校验通过: $(basename "$backup_file")"

    return 0
}

verify_latest_backup() {
    local latest
    # Keep the check portable across the GNU/Linux production host and the
    # macOS development host; BSD find has no -printf.
    latest=$(ls -1t "$ENCRYPTED_DIR"/*.enc 2>/dev/null | head -1 || true)
    if [ -z "$latest" ]; then
        log "错误: 没有可验证的本地备份"
        return 1
    fi
    verify_backup "$latest"
}

# 列出备份
list_backups() {
    echo "=== 本地备份列表 ==="
    ls -lh "$ENCRYPTED_DIR"/*.enc 2>/dev/null || echo "无本地备份"
    
    echo ""
    echo "=== 本地备份统计 ==="
    local total_size=$(du -sh "$ENCRYPTED_DIR" 2>/dev/null | cut -f1)
    local file_count=$(ls -1 "$ENCRYPTED_DIR"/*.enc 2>/dev/null | wc -l)
    echo "总大小: $total_size"
    echo "文件数: $file_count"
    
    # 列出 COS 上的备份
    if [ "$REMOTE_TYPE" == "cos" ] && [ -n "$REMOTE_BUCKET" ]; then
        echo ""
        echo "=== COS 远程备份列表 ==="
        list_cos_backups
    fi
}



# 恢复备份 (交互式)
restore_backup() {
    local backup_file="$1"
    
    echo "=== 备份恢复 ==="
    echo "警告: 恢复操作将覆盖现有数据!"
    echo "备份文件: $backup_file"
    echo ""
    if [ "${RESTORE_CONFIRMATION:-}" = "RESTORE" ]; then
        confirm="RESTORE"
    else
        read -r -p "确定要继续吗? 输入 'RESTORE' 确认: " confirm
    fi
    
    if [ "$confirm" != "RESTORE" ]; then
        echo "已取消"
        return 1
    fi
    
    # 1. Verify before any restore-side effect, then decrypt into a private
    # temporary directory that is removed on every exit path.
    verify_backup "$backup_file"
    local temp_dir
    temp_dir=$(mktemp -d)
    register_temp_dir "$temp_dir"
    local decrypted="$temp_dir/backup"

    log "解密备份文件..."
    if [[ "$backup_file" == *.enc ]]; then
        openssl_decrypt "$backup_file" "$decrypted"
    else
        cp "$backup_file" "$decrypted"
    fi
    
    # 2. 恢复数据库
    if [[ "$backup_file" == *.sql.enc || "$backup_file" == *.sql ]]; then
        log "恢复数据库..."
        validate_postgres_container
        # Restore only through the controlled Docker PostgreSQL container.  No
        # PM2, host postgres service, sudo, or uncontrolled production socket.
        cat "$decrypted" | docker exec -i "$POSTGRES_CONTAINER" pg_restore \
            --username="$DB_USER" \
            --dbname="$DB_NAME" \
            --clean \
            --if-exists \
            --no-owner \
            --exit-on-error \
            -
    fi
    
    # 清理
    log "恢复完成"
}

# 主函数
main() {
    init
    
    case "${1:-full}" in
        full)
            full_backup
            ;;
        incremental)
            incremental_backup
            ;;
        verify)
            [ "$#" -ge 2 ] || { echo "verify 需要备份文件路径" >&2; exit 1; }
            verify_backup "$2"
            ;;
        verify-latest)
            verify_latest_backup
            ;;
        list)
            list_backups
            ;;
        restore)
            [ "$#" -ge 2 ] || { echo "restore 需要备份文件路径" >&2; exit 1; }
            restore_backup "$2"
            ;;
        cleanup)
            cleanup_old_backups
            ;;
        setup-cron)
            # 设置定时任务
            # 每天凌晨2点全量备份
            (crontab -l 2>/dev/null; echo "0 2 * * * $SCRIPT_DIR/backup-enhanced.sh full >> /var/log/ptool/monitoring/backup-cron.log 2>&1") | crontab -
            # Incremental WAL tar is intentionally not scheduled.  Verify the
            # newest encrypted full backup once a week instead.
            (crontab -l 2>/dev/null; echo "0 4 * * 0 $SCRIPT_DIR/backup-enhanced.sh verify-latest >> /var/log/ptool/monitoring/backup-verify-cron.log 2>&1") | crontab -
            log "已设置全量备份和每周校验定时任务"
            ;;
        *)
            echo "用法: $0 [full|verify <file>|verify-latest|list|restore <file>|cleanup|setup-cron]"
            exit 1
            ;;
    esac
}

main "$@"
