import { describe,it,expect } from 'vitest'
import { canonicalHash } from '../../modules/assessment-runtime/canonical'
import { LINK_CONSENT_VERSION,assertStudentConfirmation,assertExactReportBinding,parseParentProjection } from '../../modules/parent-portal/contracts'
const policy={key:'parent-summary-v1',version:'1',audience:'PARENT' as const,mode:'EDUCATIONAL_SUMMARY' as const,rawAnswers:false as const,itemLevel:false as const,researchExport:false as const}
const projection=()=>({schemaVersion:1,audience:'PARENT',artifactId:'artifact',subjectUserId:'child',title:'家长摘要',publicationStatus:'PUBLISHED',policy,policyHash:canonicalHash(policy),summary:'后端 canonical 说明',blocks:[]})
describe('parent canonical disclosure contract',()=>{
 it('accepts only explicit published parent audience and exact subject/artifact',()=>{expect(parseParentProjection(projection(),'artifact','child').summary).toBe('后端 canonical 说明');expect(()=>parseParentProjection(projection(),'other','child')).toThrow();expect(()=>parseParentProjection(projection(),'artifact','other')).toThrow()})
 it.each([{audience:'TEACHER'},{publicationStatus:'DRAFT'},{rawAnswers:['secret']},{policyHash:'0'.repeat(64)},{blocks:[{title:'raw',text:'value',itemAnswers:['secret']}]}])('rejects nonparent or extra raw fields %j',patch=>{expect(()=>parseParentProjection({...projection(),...patch},'artifact','child')).toThrow()})
 it('completion-only never carries scientific interpretations',()=>{const p={...policy,mode:'COMPLETION_ONLY' as const};expect(()=>parseParentProjection({...projection(),policy:p,policyHash:canonicalHash(p)},'artifact','child')).toThrow();expect(parseParentProjection({...projection(),policy:p,policyHash:canonicalHash(p),summary:''},'artifact','child').policy.mode).toBe('COMPLETION_ONLY')})
 it('student confirmation is a distinct flow, never implicit teacher/admin approval',()=>{expect(()=>assertStudentConfirmation({actorUserId:'child',studentUserId:'child',status:'PENDING',consentVersion:LINK_CONSENT_VERSION})).not.toThrow();expect(()=>assertStudentConfirmation({actorUserId:'admin',studentUserId:'child',status:'PENDING',consentVersion:LINK_CONSENT_VERSION})).toThrow();expect(()=>assertStudentConfirmation({actorUserId:'child',studentUserId:'child',status:'REVOKED',consentVersion:LINK_CONSENT_VERSION})).toThrow()})
 it.each(['parentUserId','studentUserId','relationshipId','sourceArtifactId'] as const)('exact report grant cannot substitute %s',key=>{const grant={parentUserId:'parent',studentUserId:'child',relationshipId:'link',sourceArtifactId:'artifact'};expect(()=>assertExactReportBinding({parentUserId:'parent',studentUserId:'child',relationshipId:'link',artifactId:'artifact'},{...grant,[key]:'other'})).toThrow()})
})
