import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowUpRight, Building2 } from 'lucide-react'
import { organizationApi, type OrganizationListProjection } from '../../api/organizations'
import { PageHeader, ProductButton, ProductPage, ProductStatus } from '../../components/product-ui'
export function OrganizationIndexPage(){
  const [page,setPage]=useState(1),[revision,setRevision]=useState(0),[projection,setProjection]=useState<OrganizationListProjection|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
  useEffect(()=>{let cancelled=false;setLoading(true);setError('');void organizationApi.list(page,24).then(v=>{if(!cancelled)setProjection(v)}).catch(v=>{if(!cancelled)setError(v instanceof Error?v.message:'无法读取组织列表')}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[page,revision])
  return <ProductPage width="management"><PageHeader title="组织空间" description="选择学校或组织，管理成员、测评批次和报告。可用操作以当前组织权限为准。" actions={projection?.allowedActions.includes('CREATE_ORGANIZATION')?<Link className="staff-primary-link" to="/organizations/new">创建组织</Link>:undefined}/><div className="staff-toolbar"><span className="staff-help">{projection?`共 ${projection.total} 个可访问组织`:'组织目录'}</span><ProductButton disabled={loading} onClick={()=>setRevision(v=>v+1)}>刷新列表</ProductButton></div>
  {error?<ProductStatus kind="error" title="组织列表加载失败" actions={<ProductButton onClick={()=>setRevision(v=>v+1)}>重新加载</ProductButton>}>{error}</ProductStatus>:loading?<ProductStatus kind="pending" title="正在加载组织">正在确认可访问的组织范围。</ProductStatus>:!projection?.list.length?<ProductStatus kind="info" title="暂无可访问组织" actions={<Link className="staff-secondary-link" to="/organization-tasks">组织测评任务</Link>}>请联系平台或组织管理员添加成员关系。已分配给您的测评可从组织测评任务进入。</ProductStatus>:<div className="staff-card-grid">{projection.list.map(o=><article key={o.id} className="staff-catalog-card"><Building2 size={26} aria-hidden="true"/><h2><Link to={`/organizations/${encodeURIComponent(o.id)}`}>{o.name}</Link></h2><p>{o.status==='ACTIVE'?'运行中':'已暂停'} · {o.orgRole||'平台管理范围'}</p><Link className="staff-secondary-link" to={`/organizations/${encodeURIComponent(o.id)}`}>进入组织 <ArrowUpRight size={16} aria-hidden="true"/></Link></article>)}</div>}
  {projection&&projection.total>projection.pageSize&&<nav className="staff-pagination" aria-label="组织列表分页"><ProductButton disabled={loading||page<=1} onClick={()=>setPage(v=>v-1)}>上一页</ProductButton><span>第 {page} / {Math.max(1,Math.ceil(projection.total/projection.pageSize))} 页</span><ProductButton disabled={loading||page*projection.pageSize>=projection.total} onClick={()=>setPage(v=>v+1)}>下一页</ProductButton></nav>}</ProductPage>
}
export function OrganizationNotFound(){const {organizationId}=useParams<{organizationId:string}>();return <ProductPage width="management"><ProductStatus kind="warning" title="找不到此组织页面" actions={<><Link to="/organizations">返回组织列表</Link>{organizationId&&<> · <Link to={`/organizations/${encodeURIComponent(organizationId)}`}>返回组织概览</Link></>}</>}>页面地址可能不完整或已经变更。请通过导航进入测评批次、报告分析或安全事项与导出。</ProductStatus></ProductPage>}
