import './organization-ui.css'
import { useEffect, useState } from 'react'
import { Link, Navigate, Route, Routes, useLocation } from 'react-router-dom'
import { useAuth } from '../../contexts/AuthContext'
import { useOrganization } from '../../contexts/OrganizationContext'
import { ProductButton, ProductPage, ProductStatus } from '../../components/product-ui'
import { RouteLoading } from '../../components/app-shell/RouteAccess'
import OrganizationCreatePage from './OrganizationCreatePage'
import MyAssessments from '../MyAssessments'
import OrganizationAdminPage from './OrganizationAdminPage'
import OrganizationRunListPage from './OrganizationRunListPage'
import OrganizationRunDetailPage from './OrganizationRunDetailPage'
import OrganizationReportingPage from './OrganizationReportingPage'
import OrganizationDeliveryPage from './OrganizationDeliveryPage'
import { OrganizationIndexPage, OrganizationNotFound } from './OrganizationIndexPage'
function Boundary({children,organizationId}:{children:React.ReactNode;organizationId:string}){const {user}=useAuth();const {active,selectOrganization}=useOrganization();const context=active?.organization.id===organizationId?active:null;const key=`${user?.id||''}:${organizationId}`;const [state,setState]=useState<{key:string;failed:boolean}|null>(null);useEffect(()=>{if(!user||!organizationId||context)return;let cancelled=false;setState({key,failed:false});void selectOrganization(organizationId).then(v=>{if(!cancelled)setState({key,failed:v?.organization.id!==organizationId})}).catch(()=>{if(!cancelled)setState({key,failed:true})});return()=>{cancelled=true}},[user?.id,organizationId,context,key,selectOrganization]);if(context)return <>{children}</>;const failed=state?.key===key&&state.failed;return <ProductPage width="management"><ProductStatus kind={failed?'error':'pending'} title={failed?'无法进入组织空间':'正在确认组织访问权限'} actions={failed?<><ProductButton onClick={()=>void selectOrganization(organizationId)}>重新加载</ProductButton> <Link to="/organizations">返回组织列表</Link></>:undefined}>{failed?'组织不存在，或当前账户没有访问权限。请返回组织列表选择可访问的组织。':'正在读取当前组织的可用工作区。'}</ProductStatus></ProductPage>}
function Nested(){const location=useLocation(),organizationId=location.pathname.split('/')[2]||'';return <Boundary organizationId={organizationId}><Routes><Route path="/organizations/:organizationId" element={<OrganizationAdminPage/>}/><Route path="/organizations/:organizationId/runs" element={<OrganizationRunListPage/>}/><Route path="/organizations/:organizationId/runs/:runId" element={<OrganizationRunDetailPage/>}/><Route path="/organizations/:organizationId/reporting" element={<OrganizationReportingPage/>}/><Route path="/organizations/:organizationId/delivery" element={<OrganizationDeliveryPage/>}/><Route path="/organizations/:organizationId/*" element={<OrganizationNotFound/>}/></Routes></Boundary>}
export default function OrganizationProductRoutes(){const {user,isLoading}=useAuth(),location=useLocation();if(isLoading)return <RouteLoading/>;if(!user)return <ProductPage width="management"><ProductStatus kind="warning" title="需要登录" actions={<Link to="/">返回登录入口</Link>}>组织工作区只接受当前已认证会话，具体组织权限由服务器实时验证。</ProductStatus></ProductPage>;if(location.pathname==='/organizations')return <OrganizationIndexPage/>;if(location.pathname==='/organizations/new')return <OrganizationCreatePage/>;if(location.pathname==='/organization-tasks')return <Navigate to="/my-assessments" replace/>;if(location.pathname==='/my-assessments')return <MyAssessments key={user.id}/>;if(location.pathname.startsWith('/organizations/'))return <Nested/>;return <OrganizationNotFound/>}
