Page({
 data:{status:'loading',title:'公开打卡',navItems:[],content:'',images:[],errorMessage:'',formError:'',submitted:false},
 onLoad(options){this.token=options.token;this.sequence=0;this.context=null;this.images=[];this.local=[];this.sealed=null;this.picking=false;this.retryAt=0},
 onShow(){if(!this.context&&!this.data.submitted)this.load()},
 onHide(){if(!this.picking)this.clear()},onUnload(){this.clear()},
 clear(){this.sequence+=1;getApp().runtime.publicCheckins.discard(this.local);this.context=null;this.images=[];this.local=[];this.sealed=null;this.setData({content:'',images:[],publishedImages:[],body:'',formError:''})},
 async load(){const sequence=++this.sequence;this.setData({status:'loading',errorMessage:''});try{const service=getApp().runtime.publicCheckins,context=await service.open(this.token);if(sequence!==this.sequence)return;const local=await service.media(context,context.checkin.images||[]);if(sequence!==this.sequence){service.discard(local);return}this.context=context;this.local=local;this.images=[];this.sealed=null;this.setData({status:'ready',title:context.checkin.title,body:context.checkin.content||context.checkin.description||'',publishedImages:local,images:[],content:'',submitted:false})}catch(error){if(sequence===this.sequence)this.setData({status:'error',errorMessage:error.message})}},
 retry(){return this.load()},change(e){if(!this.sealed&&this.data.status!=='submitting')this.setData({content:e.detail.value})},
 async upload(){if(!this.context||this.sealed||this.data.status==='submitting'||this.images.length>=9||this.picking)return;const sequence=this.sequence;this.picking=true;try{const files=await getApp().runtime.media.chooseImages(9-this.images.length,()=>sequence===this.sequence&&Boolean(this.context)&&!this.sealed);if(sequence!==this.sequence)return;this.setData({status:'submitting'});for(const file of files){const image=await getApp().runtime.publicCheckins.upload(this.context,file.tempFilePath);if(sequence!==this.sequence)return;this.images.push(image)}this.setData({status:'ready',images:this.images})}catch(error){if(sequence===this.sequence&&error.kind!=='cancelled')this.setData({status:'ready',formError:error.message||'未选择图片'})}finally{this.picking=false}},
 remove(e){if(this.sealed||this.data.status==='submitting')return;this.images=this.images.filter((_,i)=>i!==Number(e.currentTarget.dataset.index));this.setData({images:this.images})},
 async submit(){if(!this.context||this.data.status==='submitting'||this.data.submitted||Date.now()<this.retryAt)return;const sequence=this.sequence;if(!this.sealed)this.sealed={content:this.data.content,images:this.images.slice()};this.setData({status:'submitting',formError:''});try{await getApp().runtime.publicCheckins.submit(this.context,this.sealed.content,this.sealed.images);if(sequence!==this.sequence)return;this.context=null;this.images=[];this.sealed=null;getApp().runtime.publicCheckins.discard(this.local);this.local=[];this.setData({status:'ready',submitted:true,content:'',body:'',images:[],publishedImages:[]})}catch(error){if(sequence===this.sequence){if(error.retryAfterMs)this.retryAt=Date.now()+error.retryAfterMs;if(error.status>=400&&error.status<500&&error.status!==429||error.kind==='invalidRequest')this.sealed=null;this.setData({status:'ready',formError:error.message+(error.status===429?'。请等待 '+Math.ceil((error.retryAfterMs||0)/1000)+' 秒后重试原提交。':!error.status?'。服务器结果未知，请保留原内容重试确认。':'')})}}},
 home(){wx.reLaunch({url:'/pages/entry/index'})},
})
