const {workspacePage}=require('../../app/pages/index')
Page(workspacePage({
 setup(o){this.organizationId=o.organizationId;this.preview=null;this.artifactId=null;this.consentRows=[]},
 reset(){this.preview=null;this.artifactId=null;this.consentRows=[];this.setData({preview:null,blocks:[],consents:[],notice:'',actionError:''})},
 async fetch(runtime){this.preview=null;this.artifactId=null;this.consentRows=[];return {...await runtime.parentPublications.list(this.organizationId),preview:null,blocks:[],consents:[],notice:'选取报告后先核对家长专用内容。发布后，仍需学生逐份同意和独立披露授权。首期正式模板只披露报告已生成。'}},
 methods:{
 async act(operation){if(this.data.status==='submitting')return;const sequence=this.sequence;this.setData({status:'submitting',actionError:''});try{const result=await operation(getApp().runtime.parentPublications);if(sequence===this.sequence)this.setData({status:'ready',...result})}catch(e){if(sequence!==this.sequence)return;this.setData({status:'ready',actionError:e.message+(e.status?'':'。确认结果未知；可用相同命令明确重试。')});if([401,403,404,409].includes(e.status)){this.preview=null;this.consentRows=[];this.setData({preview:null,blocks:[],consents:[]})}}},
 select(e){if(!this.data.list?.some(r=>r.id===e.detail.id))return;const sequence=this.sequence;return this.act(async service=>{const preview=await service.preview(e.detail.id);if(sequence!==this.sequence)return {};this.preview=preview;this.artifactId=preview.artifactId;return {preview:preview.projection,blocks:preview.projection.blocks.map((b,i)=>({...b,key:String(i)})),consents:[],notice:'请核对以下内容。发布不会自动给家长开放报告。'}})},
 async publish(){if(!this.preview||this.data.status==='submitting')return;const sequence=this.sequence,preview=this.preview;const answer=await new Promise(resolve=>wx.showModal({title:'发布家长版报告',content:'将创建本次内容的独立发布版本；已有同意和授权不会转到新版本。确认发布？',success:resolve,fail:()=>resolve({confirm:false})}));if(!answer.confirm||sequence!==this.sequence||this.preview!==preview)return;return this.act(async service=>{await service.publish(preview);return {notice:'服务器已确认发布。学生可在家长关联中预览并逐份同意；此处仍需完成披露授权。'}})},
 consents(){if(!this.artifactId)return;const sequence=this.sequence;return this.act(async service=>{const raw=await service.consents(this.artifactId);if(sequence!==this.sequence)return {};this.consentRows=raw.list;return {consents:raw.list.map(r=>({id:r.id,title:r.parentName,canOpen:r.allowedActions.includes('GRANT')})),notice:raw.list.length?'选择已经同意的接收家长，再核对授权。':'尚无当前版本的有效学生同意。'}})},
 async grant(e){const row=this.consentRows.find(r=>r.id===e.detail.id);if(!row||this.data.status==='submitting')return;const sequence=this.sequence,artifactId=this.artifactId;const answer=await new Promise(resolve=>wx.showModal({title:'授权本份家长报告',content:'确认向 '+row.parentName+' 开放这一份学生已经同意的家长报告？不包含原始作答和其他报告。',success:resolve,fail:()=>resolve({confirm:false})}));if(!answer.confirm||sequence!==this.sequence||artifactId!==this.artifactId||!this.consentRows.includes(row))return;return this.act(async service=>{await service.grant(artifactId,row);return {notice:'服务器已确认逐份披露授权。家长可查看获准的当前版本。'}})},
 onHide(){this.sequence++;this.preview=null;this.artifactId=null;this.consentRows=[];this.setData({preview:null,blocks:[],consents:[]})},
 }}))
