const { ApiError } = require('../../core/errors/index')
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k)
function options(raw){if(raw==null)return [];if(typeof raw==='string'){try{raw=JSON.parse(raw)}catch(_){throw new ApiError('unsupportedRenderer','选项定义不能验证')}}if(!Array.isArray(raw))throw new ApiError('unsupportedRenderer','选项格式尚未适配');return raw.map(o=>({value:typeof o==='string'?o:o.value,label:typeof o==='string'?o:o.label}))}
function scaleItems(definition){if(!definition||definition.schemaVersion!==2||!Array.isArray(definition.items))throw new ApiError('unsupportedRenderer','量表不是受支持的冻结定义');if(definition.display&&definition.display.randomizeItems)throw new ApiError('unsupportedRenderer','随机呈现使用正式网页测评');return definition.items.map(i=>({key:i.itemCode,label:i.content,type:'single_choice',required:i.required!==false,options:options(i.options),media:i.images,video:i.video,randomize:i.randomizeOptions,source:i}))}
function formItems(section){if(!section||!Array.isArray(section.items))throw new ApiError('unsupportedRenderer','表单定义不完整');return section.items.map(i=>({key:i.formItemId||i.id,label:i.label,type:i.type,required:i.required===true,options:options(i.options),initial:i.value,source:i}))}
function situationalItems(instrument){const d=instrument&&instrument.definition;if(instrument?.assignment||!d||d.schemaVersion!==1||!Array.isArray(d.scenes)||d.sampling?.strategy!=='ALL'||d.scenes.some(s=>s.channels.some(c=>c.responseType==='CONTINUOUS')))throw new ApiError('unsupportedRenderer','此情境使用正式网页测评');return d.scenes.flatMap(scene=>scene.channels.map(c=>({key:scene.sceneKey+':'+c.channelKey,label:c.prompt,scenarioTitle:scene.title,scenarioText:scene.stimulus&&scene.stimulus.text,type:{SINGLE_CHOICE:'single_choice',CONTINUOUS:'numeric',FREE_TEXT:'text_input'}[c.responseType],required:c.required!==false,options:(c.options||[]).map(o=>({value:o.optionKey,label:o.label})),range:c.range,maxLength:c.maxLength,stimulus:scene.stimulus,sceneKey:scene.sceneKey,channelKey:c.channelKey,source:c})))}
function supported(items){return items.length>0&&items.every(i=>typeof i.key==='string'&&i.key.length>0&&!['__proto__','constructor','prototype'].includes(i.key)&&['single_choice','multiple_choice','fill_blank','text_input','numeric','number','year_month'].includes(i.type)&&!i.video&&!(i.media&&i.media.length)&&!i.randomize&&(!i.stimulus||i.stimulus.type==='TEXT_V1')&&i.options.every(o=>o.value!==undefined&&typeof o.label==='string'&&!o.images&&!o.video)&&!(i.source.options&&Array.isArray(i.source.options)&&i.source.options.some(o=>o&&typeof o==='object'&&(o.images||o.video))))&&new Set(items.map(i=>i.key)).size===items.length}
function validate(items,values){const normalized={};for(const i of items){const v=values[i.key],empty=v===undefined||v===null||v===''||(Array.isArray(v)&&!v.length);if(empty){if(i.required)throw new ApiError('invalidRequest','请完成：'+i.label);continue}if(['single_choice','multiple_choice'].includes(i.type)){const choices=i.type==='multiple_choice'?v:[v];if(!Array.isArray(choices)||new Set(choices).size!==choices.length||choices.some(c=>!i.options.some(o=>typeof o.value===typeof c&&o.value===c)))throw new ApiError('invalidRequest','请核对：'+i.label)}else if(i.type==='numeric'||i.type==='number'){if(typeof v!=='number'||!Number.isFinite(v)||(i.range&&(v<i.range.min||v>i.range.max)))throw new ApiError('invalidRequest','数值不符合题目要求：'+i.label)}else if(typeof v!=='string'||v.length>(i.maxLength||10000)||(i.type==='year_month'&&!/^\d{4}-(0[1-9]|1[0-2])$/.test(v)))throw new ApiError('invalidRequest','填写格式不符合要求：'+i.label);Object.defineProperty(normalized,i.key,{value:v,enumerable:true})}return normalized}
function view(items,values,index,locked){const item=items[index];if(!item)return null;const v=values[item.key];return {key:item.key,label:item.label,scenarioTitle:item.scenarioTitle||'',scenarioText:item.scenarioText||'',type:item.type,required:item.required,choices:item.options.map((o,n)=>({value:String(n),label:o.label})),choiceValue:item.type==='multiple_choice'?(Array.isArray(v)?v:[]).map(c=>String(item.options.findIndex(o=>typeof o.value===typeof c&&o.value===c))):String(item.options.findIndex(o=>typeof o.value===typeof v&&o.value===v)),value:v===undefined?'':v,multiple:item.type==='multiple_choice',isChoice:['single_choice','multiple_choice'].includes(item.type),numeric:['numeric','number'].includes(item.type),position:index+1,total:items.length,locked}}
function fromInput(item,eventValue){if(item.type==='single_choice'){const option=item.options[Number(eventValue)];if(!option)throw new ApiError('invalidRequest','请选择选项');return option.value}if(item.type==='multiple_choice'){if(!Array.isArray(eventValue))throw new ApiError('invalidRequest','多选输入无效');return eventValue.map(n=>{const option=item.options[Number(n)];if(!option)throw new ApiError('invalidRequest','请选择选项');return option.value})}if(['numeric','number'].includes(item.type))return eventValue===''?'':Number(eventValue);return String(eventValue)}
module.exports={scaleItems,formItems,situationalItems,supported,validate,view,fromInput,own}
