const {test}=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{createRequire}=require('node:module')
const {platform,response,csrf,session,user}=require('./helpers.cjs')
const {createRuntime}=require('../app/bootstrap/index')
const {createAssessmentService}=require('../domains/assessments/service')
const {createReportService,scaleBlocks,collectionBlocks}=require('../domains/assessments/reports')
const {normalize}=require('../domains/assessments/contracts')
const web=require('../domains/assessments/web-runtime')
const {parseEntry,resolveEntry}=require('../app/entry/index')
const origin='https://acceptance.example',hash='a'.repeat(64),other='b'.repeat(64)
const definition={schemaVersion:2,items:[{itemCode:'I1',content:'第一题',options:[{value:1,label:'是'},{value:'1',label:'否'}]},{itemCode:'I2',content:'第二题',options:[{value:0,label:'否'},{value:2,label:'是'}]}]}
function scale(epoch=1,status='IN_PROGRESS'){return {assessment:{id:'attempt-1',deliveryMode:'FINAL_ONLY',attemptEpoch:epoch,definitionHash:hash,contextSnapshotHash:null,status},scale:{id:'tool-1',name:'冻结量表',definition,definitionHash:hash}}}
function questionnaire(section='section-1',epoch=1){return {questionnaireAssessment:{id:'attempt-1',status:'IN_PROGRESS',deliveryMode:'FINAL_ONLY',attemptEpoch:epoch},contextSnapshotHash:null,currentFormSection:{id:section,definitionHash:hash,items:[{formItemId:'form-1',type:'multiple_choice',label:'背景',required:true,options:[{value:'a',label:'甲'},{value:'b',label:'乙'}]}]}}}
async function setup(handler=()=>undefined){let account=user(),raw=scale();account.mobile.capabilities.canUseAssessmentRuntime=true
 const p=platform(async o=>{const route=o.url.slice((origin+'/api').length);if(route==='/auth/csrf')return csrf();if(route==='/auth/login')return response({user:account},200,session());if(route==='/auth/me')return response(account);if(route==='/capabilities')return response({cognitive:false});if(route==='/auth/logout')return response(null,200,['ptool_session=; Max-Age=0']);const custom=await handler(o,route);if(custom!==undefined)return custom;if(route==='/mobile/assessment-runtime/scales/attempt-1'||route==='/questionnaires/assessments/attempt-1')return response(raw);throw new Error('unexpected '+route)})
 const create=()=>{const r=createRuntime(p,origin);r.assessments=createAssessmentService(r.api,r.session,r.drafts,r.config);r.reports=createReportService(r.api,r.session);return r}
 const runtime=create();await runtime.session.login({username:'test',password:'secret123'});return {runtime,p,create,setRaw(v){raw=v},setAccount(v){account=v}}
}
const handle={family:'SCALE',rootId:'attempt-1',resourceId:'tool-1',webTarget:'/student/scales/tool-1'}
async function filled(app){const unit=await app.runtime.assessments.resume(handle);await Promise.all([app.runtime.assessments.change(unit,'I1','0'),app.runtime.assessments.change(unit,'I2','1')]);return unit}
function loadPage(name,app,t){const file=path.resolve(__dirname,'../pages/'+name+'/index.js');let spec;const old={wx:global.wx,getApp:global.getApp};global.wx=app.p;global.getApp=()=>({runtime:app.runtime,ready:Promise.resolve()});t.after(()=>Object.assign(global,old));vm.runInNewContext(fs.readFileSync(file,'utf8'),{require:createRequire(file),wx:app.p,getApp:global.getApp,Page:s=>{spec=s},Promise});return {...spec,data:structuredClone(spec.data),setData(v){Object.assign(this.data,v)}}}
test('encrypted draft survives process rebuild and retains numeric/string canonical option values',async()=>{const app=await setup(),unit=await filled(app);assert.deepEqual(unit.draft.values,{I1:1,I2:2});const rebuilt=app.create();await rebuilt.session.restore();const restored=await rebuilt.assessments.resume(handle);assert.deepEqual(restored.draft.values,unit.draft.values);assert.equal(restored.draft.commandId,unit.draft.commandId);assert.ok([...app.p.stored.keys()].every(k=>k.startsWith('huisurvey:v2:')));assert.equal(app.p.calls.filter(c=>c.method==='POST'&&c.url.includes('/submit')).length,0)})
test('rapid same-question input persists newest value without losing another question',async()=>{const app=await setup(),unit=await app.runtime.assessments.resume(handle);await Promise.all([app.runtime.assessments.change(unit,'I1','0'),app.runtime.assessments.change(unit,'I1','1'),app.runtime.assessments.change(unit,'I2','0')]);const r=await app.runtime.assessments.resume(handle);assert.deepEqual(r.draft.values,{I1:'1',I2:0})})
test('lost server receipt rebuilds sealed exact payload, including provenance, and coalesces retry',async()=>{const posts=[];let fail=true;const app=await setup((o,route)=>{if(route.endsWith('/submit')){posts.push(structuredClone(o.data));if(fail){fail=false;throw new Error('lost response')}return response({status:'COMPLETED'})}});let unit=await filled(app);await assert.rejects(app.runtime.assessments.submit(unit),{kind:'network'});assert.equal(unit.draft.state,'sealed');await assert.rejects(app.runtime.assessments.change(unit,'I1','1'),{kind:'sealed'});app.setRaw(scale(1,'COMPLETED'));const rebuilt=app.create();await rebuilt.session.restore();unit=await rebuilt.assessments.resume(handle);assert.equal(unit.recovery,true);assert.equal(unit.state,'recoverable');await Promise.all([rebuilt.assessments.submit(unit),rebuilt.assessments.submit(unit)]);assert.equal(posts.length,2);assert.deepEqual(posts[0],posts[1]);assert.equal((await rebuilt.assessments.resume(handle)).state,'submitted')})
test('questionnaire advanced unit restores previous sealed command and canonical previous submit path',async()=>{const posts=[];let fail=true;const app=await setup((o,route)=>{if(route.endsWith('/submit')){posts.push({route,data:structuredClone(o.data)});if(fail){fail=false;throw new Error('lost')}return response({status:'COMPLETED'})}});app.setRaw(questionnaire());const h={family:'QUESTIONNAIRE',rootId:'attempt-1',resourceId:'questionnaire-1'},unit=await app.runtime.assessments.resume(h);await app.runtime.assessments.change(unit,'form-1',['0','1']);await assert.rejects(app.runtime.assessments.submit(unit));app.setRaw(questionnaire('section-2'));const r=app.create();await r.session.restore();const pending=await r.assessments.resume(h);assert.equal(pending.recovery,true);assert.equal(pending.items.length,0);await r.assessments.submit(pending);assert.deepEqual(posts[0],posts[1]);assert.match(posts[1].route,/form-sections\/section-1\/submit$/);assert.equal((await r.assessments.resume(h)).unitId,'section-2')})
test('storage failure prevents FINAL network write and failed edit can explicitly persist again',async()=>{const app=await setup(),unit=await app.runtime.assessments.resume(handle);const set=app.p.setStorage;app.p.setStorage=o=>queueMicrotask(()=>o.fail({errMsg:'quota exceeded'}));await assert.rejects(app.runtime.assessments.change(unit,'I1','0'),{kind:'storageUnavailable'});await assert.rejects(app.runtime.assessments.submit(unit));assert.equal(app.p.calls.filter(c=>c.url.endsWith('/submit')).length,0);app.p.setStorage=set;await app.runtime.assessments.savePending(unit);assert.equal(unit.draft.values.I1,1)})
test('storage failure while sealing sends no request and keeps editable draft',async()=>{const app=await setup(),unit=await filled(app);app.p.setStorage=o=>queueMicrotask(()=>o.fail({errMsg:'quota exceeded'}));await assert.rejects(app.runtime.assessments.submit(unit),{kind:'storageUnavailable'});assert.equal(unit.draft.state,'draft');assert.equal(app.p.calls.filter(c=>c.url.endsWith('/submit')).length,0)})
test('429 interval blocks premature replay and exact sealed body survives permitted retry',async()=>{let posts=0;const app=await setup((o,route)=>{if(route.endsWith('/submit')){posts++;return posts===1?response(null,429,[],{'Retry-After':'1'}):response({status:'COMPLETED'})}}),unit=await filled(app);await assert.rejects(app.runtime.assessments.submit(unit),{status:429});await assert.rejects(app.runtime.assessments.submit(unit),{kind:'rateLimited'});assert.equal(posts,1);unit.retryAt=Date.now()-1;await app.runtime.assessments.submit(unit);assert.equal(posts,2)})
test('409 locks sealed payload; fresh epoch requires explicit stale discard and cannot replay restart',async()=>{const app=await setup((o,route)=>route.endsWith('/submit')?response(null,409):undefined),unit=await filled(app);await assert.rejects(app.runtime.assessments.submit(unit),{status:409});assert.equal(unit.state,'conflict');app.setRaw(scale(2));await assert.rejects(app.runtime.assessments.restart(unit),{kind:'conflict'});assert.equal(app.p.calls.filter(c=>c.url.endsWith('/restart')).length,0);await app.runtime.assessments.discardStale(unit);const next=await app.runtime.assessments.resume(handle);assert.equal(next.meta.attemptEpoch,2);assert.deepEqual(next.draft.values,{})})
test('unsealed stale definition cannot overwrite draft; discard requires server identity change',async()=>{const app=await setup(),old=await filled(app);await assert.rejects(app.runtime.drafts.discardStale(old.meta),{kind:'conflict'});app.setRaw({...scale(),assessment:{...scale().assessment,definitionHash:other},scale:{...scale().scale,definitionHash:other}});const conflict=await app.runtime.assessments.resume(handle);assert.equal(conflict.state,'draftConflict');await app.runtime.assessments.discardStale(conflict);assert.deepEqual((await app.runtime.assessments.resume(handle)).draft.values,{})})
test('logout purges private drafts; old owner identity cannot write after account change',async()=>{const app=await setup(),unit=await filled(app);await app.runtime.session.logout();assert.equal(app.p.stored.size,0);await assert.rejects(app.runtime.drafts.save(unit.meta,unit.draft),{kind:'sessionChanged'});const otherUser=user('PARENT');otherUser.mobile.capabilities.canUseAssessmentRuntime=true;app.setAccount(otherUser);await app.runtime.session.login({username:'parent',password:'secret123'});await assert.rejects(app.runtime.drafts.open(unit.meta),{kind:'sessionChanged'});assert.deepEqual((await app.runtime.assessments.resume(handle)).draft.values,{})})
test('disabled runtime capability prevents start and resume before transport',async()=>{const app=await setup();const disabled=user();disabled.mobile.capabilities.canUseAssessmentRuntime=false;app.setAccount(disabled);await app.runtime.session.refresh();const before=app.p.calls.length;await assert.rejects(app.runtime.assessments.begin({family:'SCALE',resourceId:'tool-1'}),{kind:'capabilityMismatch'});await assert.rejects(app.runtime.assessments.resume(handle),{kind:'capabilityMismatch'});assert.equal(app.p.calls.length,before)})
test('actual runner hides private answers and late read cannot restore unit after background',async t=>{let release,delayed=false;const app=await setup((o,route)=>delayed&&route.includes('/assessment-runtime/')?new Promise(resolve=>{release=()=>resolve(response(scale()))}):undefined);delayed=true;const page=loadPage('runner',app,t);page.onLoad(handle);const pending=page.onShow();await new Promise(resolve=>setImmediate(resolve));page.onHide();release();await pending;assert.equal(page.unit,null);assert.equal(page.data.item,null);assert.equal(page.data.canSubmit,false);page.onUnload()})
test('actual runner cannot double-submit; logout suppresses a late confirmation',async t=>{let release;const app=await setup((o,route)=>route.endsWith('/submit')?new Promise(resolve=>{release=()=>resolve(response({status:'COMPLETED'}))}):undefined);const page=loadPage('runner',app,t);page.onLoad(handle);await page.onShow();await page.change({detail:{value:'0'}});page.next();await page.change({detail:{value:'1'}});const pending=page.submit();await page.submit();await new Promise(resolve=>setImmediate(resolve));assert.equal(app.p.calls.filter(c=>c.url.endsWith('/submit')).length,1);await app.runtime.session.logout();release();await pending;assert.equal(page.data.item,null);assert.equal(page.unit,null);assert.equal(app.p.stored.size,0);page.onUnload()})
test('FINAL composite requires current unit hash; context hashes are not inferred from parent definition',()=>{assert.throws(()=>normalize('COMPOSITE',{id:'a',deliveryMode:'FINAL_ONLY',attemptEpoch:1,status:'IN_PROGRESS',definitionHash:hash,currentItem:{type:'SCALE',id:'i',scale:{definition}}},'u','r'),{kind:'definitionMismatch'})})
test('unsupported media, randomization, SJT research and continuous presentation use canonical Web',()=>{for(const d of [{...definition,display:{randomizeItems:true}},{...definition,items:[{...definition.items[0],images:['asset']}]},{...definition,items:[{...definition.items[0],options:[{value:1,label:'是',images:['asset']}]}]}])assert.throws(()=>normalize('SCALE',{...scale(),scale:{...scale().scale,definition:d}},'u','r'),{kind:'unsupportedRenderer'});const raw={attempt:scale().assessment,instrument:{assignment:{assignmentIdentity:'x'},definition:{schemaVersion:1,sampling:{strategy:'ALL'},scenes:[]}}};assert.throws(()=>normalize('SITUATIONAL',raw,'u','r'),{kind:'unsupportedRenderer'})})
test('reports respect explicit completion/unavailable and never fall back to raw result',async()=>{assert.deepEqual(scaleBlocks({kind:'completion',scores:[{label:'SECRET',value:99}],itemScores:[{responseValue:'secret'}]}).map(b=>b.text),['当前披露策略仅开放完成情况。']);assert.throws(()=>scaleBlocks(null),{kind:'unsupportedRenderer'});assert.throws(()=>collectionBlocks({packageReport:{},unitReports:[]}),{kind:'unsupportedRenderer'});const s=createReportService({get:async()=>({report:{kind:'completion'},result:{scores:[{label:'SECRET',value:99}]}})},{get:()=>({user:{id:'u'},capabilities:{canReadOwnAssessments:true}})});assert.ok(!JSON.stringify(await s.read('SCALE','attempt-1')).includes('SECRET'))})
test('public and anonymous canonical QR adapters preserve formal route without forcing native login',async()=>{for(const target of ['/public/questionnaire/abcdefghijklmnop','/public/composite/abcdefghijklmnop','/public/studies/study-1','/public/studies/waves/wave-1/abcdefghijklmnop','/public/cognitive/assignments/abcdefghijklmnop']){const entry=parseEntry({q:encodeURIComponent(origin+target)},origin),resolved=await resolveEntry(entry,{user:null},{ });assert.equal(resolved.destination,'/pages/web-runtime/index?path='+encodeURIComponent(target))}})
test('Web runtime rejects foreign, token query, encoded traversal and fragments before rendering',()=>{for(const path of ['https://evil.example/student/scales/x','//evil.example','/student/scales/x?token=secret','/student/scales/%2e%2e','/student/scales/x#f','/student/scales/x\\y'])assert.throws(()=>web.url({origin},path),{kind:'invalidEntry'});assert.equal(web.url({origin},'/student/scales/tool-1'),origin+'/student/scales/tool-1')})

const {longitudinal,geometry}=require('../domains/assessments/longitudinal')
const {reportTarget}=require('../domains/assessments/reports')
test('collection renderer respects completion kind even when a unit contains forbidden numeric fields',()=>{const blocks=collectionBlocks({unitReports:[{type:'SCALE',kind:'scale',reportKind:'completion',scaleName:'测量',scores:[{label:'SECRET',value:999}]}]});assert.ok(blocks.some(b=>b.text.includes('仅开放完成情况')));assert.ok(!JSON.stringify(blocks).includes('SECRET'))})
test('longitudinal report preserves missing waves, exact server delta and reference versions',()=>{const dto={schemaVersion:1,kind:'MY_LONGITUDINAL',waves:[{ordinal:1,evidenceLevel:'PILOT',metrics:{score:{state:'present',value:1}}},{ordinal:2,evidenceLevel:'PILOT',metrics:{score:{state:'missing',value:99}}},{ordinal:3,evidenceLevel:'PILOT',metrics:{score:{state:'present',value:9}}}],comparisons:[{fromOrdinal:1,toOrdinal:3,metrics:{score:{comparability:'SAME_MEASUREMENT',delta:6}}}],referenceTrajectories:{metrics:{score:{unified:false,points:[{ordinal:1,referenceVersion:'v1'},{ordinal:3,referenceVersion:'v2',bandLabel:'服务器分段'}]}}},limitations:['服务器限制']};const report=longitudinal(dto),display=JSON.stringify(report);assert.ok(display.includes('未提供可用值'));assert.ok(display.includes('变化值：6'));assert.ok(!display.includes('变化值：8'));assert.ok(!display.includes('99'));assert.equal(geometry(report.series[0].points).points[1].y,null);assert.ok(display.includes('v1'));assert.ok(display.includes('v2'));assert.ok(display.includes('服务器限制'))})
test('run summary uses native authorized API and withholds injected metrics',async()=>{assert.equal(reportTarget('/my-assessments/results/execution-1').family,'RUN_SUMMARY');assert.throws(()=>web.path('/my-assessments/results/execution-1'),{kind:'invalidEntry'});const s=createReportService({get:async path=>{assert.equal(path,'/my-assessments/results/execution-1');return {schemaVersion:1,mode:'NONE',state:'WITHHELD',metrics:{SECRET:99}}}},{get:()=>({user:{id:'u'},capabilities:{canReadOwnAssessments:true}})});assert.ok(!JSON.stringify(await s.read('RUN_SUMMARY','execution-1')).includes('SECRET'))})
test('restart cannot discard an unconfirmed completed receipt',async()=>{const app=await setup((o,route)=>route.endsWith('/submit')?Promise.reject(new Error('lost')):undefined),unit=await filled(app);await assert.rejects(app.runtime.assessments.submit(unit));app.setRaw(scale(1,'COMPLETED'));await assert.rejects(app.runtime.assessments.restart(unit),{kind:'conflict'});assert.equal(app.p.calls.filter(c=>c.url.endsWith('/restart')).length,0)})
test('actual report clears blocks on hide and suppresses late read',async t=>{const app=await setup();let release;app.runtime.reports.read=()=>new Promise(resolve=>{release=()=>resolve({title:'private',blocks:[{text:'SECRET'}]})});const page=loadPage('report',app,t);page.onLoad({family:'SCALE',id:'attempt-1'});const pending=page.onShow();await new Promise(resolve=>setImmediate(resolve));page.onHide();release();await pending;assert.equal(page.data.blocks.length,0);page.onUnload()})

const draftKeyIn = app => [...app.p.stored.keys()].find(key=>key.includes(':draft:'))
const indexKeyIn = app => [...app.p.stored.keys()].find(key=>key.endsWith(':draft-index'))
test('body quota failure after index reservation repairs on process rebuild and permits new answers',async()=>{
 const app=await setup(),unit=await app.runtime.assessments.resume(handle),set=app.p.setStorage
 app.p.setStorage=o=>o.key.includes(':draft:')?queueMicrotask(()=>o.fail({errMsg:'quota exceeded'})):set(o)
 await assert.rejects(app.runtime.assessments.change(unit,'I1','0'),{kind:'storageUnavailable'})
 const index=indexKeyIn(app);assert.equal(app.p.stored.get(index).length,1);assert.equal(draftKeyIn(app),undefined)
 app.p.setStorage=set;const rebuilt=app.create();await rebuilt.session.restore();const restored=await rebuilt.assessments.resume(handle)
 assert.equal(restored.state,'draft');assert.deepEqual(app.p.stored.get(index),[])
 await rebuilt.assessments.change(restored,'I1','1');assert.equal(restored.draft.values.I1,'1')
 assert.equal(app.p.calls.filter(c=>c.url.endsWith('/submit')).length,0)
})
test('interrupted reserved index is repaired without changing another valid sealed submission',async()=>{
 const posts=[],app=await setup((o,route)=>route.endsWith('/submit')?(posts.push(structuredClone(o.data)),Promise.reject(new Error('lost'))):undefined),unit=await filled(app)
 await assert.rejects(app.runtime.assessments.submit(unit));const full=draftKeyIn(app),index=indexKeyIn(app),sealed=structuredClone(app.p.stored.get(full))
 app.p.stored.set(index,[...app.p.stored.get(index),full.replace(/attempt-1:/,'attempt-1:missing-')])
 const rebuilt=app.create();await rebuilt.session.restore();const restored=await rebuilt.assessments.resume(handle)
 assert.deepEqual(restored.draft.payload,posts[0]);assert.equal(restored.draft.commandId,sealed.commandId)
 assert.deepEqual(app.p.stored.get(full),sealed);assert.deepEqual(app.p.stored.get(index),[full]);await assert.rejects(rebuilt.assessments.submit(restored));assert.deepEqual(posts[1],posts[0])
})
test('a sealed body committed before an interrupted callback restores the exact command',async()=>{
 const app=await setup(),unit=await filled(app),set=app.p.setStorage
 app.p.setStorage=o=>{if(o.data?.state==='sealed'){app.p.stored.set(o.key,structuredClone(o.data));queueMicrotask(()=>o.fail({errMsg:'interrupted callback'}))}else set(o)}
 await assert.rejects(app.runtime.assessments.submit(unit),{kind:'storageUnavailable'});assert.equal(app.p.calls.filter(c=>c.url.endsWith('/submit')).length,0)
 const persisted=structuredClone(app.p.stored.get(draftKeyIn(app)));app.p.setStorage=set;await assert.rejects(app.runtime.assessments.change(unit,'I1','1'),{kind:'sealed'});assert.deepEqual(app.p.stored.get(draftKeyIn(app)),persisted);const rebuilt=app.create();await rebuilt.session.restore()
 const restored=await rebuilt.assessments.resume(handle);assert.equal(restored.draft.state,'sealed');assert.deepEqual(restored.draft,persisted)
 await assert.rejects(rebuilt.assessments.change(restored,'I1','1'),{kind:'sealed'})
})
test('body deleted before failed directory update recovers server completion instead of draftConflict',async()=>{
 const app=await setup((o,route)=>route.endsWith('/submit')?response({status:'COMPLETED'}):undefined),unit=await filled(app),set=app.p.setStorage
 app.p.setStorage=o=>o.key.endsWith(':draft-index')&&o.data.length===0?queueMicrotask(()=>o.fail({errMsg:'quota exceeded'})):set(o)
 await assert.rejects(app.runtime.assessments.submit(unit),{kind:'storageUnavailable'});const index=indexKeyIn(app)
 assert.equal(draftKeyIn(app),undefined);assert.equal(app.p.stored.get(index).length,1)
 app.p.setStorage=set;app.setRaw(scale(1,'COMPLETED'));const rebuilt=app.create();await rebuilt.session.restore()
 assert.equal((await rebuilt.assessments.resume(handle)).state,'submitted');assert.deepEqual(app.p.stored.get(index),[])
})
test('failed body deletion keeps sealed content recoverable and explicit repeated deletion is safe',async()=>{
 const app=await setup((o,route)=>route.endsWith('/submit')?Promise.reject(new Error('lost')):undefined),unit=await filled(app)
 await assert.rejects(app.runtime.assessments.submit(unit));const full=draftKeyIn(app),sealed=structuredClone(app.p.stored.get(full)),remove=app.p.removeStorage
 app.p.removeStorage=o=>queueMicrotask(()=>o.fail({errMsg:'disk unavailable'}))
 await assert.rejects(app.runtime.drafts.remove(unit.meta),{kind:'storageUnavailable'});assert.deepEqual(app.p.stored.get(full),sealed)
 app.p.removeStorage=remove;const rebuilt=app.create();await rebuilt.session.restore();assert.deepEqual((await rebuilt.assessments.resume(handle)).draft,sealed)
 await rebuilt.drafts.remove(unit.meta);await rebuilt.drafts.remove(unit.meta);assert.deepEqual(await rebuilt.drafts.pending(unit.meta.ownerId,'SCALE','attempt-1'),null)
})
test('damaged bodies and unknown read failures are never treated as missing or silently pruned',async()=>{
 const app=await setup(),unit=await filled(app),full=draftKeyIn(app),index=indexKeyIn(app),original=structuredClone(app.p.stored.get(full))
 for(const damaged of [null,false,{schemaVersion:99}]){app.p.stored.set(full,damaged);await assert.rejects(app.runtime.assessments.resume(handle),{kind:'draftConflict'});assert.deepEqual(app.p.stored.get(index),[full]);assert.deepEqual(app.p.stored.get(full),damaged)}
 app.p.stored.set(full,original);const get=app.p.getStorage;app.p.getStorage=o=>o.key===full?queueMicrotask(()=>o.fail({errMsg:'decryption key not found'})):get(o)
 await assert.rejects(app.runtime.assessments.resume(handle),{kind:'storageUnavailable'});assert.deepEqual(app.p.stored.get(index),[full]);assert.deepEqual(app.p.stored.get(full),original)
 app.p.getStorage=get;assert.deepEqual((await app.runtime.assessments.resume(handle)).draft.values,original.values)
})
test('directory repair failure can retry after space recovery without deleting a sealed body',async()=>{
 const app=await setup((o,route)=>route.endsWith('/submit')?Promise.reject(new Error('lost')):undefined),unit=await filled(app)
 await assert.rejects(app.runtime.assessments.submit(unit));const full=draftKeyIn(app),index=indexKeyIn(app),sealed=structuredClone(app.p.stored.get(full)),set=app.p.setStorage
 app.p.stored.set(index,[full,full+'missing']);app.p.setStorage=o=>queueMicrotask(()=>o.fail({errMsg:'quota exceeded'}))
 await assert.rejects(app.runtime.assessments.resume(handle),{kind:'storageUnavailable'});assert.deepEqual(app.p.stored.get(full),sealed)
 app.p.setStorage=set;assert.deepEqual((await app.runtime.assessments.resume(handle)).draft,sealed);assert.deepEqual(app.p.stored.get(index),[full])
})
test('a concurrent pending read waits for body write instead of pruning its reservation',async()=>{
 const app=await setup(),unit=await app.runtime.assessments.resume(handle),set=app.p.setStorage;let release
 app.p.setStorage=o=>o.key.includes(':draft:')?release=()=>set(o):set(o)
 const change=app.runtime.assessments.change(unit,'I1','0');await new Promise(resolve=>setImmediate(resolve));assert.equal(typeof release,'function')
 let finished=false;const pending=app.runtime.drafts.pending(unit.meta.ownerId,'SCALE','attempt-1').then(value=>{finished=true;return value})
 await new Promise(resolve=>setImmediate(resolve));assert.equal(finished,false);release();await change;assert.equal(await pending,null)
 assert.equal((await app.runtime.assessments.resume(handle)).draft.values.I1,1)
})
function scaleQuestionnaire(unitId='scale-1',instruction='请仅回顾过去两周。\n逐项作答。'){
 return {questionnaireAssessment:{id:'attempt-1',status:'IN_PROGRESS',deliveryMode:'FINAL_ONLY',attemptEpoch:1},questionnaire:{name:'整体问卷',instruction:'整体说明：请独立填写。'},currentScale:{name:'单元 '+unitId,instruction,scaleAssessmentId:unitId,definitionHash:hash,definition}}
}
test('runner preserves overall and current Scale instructions across unit advance and resumed answers',async t=>{
 const app=await setup((o,route)=>route.endsWith('/submit')?(app.setRaw(scaleQuestionnaire('scale-2','请回顾过去七天。')),response({status:'IN_PROGRESS'})):undefined)
 app.setRaw(scaleQuestionnaire());const page=loadPage('runner',app,t);page.onLoad({family:'QUESTIONNAIRE',rootId:'attempt-1',resourceId:'questionnaire-1'});await page.onShow()
 assert.equal(page.data.instruction,'整体说明：请独立填写。');assert.equal(page.data.unitTitle,'单元 scale-1');assert.equal(page.data.unitInstruction,'请仅回顾过去两周。\n逐项作答。')
 await page.change({detail:{value:'0'}});page.onHide();assert.equal(page.data.unitInstruction,'');await page.onShow();assert.equal(page.data.unitInstruction,'请仅回顾过去两周。\n逐项作答。');assert.equal(page.unit.draft.values.I1,1)
 page.next();await page.change({detail:{value:'0'}});await page.submit();assert.equal(page.data.unitTitle,'单元 scale-2');assert.equal(page.data.unitInstruction,'请回顾过去七天。');assert.equal(page.data.instruction,'整体说明：请独立填写。');page.onUnload()
})
test('Questionnaire and Composite form sections preserve canonical title and description, with both Composite shapes',()=>{
 const section={...questionnaire().currentFormSection,title:'背景区段',description:'仅填写本学期情况。\n保持原文。'}
 const q=normalize('QUESTIONNAIRE',{...questionnaire(),questionnaire:{name:'问卷',instruction:'整体问卷说明'},currentFormSection:section},'u','r')
 assert.equal(q.instruction,'整体问卷说明');assert.equal(q.unitTitle,section.title);assert.equal(q.unitInstruction,section.description)
 for(const currentItem of [{type:'FORM_SECTION',...section,items:undefined,answers:section.items},{type:'FORM_SECTION',formSection:section}]){
  const c=normalize('COMPOSITE',{id:'attempt-1',name:'综合',instruction:'综合说明',status:'IN_PROGRESS',deliveryMode:'FINAL_ONLY',attemptEpoch:1,currentItem},'u','r')
  assert.equal(c.instruction,'综合说明');assert.equal(c.unitTitle,section.title);assert.equal(c.unitInstruction,section.description)
 }
 const c=normalize('COMPOSITE',{id:'attempt-1',name:'综合',status:'IN_PROGRESS',deliveryMode:'FINAL_ONLY',attemptEpoch:1,currentItem:{type:'SCALE',id:'unit-1',definitionHash:hash,scale:{name:'子量表',instruction:'仅回顾昨天。',definition}}},'u','r')
 assert.equal(c.unitTitle,'子量表');assert.equal(c.unitInstruction,'仅回顾昨天。')
})
test('runner renders restored form instructions and removes prior instructions when the next unit has none',async t=>{
 const app=await setup();app.setRaw({...questionnaire(),questionnaire:{name:'问卷',instruction:'整体要求'},currentFormSection:{...questionnaire().currentFormSection,title:'本学期',description:'请仅回顾本学期。'}})
 const page=loadPage('runner',app,t);page.onLoad({family:'QUESTIONNAIRE',rootId:'attempt-1',resourceId:'questionnaire-1'});await page.onShow();await page.change({detail:{value:['0']}});page.onHide();await page.onShow()
 assert.equal(page.data.unitTitle,'本学期');assert.equal(page.data.unitInstruction,'请仅回顾本学期。');assert.deepEqual(page.unit.draft.values['form-1'],['a'])
 app.setRaw(questionnaire('section-2'));await page.retry();assert.equal(page.data.unitInstruction,'');assert.equal(page.data.unitTitle,'');assert.equal(page.data.instruction,'');page.onUnload()
 const wxml=fs.readFileSync(path.resolve(__dirname,'../pages/runner/index.wxml'),'utf8');assert.match(wxml,/\{\{instruction\}\}/);assert.match(wxml,/\{\{unitInstruction\}\}/);assert.match(wxml,/title="\{\{unitTitle\}\}"/)
})
