const {test}=require('node:test');const assert=require('node:assert/strict')
const {platform,response,csrf,session,user,mobile}=require('./helpers.cjs')
const {createRuntime}=require('../app/bootstrap/index');const {createCookieJar}=require('../core/auth/cookies');const {createStorage}=require('../core/storage/index')
const {createDomainService}=require('../domains/shared/service');const {createWorkspaceService}=require('../workspaces/service');const {navigationFor}=require('../app/navigation/index');const {resolveRole,destination}=require('../app/router/index');const {resolveCapabilities}=require('../app/capabilities/index');const {parseEntry,resolveEntry,KINDS}=require('../app/entry/index');const {fromResponse}=require('../core/errors/index')
const origin='https://acceptance.example'
function route(options){return options.url.slice((origin+'/api').length).split('?')[0]}
function apiPlatform(role='STUDENT',mustChangePassword=false) {return platform(options=>{
 const path=route(options)
 if(path==='/auth/csrf')return csrf()
 if(path==='/auth/login')return response({user:user(role,mustChangePassword)},200,session())
 if(path==='/auth/logout')return response(null,200,['ptool_session=; Max-Age=0; Path=/'])
 if(path==='/auth/me')return response(user(role,mustChangePassword))
 if(path==='/capabilities')return response({cognitive:false,situational:{supported:true}})
 if(path==='/courses/my/tasks')return response({list:[{id:'task-1',kind:'ASSIGNMENT',title:'任务',state:'IN_PROGRESS',canContinue:true,canStart:false,courses:[]}],total:1})
 if(['/courses','/courses/my','/users'].includes(path))return response({list:[{id:'item-1',title:'课程',username:'用户'}],total:1})
 if(path==='/organizations')return response({list:[{id:'org-1',name:'组织'}],total:1,allowedActions:[]})
 if(path==='/my-assessments')return response({list:[{taskId:'own-1',title:'本人任务',state:'ASSIGNED',subject:{userId:'other-child'}}],truncated:true})
 if(path==='/courses/item-1')return response({id:'item-1',title:'已授权课程'})
 if(path==='/organizations/org-1/context')return response({organization:{name:'组织'},allowedActions:['RUNS']})
 throw new Error('Unexpected request '+path)
})}
for(const role of ['STUDENT','PARENT','TEACHER','ADMIN'])test(role+' login, server discovery, home budget, logout, encrypted cold restore',async()=>{
 const p=apiPlatform(role);const runtime=createRuntime(p,origin)
 const state=await runtime.session.login({username:role,password:'secret123'})
 assert.equal(state.activeRole,role);assert.equal(state.user.role,role);assert.equal(state.capabilities.canReadChildReports,false)
 assert.equal(p.calls.length,4);assert.equal(p.calls[0].url,origin+'/api/auth/csrf')
 assert.equal(p.calls[1].header['X-CSRF-Token'],'csrf-one');assert.equal(p.calls[1].header.Cookie,'ptool_csrf=csrf-one')
 assert.ok(p.calls.slice(2).every(call=>call.header.Cookie.includes('ptool_session=test-session')))
 assert.ok(p.calls.every(call=>!Object.keys(call.header).some(key=>key.toLowerCase()==='authorization')))
 const domains=createDomainService(runtime.api,runtime.session);const workspace=createWorkspaceService(domains,runtime.session)
 const before=p.calls.length;const home=await workspace.home();assert.ok(home.blocks.length);assert.ok(p.calls.length-before<=2)
 assert.ok(navigationFor(state).length>=3)
 const restored=createRuntime(p,origin);assert.equal((await restored.session.restore()).activeRole,role)
 assert.equal(p.calls.length-before,home.blocks.length+2)
 await runtime.session.logout();assert.equal(runtime.session.get().user,null);assert.equal(p.stored.size,0)
})
test('mustChangePassword routes to password without business capabilities',async()=>{const r=createRuntime(apiPlatform('ADMIN',true),origin);const state=await r.session.refresh();assert.equal(destination(state),'/pages/auth/password/index');assert.equal(state.capabilities.canReadUsers,false)})
test('cold/warm refresh coalesces and counts exactly two bootstrap requests',async()=>{const p=apiPlatform();const r=createRuntime(p,origin);await Promise.all([r.session.refresh(),r.session.refresh(),r.session.refresh()]);assert.equal(p.calls.length,2)})
test('encrypted storage support unavailable never writes plaintext',async()=>{const p=apiPlatform();p.canIUse=()=>false;const r=createRuntime(p,origin);await assert.rejects(r.session.login({username:'test',password:'secret123'}),error=>error.kind==='storageUnavailable');assert.equal(p.stored.size,0)})
test('bad login/public 401 does not invalidate current authenticated session',async()=>{const p=apiPlatform();const r=createRuntime(p,origin);await r.session.refresh();p.request=options=>queueMicrotask(()=>options.success(response(null,401)));await assert.rejects(r.api.post('/auth/login',{}));assert.ok(r.session.get().user);await assert.rejects(r.api.get('/public/assessments/opaque',{retry:false}));assert.ok(r.session.get().user)})
test('protected 401 clears session and saved cookies',async()=>{const p=apiPlatform();const r=createRuntime(p,origin);await r.session.login({username:'test',password:'secret123'});p.request=options=>queueMicrotask(()=>options.success(response(null,401)));await assert.rejects(r.api.get('/courses'));assert.equal(r.session.get().user,null);assert.equal(p.stored.size,0)})
test('public calls never carry session cookies or CSRF',async()=>{const p=apiPlatform();const r=createRuntime(p,origin);await r.session.login({username:'test',password:'secret123'});p.request=options=>{assert.equal(options.header.Cookie,undefined);assert.equal(options.header['X-CSRF-Token'],undefined);queueMicrotask(()=>options.success(response({ok:true})))};await r.api.post('/public/assessments/opaque',{})})
test('concurrent mutations share one CSRF request and never replay writes',async()=>{const p=platform(o=>route(o)==='/auth/csrf'?csrf():response(null,500));const r=createRuntime(p,origin);await Promise.all([assert.rejects(r.api.post('/one',{})),assert.rejects(r.api.post('/two',{}))]);assert.equal(p.calls.filter(c=>route(c)==='/auth/csrf').length,1);assert.equal(p.calls.filter(c=>c.method==='POST').length,2)})
test('safe GET bounded retry, rate limit Retry-After, offline state',async()=>{let count=0;const p=platform(()=>++count===1?response(null,500):response({ok:true}));const r=createRuntime(p,origin);assert.deepEqual(await r.api.get('/resource'),{ok:true});assert.equal(count,2);p.request=o=>queueMicrotask(()=>o.success(response(null,429,[],{'Retry-After':'12'})));await assert.rejects(r.api.get('/resource'),e=>e.kind==='rateLimited'&&e.retryAfterMs===12000);p.networkChange({isConnected:false});await assert.rejects(r.api.post('/resource',{}),e=>e.kind==='offline')})
test('network mutation failure leaves session intact and makes no mutation retry',async()=>{const p=apiPlatform();const r=createRuntime(p,origin);await r.session.login({username:'test',password:'secret123'});let count=0;p.request=o=>{count++;queueMicrotask(()=>o.fail({errMsg:'secret detail'}))};await assert.rejects(r.api.post('/resource',{}),e=>e.kind==='network');assert.equal(count,1);assert.ok(r.session.get().user)})
test('logout rejects late old responses including cookies and 401 after new login',async()=>{const p=apiPlatform();const r=createRuntime(p,origin);await r.session.login({username:'test',password:'secret123'});let late;const original=p.request;p.request=o=>{late=o};const pending=r.api.get('/courses',{retry:false});await r.session.expire();p.request=original;await r.session.login({username:'test',password:'secret123'});late.success(response(null,401,['ptool_session=old-user; Max-Age=1000']));await assert.rejects(pending,e=>e.kind==='sessionChanged');assert.ok(r.session.get().user);const store=[...p.stored.values()][0];assert.equal(store.cookies.ptool_session.value,'test-session')})
test('logout during current-user refresh cannot repopulate user',async()=>{let resolveMe;const p=apiPlatform();const r=createRuntime(p,origin);const original=p.request;p.request=o=>route(o)==='/auth/me'?resolveMe=o:original(o);const pending=r.session.refresh();await r.session.expire();resolveMe.success(response(user()));await pending;assert.equal(r.session.get().user,null)})
test('logout clears local state even when server/network logout fails',async()=>{const p=apiPlatform();const r=createRuntime(p,origin);await r.session.login({username:'test',password:'secret123'});p.request=o=>queueMicrotask(()=>o.fail({}));await assert.rejects(r.session.logout());assert.equal(r.session.get().user,null);assert.equal(p.stored.size,0)})
test('cookie parsing handles combined Expires commas, allowlists names and expiry',async()=>{let now=1000;const p=platform(()=>response(null));const storage=createStorage(p,origin);const jar=createCookieJar(storage,()=>now);await jar.absorb({header:{'Set-Cookie':'ptool_session=one; Max-Age=5; Expires=Wed, 01 Jan 2030 00:00:00 GMT, ptool_csrf=two; Max-Age=5, tracking=secret; Max-Age=100'}},jar.epoch());assert.equal(jar.header(),'ptool_session=one; ptool_csrf=two');now=7000;assert.equal(jar.header(),'');assert.equal(jar.hasSession(),false);await jar.clear();assert.equal(p.stored.size,0)})
test('foreign origin storage cannot restore another backend cookie',async()=>{const p=apiPlatform();const first=createRuntime(p,origin);await first.session.login({username:'test',password:'secret123'});let cookie;p.request=o=>{cookie=o.header.Cookie;queueMicrotask(()=>o.success(response(null,401)))};await createRuntime(p,'https://other.example').session.restore();assert.equal(cookie,undefined)})
for(const status of [403,404,409,410,429,500,503])test('maps HTTP '+status+' with safe UI message',()=>{const error=fromResponse(response(null,status,[],{'X-Request-ID':'request-123'}));assert.equal(error.status,status);assert.equal(error.requestId,'request-123');assert.ok(error.message);assert.ok(!error.message.includes('操作成功'))})
test('wrong/unknown server role or capability schema fails closed',()=>{assert.throws(()=>resolveRole({role:'SYSTEM_ADMIN',mobile:mobile('ADMIN')}));assert.throws(()=>resolveRole({role:'PARENT',mobile:mobile('ADMIN')}));assert.throws(()=>resolveCapabilities({schemaVersion:2,capabilities:{canReadUsers:true}}));assert.equal(resolveCapabilities({schemaVersion:1,capabilities:{canReadUsers:'true'}}).canReadUsers,false)})
test('role does not grant organization actions; detail keeps server allowedActions only',async()=>{const p=apiPlatform('ADMIN');const r=createRuntime(p,origin);await r.session.refresh();const d=createDomainService(r.api,r.session);assert.deepEqual((await d.detail('organizations','org-1')).availableActions,['RUNS']);assert.equal(r.session.get().capabilities.canReadChildReports,false)})
test('forbidden domains rejected before request and invalid resource ids cannot inject paths',async()=>{const p=apiPlatform('PARENT');const r=createRuntime(p,origin);await r.session.refresh();const d=createDomainService(r.api,r.session);const before=p.calls.length;await assert.rejects(d.list('users'),e=>e.kind==='forbidden');await assert.rejects(d.detail('organizations','../other'),e=>e.kind==='invalidRequest');assert.equal(p.calls.length,before)})
for(const path of ['https://evil.example','//evil.example','/x\\y','/x#fragment','/x\n'])test('API rejects invalid path '+JSON.stringify(path),async()=>{const r=createRuntime(apiPlatform(),origin);await assert.rejects(r.api.get(path),e=>e.kind==='invalidRequest')})
test('QR handles only known origin and rejects ambiguous input',()=>{assert.deepEqual(parseEntry({q:encodeURIComponent(origin+'/mini/entry?kind=course&id=course-1')},origin),{kind:'course',id:'course-1',requiresAuth:true});for(const q of ['https://evil.example/mini/entry?kind=course&id=one',origin+'.evil/mini/entry?kind=course&id=one','kind=course&id=../secret','kind=course&id=one&id=two','kind=course&id=one&redirect=https://evil.example','%GG'])assert.throws(()=>parseEntry({q},origin));assert.equal(parseEntry({},origin),null)})
for(const kind of KINDS)test('recognizes '+kind+' entry without granting resource authorization',()=>{const input=['public','anonymous'].includes(kind)?{kind,token:'opaque-123456789012345'}:{kind,id:'resource-1'};assert.equal(parseEntry(input,origin).kind,kind)})
test('entry defers login preserving resource, verifies course with backend, unsupported public never forces login',async()=>{const e=parseEntry({kind:'course',id:'course-1'},origin);assert.equal((await resolveEntry(e,{user:null},{})).status,'login');let authorized=false;const dest=await resolveEntry(e,{user:user()}, {async detail(domain,id){authorized=domain==='courses'&&id==='course-1'}});assert.ok(authorized);assert.equal(dest.status,'ready');assert.equal((await resolveEntry({kind:'public',requiresAuth:false},{user:null},{})).status,'unavailable');await assert.rejects(resolveEntry(e,{user:user()},{detail:()=>Promise.reject(new Error('forbidden'))}))})
module.exports={apiPlatform,origin}

test('canonical existing Web course and public QR paths are recognized without redirects',()=>{
  assert.deepEqual(parseEntry({q:origin+'/student/courses/course-1'},origin),{kind:'course',id:'course-1',requiresAuth:true})
  const entry=parseEntry({q:origin+'/public/questionnaire/opaque-123456789012345'},origin)
  assert.equal(entry.requiresAuth,false);assert.equal(entry.resourceFamily,'questionnaire')
  assert.throws(()=>parseEntry({q:origin+'/student/courses/course-1?redirect=evil'},origin))
})
test('failed async credential removal falls back to synchronous deletion',async()=>{
  const p=apiPlatform();const r=createRuntime(p,origin);await r.session.login({username:'test',password:'secret123'})
  p.removeStorage=o=>queueMicrotask(()=>o.fail({}));p.removeStorageSync=key=>p.stored.delete(key)
  await r.session.expire();assert.equal(p.stored.size,0)
})
