const { workspacePage } = require('../../app/pages/index')
Page(workspacePage({
 setup(options){this.classroomId=options.id||null;this.code=options.code||'';this.answer='';this.active=true;this.timer=null;this.snapshot=null},
 reset(){this.stop();this.answer='';this.snapshot=null;this.classroomId=null},
 async fetch(runtime){this.active=true;if(!this.classroomId)return {title:'加入课堂',code:this.code,joinReady:true};const snapshot=await runtime.classrooms.state(this.classroomId);const result=this.project(snapshot);this.schedule();return result},
 methods:{
 stop(){this.active=false;if(this.timer)clearTimeout(this.timer);this.timer=null},
 onHide(){this.sequence+=1;this.stop();this.answer='';this.setData({answer:'',question:null,questions:[],canSubmit:false})},
 project(snapshot){const question=snapshot.question,proof=question?question.id+':'+question.startedAt:null;if(proof!==this.questionProof){this.answer='';this.questionProof=proof;this.sealed=null}this.snapshot=snapshot;const content=question&&question.questionContent||{};const choices=Array.isArray(content.options)?content.options.map(o=>({value:o.value,label:o.label})):[];const remaining=question?Math.max(0,Math.ceil((Date.parse(question.startedAt)+(question.timeLimit||60)*1000-Date.parse(snapshot.serverNow))/1000)):0;
  return {title:snapshot.classroom.name,description:snapshot.classroom.status,joinReady:false,question,questionText:content.question||'',choices,multiple:content.type==='multiple_choice',answer:this.answer,remaining,submitted:snapshot.submitted===true,canSubmit:snapshot.availableActions.includes('SUBMIT'),canLeave:snapshot.availableActions.includes('LEAVE'),canStart:snapshot.availableActions.includes('START'),canEnd:snapshot.availableActions.includes('END'),canClose:snapshot.availableActions.includes('CLOSE'),questions:(snapshot.questions||[]).map(q=>({id:q.id,title:q.questionContent&&q.questionContent.question||'题目',detail:'时限 '+(q.timeLimit||60)+' 秒',canOpen:snapshot.availableActions.includes('START')})),notice:snapshot.classroom.status==='ENDED'?'课堂已结束':!question?'等待老师开始题目':snapshot.submitted?'服务器已确认提交':'',statsFacts:snapshot.stats?[{label:'已提交人数',value:String(snapshot.stats.answerCount)},{label:'未离开课堂的会话数',value:String(snapshot.stats.totalSessions)}]:[],optionStats:snapshot.stats?Object.entries(snapshot.stats.optionStats||{}).map(([key,value])=>({label:key,value:String(value)})):[],pollError:'',commandError:''}
 },
 schedule(){if(!this.active||this.timer||!this.snapshot||this.snapshot.classroom.status==='ENDED')return;this.timer=setTimeout(()=>{this.timer=null;this.poll()},1500)},
 async poll(){if(!this.active||this.data.status==='submitting'){this.schedule();return}const sequence=this.sequence;try{const snapshot=await getApp().runtime.classrooms.state(this.classroomId);if(!this.active||sequence!==this.sequence)return;this.setData(this.project(snapshot));this.schedule()}catch(error){if(this.active&&sequence===this.sequence){this.stop();this.setData({pollError:error.message+'。连接恢复后请刷新课堂。',canSubmit:false,canStart:false,canEnd:false,canClose:false})}}},
 changeCode(e){this.code=e.detail.value},
 changeAnswer(e){if(this.data.status!=='submitting'&&!this.sealed){this.answer=e.detail.value;this.setData({answer:this.answer})}},
 async join(){if(this.data.status==='submitting')return;const sequence=this.sequence;this.setData({status:'submitting',commandError:''});try{const result=await getApp().runtime.classrooms.join(this.code);if(sequence!==this.sequence)return;this.classroomId=result.classroomId;await this.load()}catch(error){if(sequence===this.sequence)this.setData({status:'ready',commandError:error.message})}},
 async command(action,body){if(this.data.status==='submitting'||!this.snapshot)return;const sequence=this.sequence;this.setData({status:'submitting',commandError:''});try{await getApp().runtime.classrooms.command(this.classroomId,action,body,this.snapshot);if(sequence!==this.sequence)return;if(action==='LEAVE'){this.stop();wx.navigateBack({delta:1});return}this.sealed=null;this.setData({status:'ready'});await this.load()}catch(error){if(sequence!==this.sequence)return;this.setData({status:'ready',commandError:error.message});await this.poll()}},
 submit(){if(!this.data.canSubmit||!this.snapshot.question)return;const value=Array.isArray(this.answer)?this.answer.join(','):String(this.answer||'');if(!value.trim()){this.setData({commandError:'请先填写答案'});return}if(!this.sealed)this.sealed={questionId:this.snapshot.question.id,startedAt:this.snapshot.question.startedAt,answer:value};return this.command('SUBMIT',this.sealed)},
 start(e){const question=this.data.questions.find(q=>q.id===e.detail.id);if(question&&this.data.canStart)return this.command('START',{questionId:question.id})},
 end(){if(this.data.canEnd&&this.snapshot.question)return this.command('END',{questionId:this.snapshot.question.id,startedAt:this.snapshot.question.startedAt})},
 close(){if(!this.data.canClose||this.data.status==='submitting')return;wx.showModal({title:'结束课堂',content:'确认结束当前课堂？学生将无法继续作答。',success:r=>{if(r.confirm&&this.active)this.command('CLOSE',{})}})},
 leave(){if(this.data.canLeave)return this.command('LEAVE',{})},
 }}))
