// AUTO-GENERATED by scripts/generate-scale-instruments.ts. DO NOT EDIT.
// Production runtime imports this static file and never scans the filesystem.
import { SCALE_INSTRUMENT_SOURCE as source0 } from '../instruments/adexi_v1/2.0.0/instrument'
import { SCALE_INSTRUMENT_SOURCE as source1 } from '../instruments/cbi_en/1.0.0/instrument'
import { SCALE_INSTRUMENT_SOURCE as source2 } from '../instruments/copsoq3_job_satisfaction_en/1.0.0/instrument'
import { SCALE_INSTRUMENT_SOURCE as source3 } from '../instruments/dass21_zh_cn/1.0.0/instrument'
import { SCALE_INSTRUMENT_SOURCE as source4 } from '../instruments/gse_zh_cn/1.0.0/instrument'
import { SCALE_INSTRUMENT_SOURCE as source5 } from '../instruments/hse_msit_en/1.0.0/instrument'
import { SCALE_INSTRUMENT_SOURCE as source6 } from '../instruments/jcq_en/1.0.0/instrument'
import { SCALE_INSTRUMENT_SOURCE as source7 } from '../instruments/mpfi24_zh_cn/1.0.0/instrument'
import { SCALE_INSTRUMENT_SOURCE as source8 } from '../instruments/pss10_zh_cn/1.0.0/instrument'
import { SCALE_INSTRUMENT_SOURCE as source9 } from '../instruments/sdq_parent_zh_cn/1.0.0/instrument'
import { SCALE_INSTRUMENT_SOURCE as source10 } from '../instruments/sdq_teacher_zh_cn/1.0.0/instrument'
import { SCALE_INSTRUMENT_SOURCE as source11 } from '../instruments/texi_parent_zh_cn/1.0.0/instrument'
import { SCALE_INSTRUMENT_SOURCE as source12 } from '../instruments/texi_teacher_zh_cn/1.0.0/instrument'
import { SCALE_INSTRUMENT_SOURCE as source13 } from '../instruments/tswq_en/1.0.0/instrument'
import { SCALE_INSTRUMENT_SOURCE as source14 } from '../instruments/who5/1.0.0/instrument'
import type { ScaleInstrumentSourceV1, ScalePackageV2, VersionedScorerRegistration } from './types'

/** Legacy descriptor arrays are intentionally empty after PR-4 source migration. */
export const GENERATED_EXECUTABLE_SCALE_PACKAGES: readonly ScalePackageV2[] = []
export const GENERATED_SCALE_SCORER_PLUGINS: readonly VersionedScorerRegistration[] = []

export const GENERATED_SCALE_INSTRUMENT_SOURCES: readonly ScaleInstrumentSourceV1[] = [
  source0,
  source1,
  source2,
  source3,
  source4,
  source5,
  source6,
  source7,
  source8,
  source9,
  source10,
  source11,
  source12,
  source13,
  source14,
]
