// AUTO-GENERATED by scripts/generate-scale-instruments.ts. DO NOT EDIT.
// Build-time discovery uses the fixed *.instrument.ts descriptor convention.
// Production runtime imports this static file and never scans the filesystem.
import * as entry0 from './entries/adexi_v1__2_0_0.instrument'
import * as entry1 from './entries/sdq_parent_zh_cn__1_0_0.instrument'
import * as entry2 from './entries/sdq_teacher_zh_cn__1_0_0.instrument'
import * as entry3 from './entries/texi_parent_zh_cn__1_0_0.instrument'
import * as entry4 from './entries/texi_teacher_zh_cn__1_0_0.instrument'
import * as entry5 from './entries/who5__1_0_0.instrument'
import type { ScalePackageV2, VersionedScorerRegistration } from './types'

export const GENERATED_EXECUTABLE_SCALE_PACKAGES: readonly ScalePackageV2[] = [
  entry0.EXECUTABLE_SCALE_PACKAGE,
  entry1.EXECUTABLE_SCALE_PACKAGE,
  entry2.EXECUTABLE_SCALE_PACKAGE,
  entry3.EXECUTABLE_SCALE_PACKAGE,
  entry4.EXECUTABLE_SCALE_PACKAGE,
  entry5.EXECUTABLE_SCALE_PACKAGE,
]

export const GENERATED_SCALE_SCORER_PLUGINS: readonly VersionedScorerRegistration[] = [
  ...entry0.SCALE_SCORER_PLUGINS,
  ...entry1.SCALE_SCORER_PLUGINS,
  ...entry2.SCALE_SCORER_PLUGINS,
  ...entry3.SCALE_SCORER_PLUGINS,
  ...entry4.SCALE_SCORER_PLUGINS,
  ...entry5.SCALE_SCORER_PLUGINS,
]
