const { workspacePage } = require('../../app/pages/index')
Page(workspacePage({setup(o){this.domain=o.domain;this.parent=o.parent;this.view=o.view;this.id=o.id;this.page=Number(o.page)||1;this.visible=true},reset(){this.visible=false},async fetch(runtime){if(this.domain==='classrooms'&&this.view==='questions'){const [data,context]=await Promise.all([runtime.operations.question(this.parent,this.id,'stats'),runtime.operations.questionContext(this.parent,this.id)]);this.question=data.question;return {title:'课堂题目',content:data.question.questionContent.question||'',facts:[{label:'已提交人数',value:String(data.stats.answerCount)},{label:'未离开课堂的会话数',value:String(data.stats.totalSessions)}],answers:Object.entries(data.stats.optionStats||{}).map(([key,value])=>({label:key,value:String(value)})).concat((data.stats.textAnswers||[]).map((a,i)=>({label:'回答 '+(i+1),value:a.text}))),canEditQuestion:context.allowedActions.includes('edit'),canDeleteQuestion:context.allowedActions.includes('delete'),questionText:data.question.questionContent.question||'',timeLimit:String(data.question.timeLimit||60),questionError:''}}const result=await runtime.operations.list(this.domain,{page:this.page,parent:this.parent||undefined,view:this.view});const row=result.list.find(item=>item.id===this.id);if(!row)throw new Error('记录不存在或当前无权查看');return {title:row.title,content:row.value.content||'',facts:[{label:'状态',value:row.status},{label:'评语',value:row.value.comment||'无'}],answers:Object.entries(row.value.answers||{}).map(([key,value])=>({label:key,value:String(value)})),canGrade:this.domain==='assignments'&&this.view==='submissions',canRoster:this.domain==='students'&&Boolean(this.parent),student:row.value,comment:'',actionError:'',publicLink:this.view==='tokens'&&row.value.token?runtime.operations.publicLink(row.value.token):''}},methods:{
 copyLink(){if(this.data.publicLink)wx.setClipboardData({data:this.data.publicLink})},
 async revokeToken(){if(!this.data.publicLink||this.data.status==='submitting')return;const sequence=this.sequence;const confirm=await new Promise(resolve=>wx.showModal({title:'撤销公开链接',content:'撤销后此链接无法再用于打卡。',success:resolve,fail:()=>resolve({confirm:false})}));if(!confirm.confirm||sequence!==this.sequence)return;this.setData({status:'submitting'});try{await getApp().runtime.operations.revokeToken(this.id);if(sequence===this.sequence){this.setData({publicLink:'',status:'ready'});wx.navigateBack({delta:1})}}catch(e){if(sequence===this.sequence)this.setData({status:'ready',actionError:e.message})}},
 questionChange(e){if(this.data.status!=='submitting')this.setData({[e.currentTarget.dataset.key]:e.detail.value})},
 async questionCommand(e){if(this.data.status==='submitting')return;const action=e.currentTarget.dataset.action;if(action==='edit'&&!this.data.canEditQuestion||action==='delete'&&!this.data.canDeleteQuestion)return;const sequence=this.sequence;const confirmation=await new Promise(resolve=>wx.showModal({title:action==='delete'?'删除课堂题目':'保存题目',content:action==='delete'?'确认删除当前题目？':'确认更新当前题目与时间限制？',success:resolve,fail:()=>resolve({confirm:false})}));if(!confirmation.confirm||sequence!==this.sequence)return;const timeLimit=Number(this.data.timeLimit);if(action==='edit'&&(!this.data.questionText.trim()||!Number.isSafeInteger(timeLimit)||timeLimit<1||timeLimit>3600)){this.setData({questionError:'请填写题目，时长须为 1 至 3600 秒'});return}this.setData({status:'submitting'});try{await getApp().runtime.operations.question(this.parent,this.id,action,action==='edit'?{questionContent:Object.assign({},this.question.questionContent,{question:this.data.questionText}),timeLimit}:undefined);if(sequence!==this.sequence)return;if(action==='delete')wx.navigateBack({delta:1});else await this.load()}catch(e){if(sequence===this.sequence)this.setData({status:'ready',questionError:e.message})}},
 change(e){this.setData({comment:e.detail.value})},async grade(){if(this.data.status==='submitting')return;const sequence=this.sequence;this.setData({status:'submitting'});try{await getApp().runtime.operations.grade(this.parent,this.id,this.data.comment);if(sequence===this.sequence)await this.load()}catch(e){if(sequence===this.sequence)this.setData({status:'ready',actionError:e.message})}},
 async roster(e){if(this.data.status==='submitting'||!this.data.canRoster)return;const action=e.currentTarget.dataset.action;const result=await new Promise(resolve=>wx.showModal({title:'确认学生操作',content:action==='remove'?'将移除该学生的课程关系。':action==='resetPassword'?'重置后必须通过受保护的服务器交接文件提供临时密码。':'冻结/解冻作用于学生账户，后端会检查组织管理员保留条件。',success:resolve,fail:()=>resolve({confirm:false})}));if(!result.confirm||!this.visible)return;const sequence=this.sequence;this.setData({status:'submitting'});try{await getApp().runtime.operations.roster(this.parent,this.id,action);if(sequence===this.sequence){wx.showToast({title:'操作已完成'});await this.load()}}catch(e){if(sequence===this.sequence)this.setData({status:'ready',actionError:e.message})}},
}}))
