import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const target = resolve(process.cwd(), 'src/modules/scale/onboarding/instruments.generated.ts')
const expected = `// AUTO-GENERATED by scripts/generate-scale-instruments.ts. DO NOT EDIT.
// PR-1 keeps existing package files as the executable facts; PR-4 migrates
// those facts into per-instrument source directories without changing this API.
import { ADEXI_V2_PACKAGE } from '../packages/adexi-v2'
import { WHO5_ZH_CN_V1_PACKAGE } from '../packages/who5-zh-cn-v1'
import { SDQ_PARENT_ZH_CN_V1_PACKAGE } from '../packages/sdq-parent-zh-cn-v1'
import { SDQ_TEACHER_EN_T4_10_V1_PACKAGE } from '../packages/sdq-teacher-en-t4-10-v1'
import { TEXI_PARENT_EN_V1_PACKAGE, TEXI_TEACHER_EN_V1_PACKAGE } from '../packages/texi-en-v1'
import { SDQ_TEACHER_SCORER_KEY, sdqTeacherT410Scorer } from '../packages/sdq-teacher-impact-scorer'
import type { ScalePackageV2, VersionedScorerRegistration } from './types'

export const GENERATED_EXECUTABLE_SCALE_PACKAGES: readonly ScalePackageV2[] = [
  ADEXI_V2_PACKAGE,
  WHO5_ZH_CN_V1_PACKAGE,
  SDQ_PARENT_ZH_CN_V1_PACKAGE,
  SDQ_TEACHER_EN_T4_10_V1_PACKAGE,
  TEXI_PARENT_EN_V1_PACKAGE,
  TEXI_TEACHER_EN_V1_PACKAGE,
]

export const GENERATED_SCALE_SCORER_PLUGINS: readonly VersionedScorerRegistration[] = [
  {
    key: SDQ_TEACHER_SCORER_KEY,
    version: SDQ_TEACHER_EN_T4_10_V1_PACKAGE.definition.scoring.scoringVersion,
    scorer: sdqTeacherT410Scorer,
  },
]
`

if (process.argv.includes('--check')) {
  const current = readFileSync(target, 'utf8')
  if (current !== expected) {
    console.error('Scale instrument generated index is stale. Run: npm run scale:instruments:generate')
    process.exit(1)
  }
  process.exit(0)
}

writeFileSync(target, expected, 'utf8')
