import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, resolve, relative } from 'node:path'

const entriesDir = resolve(process.cwd(), 'src/modules/scale/onboarding/entries')
const target = resolve(process.cwd(), 'src/modules/scale/onboarding/instruments.generated.ts')

const entryFiles = readdirSync(entriesDir)
  .filter((filename) => filename.endsWith('.instrument.ts'))
  .sort((left, right) => left.localeCompare(right))

if (entryFiles.length === 0) {
  throw new Error('No Scale instrument entry descriptors found')
}

const imports = entryFiles.map((filename, index) => (
  `import * as entry${index} from './entries/${basename(filename, '.ts')}'`
)).join('\n')
const packageEntries = entryFiles.map((_, index) => `  entry${index}.EXECUTABLE_SCALE_PACKAGE,`).join('\n')
const scorerEntries = entryFiles.map((_, index) => `  ...entry${index}.SCALE_SCORER_PLUGINS,`).join('\n')

const sourceRoot = resolve(process.cwd(), 'src/modules/scale/instruments')
const discoverSources = (dir: string): string[] => !existsSync(dir) ? [] : readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
  const path = resolve(dir, entry.name)
  return entry.isDirectory() ? discoverSources(path) : entry.name === 'instrument.ts' ? [path] : []
}).sort()
const sourceFiles = discoverSources(sourceRoot)
const sourceImports = sourceFiles.map((path, index) => `import { SCALE_INSTRUMENT_SOURCE as source${index} } from '${relative(resolve(target, '..'), path).replace(/\\/g, '/').replace(/\.ts$/, '')}'`).join('\n')
const sourceEntries = sourceFiles.map((_, index) => `  source${index},`).join('\n')

const expected = `// AUTO-GENERATED by scripts/generate-scale-instruments.ts. DO NOT EDIT.\n// Build-time discovery uses the fixed *.instrument.ts descriptor convention.\n// Production runtime imports this static file and never scans the filesystem.\n${imports}\n${sourceImports}\nimport type { ScaleInstrumentSourceV1, ScalePackageV2, VersionedScorerRegistration } from './types'\n\nexport const GENERATED_EXECUTABLE_SCALE_PACKAGES: readonly ScalePackageV2[] = [\n${packageEntries}\n]\n\nexport const GENERATED_SCALE_SCORER_PLUGINS: readonly VersionedScorerRegistration[] = [\n${scorerEntries}\n]\n\nexport const GENERATED_SCALE_INSTRUMENT_SOURCES: readonly ScaleInstrumentSourceV1[] = [\n${sourceEntries}\n]\n`

if (process.argv.includes('--check')) {
  const current = readFileSync(target, 'utf8')
  if (current !== expected) {
    console.error('Scale instrument generated index is stale. Run: npm run scale:instruments:generate')
    process.exit(1)
  }
  process.exit(0)
}

writeFileSync(target, expected, 'utf8')
