import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, resolve } from 'node:path'

const entriesDir = resolve(process.cwd(), 'src/modules/scale/onboarding/entries')
const target = resolve(process.cwd(), 'src/modules/scale/onboarding/instruments.generated.ts')

const entryFiles = readdirSync(entriesDir)
  .filter((filename) => filename.endsWith('.instrument.ts'))
  .sort((left, right) => left.localeCompare(right))

if (entryFiles.length === 0) {
  throw new Error('No Scale instrument entry descriptors found')
}

const imports = entryFiles.map((filename, index) => (
  `import * as entry${index} from './entries/${basename(filename, '.ts')}'`
)).join('\n')
const packageEntries = entryFiles.map((_, index) => `  entry${index}.EXECUTABLE_SCALE_PACKAGE,`).join('\n')
const scorerEntries = entryFiles.map((_, index) => `  ...entry${index}.SCALE_SCORER_PLUGINS,`).join('\n')

const expected = `// AUTO-GENERATED by scripts/generate-scale-instruments.ts. DO NOT EDIT.\n// Build-time discovery uses the fixed *.instrument.ts descriptor convention.\n// Production runtime imports this static file and never scans the filesystem.\n${imports}\nimport type { ScalePackageV2, VersionedScorerRegistration } from './types'\n\nexport const GENERATED_EXECUTABLE_SCALE_PACKAGES: readonly ScalePackageV2[] = [\n${packageEntries}\n]\n\nexport const GENERATED_SCALE_SCORER_PLUGINS: readonly VersionedScorerRegistration[] = [\n${scorerEntries}\n]\n`

if (process.argv.includes('--check')) {
  const current = readFileSync(target, 'utf8')
  if (current !== expected) {
    console.error('Scale instrument generated index is stale. Run: npm run scale:instruments:generate')
    process.exit(1)
  }
  process.exit(0)
}

writeFileSync(target, expected, 'utf8')
